# Taste and Craft Skill
# Building things that matter - the pursuit of quality

id: taste-and-craft
name: Taste and Craft
category: strategy
version: 1.0.0
last_updated: 2025-12-19

description: |
  Good taste is knowing what is good. Craft is making it real. Together they
  separate products people tolerate from products people love. Paul Graham's
  essays explore how taste develops and why it matters.

  This skill synthesizes PG's wisdom on quality, simplicity, and the details
  that separate great from good.

triggers:
  keywords:
    - taste
    - craft
    - quality
    - simplicity
    - design principles
    - attention to detail
    - good vs great
    - polish
  contexts:
    - Making quality decisions
    - Developing taste
    - Pushing for excellence

principles:
  - name: Taste is learned, not innate
    description: |
      Taste is knowing what is good. It can be developed. Study great work.
      Understand why it is great. Compare to lesser work. See the difference.
      Taste grows through exposure and analysis.
    source: Taste for Makers
    examples:
      good: Studying great products, understanding principles, applying them
      bad: Assuming taste is innate, not investing in developing it

  - name: Simple is hard
    description: |
      Simplicity requires understanding what is essential. Anyone can add
      complexity. Removing it requires knowing what matters. Simple solutions
      are not lazy - they are the hardest to achieve.
    source: Six Principles for Making New Things
    examples:
      good: Feature works perfectly with minimal UI, obvious how to use
      bad: Feature has many options, settings, configurations

  - name: Details reveal care
    description: |
      Users notice when details are right, even if they cannot articulate why.
      Misaligned elements, inconsistent spacing, awkward copy - these signal
      lack of care. Getting details right signals quality throughout.
    source: Taste for Makers
    examples:
      good: Every element aligned, every interaction smooth, every word intentional
      bad: Close enough, ship it, users will not notice

  - name: Good people make good things
    description: |
      Quality of work reflects quality of people and culture. Hire people who
      care about craft. Create environment where quality matters. Be good,
      and you will make good things.
    source: Be Good
    examples:
      good: Team debates details, pushes for better, celebrates quality
      bad: Team ships minimum viable, nobody cares about craft

  - name: Timeless over trendy
    description: |
      Trends pass. Timeless principles endure. Simple, clean, bold choices
      last. Gimmicks date. Build for 10 years, not 10 months.
    source: Six Principles for Making New Things
    examples:
      good: Design that looked good 5 years ago and will look good in 5 years
      bad: Following current design trends that will look dated soon

anti_patterns:
  - name: Complexity as sophistication
    description: Adding complexity to seem advanced
    example: Many features, many options, many settings
    why_bad: Users want simplicity. Complexity is often laziness in disguise.
    fix: Remove until it breaks. What is the minimum that delivers value?

  - name: Quality later
    description: Assuming you can add quality after shipping
    example: Ship fast, polish later (later never comes)
    why_bad: Quality is a habit, not a phase. Patterns set early persist.
    fix: Build quality in from the start. Slower initially, faster overall.

  - name: Ignoring details
    description: Dismissing small imperfections as unimportant
    example: Slightly off alignment, typos, inconsistent styles
    why_bad: Users feel it even if they cannot articulate it. Trust erodes.
    fix: Sweat the details. They are the surface of deeper quality.

  - name: Trend chasing
    description: Adopting whatever is currently popular
    example: Redesigning to match latest design trends every year
    why_bad: Constant change is disorienting. Trends date quickly.
    fix: Choose timeless principles. Update rarely and intentionally.

  - name: Taste as elitism
    description: Using taste to dismiss or exclude
    example: Rejecting input because user does not have taste
    why_bad: Taste should elevate, not exclude. Users know when things work.
    fix: Use taste to make things better for everyone.

patterns:
  - name: Taste Development Practice
    description: Study great work systematically to develop taste over time
    when: Building your ability to recognize and create quality
    example: |
      30 min daily: Analyze excellent products, understand why they're great
      Compare great and mediocre side-by-side. See the differences.
      Taste is learned through exposure and analysis, not innate.

  - name: Simplicity Discipline
    description: Remove everything possible until it breaks, then add back one element
    when: Making design and product decisions
    example: |
      Feature works perfectly with minimal UI, obvious how to use
      Not: Many options, settings, configurations
      Simple is hard. Anyone can add. Removing requires understanding essence.

  - name: Detail Obsession
    description: Sweat every small detail as signal of overall quality
    when: Reviewing work before shipping
    example: |
      Alignment, spacing, word choice, interaction timing
      Users feel quality in details even if they can't articulate it
      Details reveal care. Getting them right signals quality throughout.

  - name: Timeless Over Trendy
    description: Choose design principles that age well over current trends
    when: Making aesthetic and architectural decisions
    example: |
      Would this have looked good 5 years ago? Will it look good in 5 years?
      Trends date quickly. Timeless principles endure.
      Build for 10 years, not 10 months.

  - name: Quality as Habit
    description: Build quality in from the start, not as a later polish phase
    when: Beginning any project or feature
    example: |
      Quality first, even if slower initially. Pattern compounds.
      Not: Ship fast, polish later (later never comes)
      Quality is a practice, not a phase. Start as you mean to continue.

  - name: Good People Make Good Things
    description: Hire people who care about craft and create culture where quality matters
    when: Building team and culture
    example: |
      Team debates details, pushes for better, celebrates quality
      Not: Minimum viable, nobody cares about craft
      Quality of output reflects quality of people and culture.

frameworks:
  - name: PG Six Principles
    when_to_use: Design and product decisions
    structure:
      - "Simple: Can this be simpler? Remove everything possible."
      - "Timeless: Will this feel dated in 5 years?"
      - "Daring: Is this bold enough to be interesting?"
      - "Thorough: Are all the details right?"
      - "Good: Does this actually work well?"
      - "Delightful: Does this create joy?"

  - name: Taste Development Practice
    when_to_use: Building your own taste
    structure:
      - "Study great work: 30 min daily analyzing excellent products"
      - "Understand why: What makes this great? What would make it less great?"
      - "Compare: Put great and mediocre side by side. See differences."
      - "Apply: Use insights in your own work"
      - "Get feedback: From people with better taste than you"

  - name: Quality Check Questions
    when_to_use: Before shipping anything
    structure:
      - "Is this as simple as possible?"
      - "Will this age well?"
      - "Do all the details feel right?"
      - "Would I be proud to show this to someone I admire?"
      - "Does this reflect the quality of our team?"

  - name: Timeless Design Audit
    when_to_use: Evaluating longevity of design decisions
    structure:
      - "Would this have looked good 10 years ago?"
      - "Will this look good 10 years from now?"
      - "Is this following a trend or a principle?"
      - "What in this might date?"

handoffs:
  receives_from:
    - skill: founder-character
      receives: Care and attention to bring
    - skill: ui-design
      receives: Visual decisions to evaluate

  hands_to:
    - skill: product-strategy
      provides: Quality standards for product
    - skill: brand-positioning
      provides: Craft and quality brand elements

resources:
  essential:
    - title: Taste for Makers
      author: Paul Graham
      url: http://paulgraham.com/taste.html
      type: essay
      why: The essay on developing and applying taste
    - title: Six Principles for Making New Things
      author: Paul Graham
      url: http://paulgraham.com/newthings.html
      type: essay
      why: Practical principles for creating quality work

  recommended:
    - title: Be Good
      author: Paul Graham
      url: http://paulgraham.com/good.html
      type: essay
      why: Why goodness and quality are connected
    - title: The Design of Everyday Things
      author: Don Norman
      type: book
      why: Classic on how good design works
