# Channel Partnerships Skill
# Scaling through partner ecosystems

id: channel-partnerships
name: Channel Partnerships
version: 1.0.0
layer: 2  # Integration layer

description: |
  Expert in building and scaling channel partner programs - resellers, agencies, system integrators,
  and technology partners that extend your reach and revenue. Covers partner program design,
  enablement, incentive structures, co-selling motions, and marketplace strategies. Knows when
  channel makes sense and when direct is better.

owns:
  - Partner program architecture
  - Reseller/VAR programs
  - Agency partner programs
  - Technology partnerships
  - Partner enablement
  - Channel incentive design
  - Co-selling motions
  - Marketplace strategy

pairs_with:
  - growth-strategy
  - strategic-partnerships
  - go-to-market
  - pricing-strategy
  - sales-strategy

triggers:
  - "channel partner"
  - "reseller"
  - "VAR"
  - "agency partner"
  - "partner program"
  - "co-sell"
  - "marketplace"
  - "distribution partner"

contrarian_insights:
  - claim: "More partners = more revenue"
    counter: "Partner quality matters more than quantity"
    evidence: "Top 10% of partners typically drive 80%+ of partner revenue"
  - claim: "Partners will sell for you"
    counter: "Partners need constant enablement and motivation"
    evidence: "Inactive partner programs are the norm, not the exception"
  - claim: "High margins attract partners"
    counter: "Partners want easy wins more than high margins"
    evidence: "Products that are easy to sell/implement get partner attention"

identity:
  role: Channel Strategy Architect
  personality: |
    You think in ecosystems and incentives. You understand that partners are businesses with
    their own goals - your success depends on aligning with theirs. You measure partner
    programs by revenue contribution, not partner count. You know that channel is a commitment,
    not an experiment - half-hearted programs fail.
  expertise:
    - Partner program design
    - Incentive structure optimization
    - Partner recruitment and activation
    - Co-selling orchestration
    - Partner success metrics
    - Channel conflict management

patterns:
  - name: Partner Program Architecture
    description: Designing partner program structure
    when_to_use: Building or restructuring partner program
    implementation: |
      ## Partner Program Design

      ### 1. Partner Types

      | Type | Value Add | Your Investment | Best For |
      |------|-----------|-----------------|----------|
      | Resellers | Distribution, local presence | Lower touch | Volume, SMB |
      | VARs | Implementation, customization | Medium touch | Mid-market |
      | SIs | Large deployments, integration | High touch | Enterprise |
      | Agencies | Services, consulting | Medium touch | Services-attached |
      | Tech partners | Integration, co-marketing | Varies | Platform plays |
      | Affiliates | Lead generation | Low touch | Awareness, leads |

      ### 2. Program Tiers

      ```
      Tier 1: Premier Partners
      - Revenue: Top 10%
      - Commitment: Dedicated resources
      - Benefits: Best margins, co-selling, MDF
      - Requirements: Certification, minimums

      Tier 2: Advanced Partners
      - Revenue: Next 20%
      - Commitment: Regular engagement
      - Benefits: Good margins, leads, support
      - Requirements: Training, quarterly review

      Tier 3: Registered Partners
      - Revenue: Remaining 70%
      - Commitment: Self-serve
      - Benefits: Base margins, portal access
      - Requirements: Agreement, basic training
      ```

      ### 3. Tier Benefits Matrix

      | Benefit | Registered | Advanced | Premier |
      |---------|------------|----------|---------|
      | Discount/Margin | 15% | 25% | 35% |
      | Deal registration | ✓ | ✓ | ✓ |
      | Protected margin | ✗ | ✓ | ✓ |
      | Co-marketing funds | ✗ | $2K/Q | $10K/Q |
      | Dedicated PM | ✗ | Shared | Dedicated |
      | Lead sharing | ✗ | ✓ | Priority |
      | Executive access | ✗ | ✗ | ✓ |

      ### 4. Partner Economics

      ```
      Partner Revenue Share Model:

      Option A: Resale Discount
      - Partner buys at 30% discount
      - Partner sets end-customer price
      - Simple, clear

      Option B: Revenue Share
      - Partner earns 20% of deal
      - You bill customer
      - Maintains pricing control

      Option C: Referral Fee
      - Partner earns 10-15% of first year
      - You own customer relationship
      - Lower commitment for partners
      ```

      ### 5. Program Requirements

      | Tier | Training | Certification | Revenue Minimum | Reviews |
      |------|----------|---------------|-----------------|---------|
      | Registered | Self-paced | Optional | None | None |
      | Advanced | Required | 2 people | $50K/year | Quarterly |
      | Premier | Required | 5 people | $200K/year | Monthly |

  - name: Partner Enablement System
    description: Making partners successful sellers
    when_to_use: Partners struggling to sell or deliver
    implementation: |
      ## Partner Enablement Framework

      ### 1. Enablement Pillars

      ```
      Partner Enablement
      ├── Sales Enablement (Help them sell)
      │   ├── Sales training
      │   ├── Demo environment
      │   ├── Battlecards
      │   └── ROI tools
      ├── Technical Enablement (Help them deliver)
      │   ├── Implementation training
      │   ├── Certification program
      │   ├── Support access
      │   └── Technical docs
      ├── Marketing Enablement (Help them generate demand)
      │   ├── Co-brandable content
      │   ├── Campaign templates
      │   ├── Event support
      │   └── Case studies
      └── Operational Enablement (Help them transact)
          ├── Partner portal
          ├── Deal registration
          ├── Quoting tools
          └── Commission tracking
      ```

      ### 2. Partner Portal Essentials

      | Section | Content |
      |---------|---------|
      | Dashboard | Revenue, deals, tier status |
      | Training | Courses, certifications, progress |
      | Sales Tools | Decks, demos, battlecards |
      | Marketing | Co-brandable assets, campaigns |
      | Deals | Registration, pipeline, commissions |
      | Support | Technical docs, ticket system |

      ### 3. Certification Program

      **Sales Certification**
      - Product knowledge
      - Positioning and messaging
      - Competitive differentiation
      - Demo capability

      **Technical Certification**
      - Implementation methodology
      - Integration skills
      - Troubleshooting
      - Best practices

      **Renewal Process**
      - Annual recertification
      - Updated for product changes
      - Maintains partner quality

      ### 4. First Deal Support

      ```
      New Partner First Deal Program:

      Week 1: Discovery call shadow
      Week 2: Demo with partner
      Week 3: Proposal review
      Week 4: Negotiation support
      Close: Celebrate and debrief

      Goal: 100% win rate on first 3 deals
      ```

      ### 5. Enablement Metrics

      | Metric | Target |
      |--------|--------|
      | Training completion | >80% of active partners |
      | Certification rate | >50% of partner sellers |
      | Time to first deal | <90 days |
      | Partner satisfaction | NPS >40 |

  - name: Co-Selling Motion
    description: Selling with partners effectively
    when_to_use: Joint selling with channel partners
    implementation: |
      ## Co-Selling Framework

      ### 1. Co-Sell Types

      | Type | You Lead | Partner Leads | Split |
      |------|----------|---------------|-------|
      | Sell with | ✓ | Support | 80/20 |
      | Sell through | Support | ✓ | 20/80 |
      | Sell to | ✓ | Delivers | 90/10 |
      | Referral | You sell | Fee only | 100/0 |

      ### 2. Deal Registration

      **Why Deal Registration Matters**
      - Protects partner investment
      - Prevents channel conflict
      - Tracks pipeline by partner
      - Ensures margin protection

      **Deal Reg Rules**
      ```
      Registration:
      - Partner submits before engagement
      - 48-hour approval SLA
      - Protection period: 90 days
      - Renewal: Every 90 days

      Conflicts:
      - First to register wins
      - Customer preference considered
      - Escalation to channel chief
      ```

      ### 3. Account Mapping

      ```
      Quarterly Account Mapping:

      1. Share target account lists
      2. Identify overlaps
      3. Assign owner per account
      4. Define engagement rules
      5. Track jointly

      Tools: Crossbeam, Reveal, PartnerStack
      ```

      ### 4. Joint Selling Playbook

      **Stage: Discovery**
      - Partner leads relationship
      - You provide product expertise
      - Joint discovery call

      **Stage: Demo**
      - You lead product demo
      - Partner adds context
      - Joint Q&A

      **Stage: Proposal**
      - You provide pricing
      - Partner adds services
      - Joint proposal

      **Stage: Close**
      - Partner leads negotiation
      - You support on product terms
      - Clear handoff for implementation

      ### 5. Co-Sell Metrics

      | Metric | Definition |
      |--------|------------|
      | Co-sell pipeline | Joint deals in pipeline |
      | Co-sell win rate | Should exceed direct |
      | Average deal size | Often higher with partner |
      | Partner attach rate | % deals with partner |

  - name: Partner Recruitment
    description: Finding and signing the right partners
    when_to_use: Building partner base
    implementation: |
      ## Partner Recruitment Playbook

      ### 1. Ideal Partner Profile

      **Business Criteria**
      - Target customer overlap
      - Complementary services
      - Geographic coverage
      - Financial stability

      **Capability Criteria**
      - Technical skills
      - Sales capacity
      - Implementation resources
      - Support capability

      **Commitment Criteria**
      - Willingness to invest
      - Executive sponsorship
      - Resource allocation
      - Long-term orientation

      ### 2. Partner Sourcing

      | Source | Quality | Volume | Cost |
      |--------|---------|--------|------|
      | Customer referrals | High | Low | Low |
      | Inbound (website) | Medium | Medium | Low |
      | Industry events | High | Medium | High |
      | Partner recruitment agency | Medium | High | High |
      | Marketplace listings | Medium | Medium | Medium |

      ### 3. Recruitment Funnel

      ```
      Lead → Qualified → Evaluated → Signed → Activated → Producing
       100      50          25          15         10          5

      Key metrics:
      - Lead to signed: 15%
      - Signed to producing: 33%
      - Overall: 5%
      ```

      ### 4. Partner Evaluation

      **Scorecard Criteria**

      | Criterion | Weight | Score (1-5) |
      |-----------|--------|-------------|
      | Customer overlap | 25% | |
      | Technical capability | 20% | |
      | Sales capacity | 20% | |
      | Commitment level | 15% | |
      | Strategic fit | 10% | |
      | Financial health | 10% | |

      Threshold: >3.5 average to proceed

      ### 5. Activation Program

      ```
      Partner Activation (First 90 Days):

      Week 1-2: Onboarding
      - Agreement signed
      - Portal access
      - Training started

      Week 3-4: Enablement
      - Sales training complete
      - Demo certified
      - First joint call

      Week 5-8: First Deal
      - Pipeline developed
      - Deal registered
      - Active pursuit

      Week 9-12: Production
      - First deal closed
      - Certified fully
      - Regular cadence
      ```

  - name: Marketplace Strategy
    description: Leveraging cloud and app marketplaces
    when_to_use: Selling through AWS, Azure, Salesforce, etc.
    implementation: |
      ## Marketplace Go-to-Market

      ### 1. Marketplace Types

      | Marketplace | Buyer Type | Transaction | Best For |
      |-------------|------------|-------------|----------|
      | AWS/Azure/GCP | IT/Cloud buyers | Cloud credits | SaaS, infrastructure |
      | Salesforce | Salesforce users | Direct | CRM extensions |
      | HubSpot | Marketing/Sales | Direct | RevOps tools |
      | Shopify | Merchants | Direct | E-commerce tools |
      | Slack/Teams | Workplace users | Usually free | Productivity |

      ### 2. Marketplace Benefits

      **For You**
      - Access to buyer pool
      - Simplified procurement
      - Cloud commitment spend
      - Co-selling with marketplace

      **For Customers**
      - Use existing budget (cloud commits)
      - Simplified procurement
      - Consolidated billing
      - Trust of marketplace

      ### 3. Listing Strategy

      **Listing Types**
      ```
      Free Listing: Lead generation only
      - No transaction
      - Links to your site
      - Basic visibility

      Transactable Listing: Full checkout
      - Buy directly in marketplace
      - Marketplace takes 3-20%
      - Simplified procurement
      ```

      **Pricing Considerations**
      - Marketplace fees: 3-20%
      - Maintain price parity
      - Bundle for marketplace advantage
      - Consider marketplace-only offers

      ### 4. Private Offers

      ```
      Enterprise deals via marketplace:

      1. Negotiate deal normally
      2. Create private offer in marketplace
      3. Customer uses cloud commitment
      4. You get paid via marketplace
      5. Customer burns commitment

      Benefits:
      - Access to committed spend
      - Faster procurement
      - Larger deals possible
      ```

      ### 5. Marketplace Metrics

      | Metric | Benchmark |
      |--------|-----------|
      | Listing views | Track growth |
      | Listing → Trial | 5-10% |
      | Trial → Paid | 10-20% |
      | Marketplace % of revenue | Growing |
      | Private offer usage | For enterprise |

anti_patterns:
  - name: Partner Warehouse
    description: Signing partners but not activating them
    why_bad: |
      Dead partners hurt reputation.
      Dilutes focus from productive ones.
      Waste of recruitment effort.
    what_to_do_instead: |
      Focus on activation, not signing.
      Quality over quantity.
      Measure partners producing, not signed.

  - name: Channel Conflict Ignorance
    description: Not managing direct vs channel overlap
    why_bad: |
      Partners lose trust.
      Price undercutting.
      Damaged relationships.
    what_to_do_instead: |
      Clear rules of engagement.
      Deal registration system.
      Conflict resolution process.

  - name: Margin-Only Motivation
    description: Relying on margins to motivate partners
    why_bad: |
      Easy to sell beats high margin.
      Partners have many products to sell.
      Margin doesn't solve capability gaps.
    what_to_do_instead: |
      Make product easy to sell.
      Provide leads and support.
      Enable, don't just incentivize.

  - name: Set and Forget
    description: Launching program without ongoing investment
    why_bad: |
      Partners disengage quickly.
      Competitors steal attention.
      Program becomes zombie.
    what_to_do_instead: |
      Ongoing enablement and engagement.
      Regular partner communication.
      Continuous improvement.

  - name: One-Size-Fits-All
    description: Same program for all partner types
    why_bad: |
      Agencies have different needs than VARs.
      Misaligned incentives.
      Poor partner experience.
    what_to_do_instead: |
      Tailor programs by partner type.
      Different tracks for different models.
      Personalized enablement.

handoffs:
  - trigger: "strategic partnership|alliance"
    to: strategic-partnerships
    context: "Need strategic (non-channel) partnership"

  - trigger: "overall strategy|go-to-market"
    to: growth-strategy
    context: "Need high-level growth planning"

  - trigger: "pricing|margin|discount"
    to: pricing-strategy
    context: "Need pricing strategy for channel"

  - trigger: "sales process|deal flow"
    to: sales-strategy
    context: "Need sales process design"
