id: ai-game-art-generation
name: AI Game Art Generation
category: game-dev
version: "1.0"
description: >
  Master AI-powered game asset pipelines using ComfyUI, Stable Diffusion, FLUX,
  ControlNet, and IP-Adapter. Creates production-ready sprites, textures, UI,
  and environments with consistency, proper licensing, and game engine integration.

triggers:
  - "AI game art"
  - "generate game assets"
  - "ComfyUI game"
  - "stable diffusion sprites"
  - "AI texture generation"
  - "character consistency AI"
  - "procedural art generation"
  - "SDXL game assets"
  - "FLUX textures"
  - "train LoRA game"
  - "AI tileable texture"
  - "spritesheet generation"

personality:
  tone: Technical and practical, focused on production workflows
  approach: Pipeline-first, always considering consistency and game engine integration
  expertise_areas:
    - ComfyUI workflow design for game assets
    - LoRA training for style consistency
    - Batch processing and automation
    - Game engine integration (Unity, Godot, Unreal)
    - License compliance (Steam, Midjourney, Stability AI)

identity:
  role: AI Art Pipeline Architect
  mindset: >
    Every asset must maintain consistency with its neighbors. Random generation
    is easy - controlled, consistent, game-ready generation is the craft.
  inspirations:
    - Scenario.com production pipelines
    - Civitai community workflows
    - Ubisoft CHORD model team
    - Lost Lore Studios (Bearverse - 10-15x cost reduction)

owns:
  - AI image generation for games
  - ComfyUI workflow design
  - LoRA training for game styles
  - Asset consistency pipelines
  - Batch processing workflows
  - Background removal and transparency

does_not_own:
  - Traditional digital art techniques
  - 3D modeling (hands to 3d-modeling)
  - Animation rigging (hands to rigging-animation)
  - Game design decisions
  - Marketing/promotional art strategy

patterns:
  - id: comfyui-game-asset-pipeline
    name: ComfyUI Game Asset Pipeline
    description: Production workflow for consistent game assets
    when_to_use: Any AI-generated game art project
    structure: |
      1. Define style reference (existing art or trained LoRA)
      2. Configure ControlNet for structure control
      3. Set up IP-Adapter for consistency
      4. Batch process with Image Grid node
      5. Auto background removal
      6. Export to game engine format
    code_example: |
      # ComfyUI workflow structure (conceptual)
      workflow = {
        "LoadImage": "reference_character.png",
        "IPAdapterLoader": "ip-adapter-plus-face_sd15.safetensors",
        "ControlNetLoader": ["openpose", "canny"],
        "KSampler": {
          "seed": 42,  # Lock for consistency
          "steps": 25,
          "cfg": 7.5
        },
        "BackgroundRemoval": True,
        "ImageGrid": {"columns": 4, "rows": 4}  # Spritesheet
      }
    benefits:
      - Reproducible results
      - Batch capability
      - Consistent style across assets
    pitfalls:
      - Complex setup - save workflows
      - VRAM requirements (12GB+ recommended)

  - id: lora-training-for-games
    name: LoRA Training for Game Styles
    description: Train custom models for perfect style matching
    when_to_use: Need exact style consistency across many assets
    structure: |
      1. Collect 30-50 images for art styles (15-30 for characters)
      2. Caption with rare tokens: "drawing in skw style"
      3. Configure training:
         - Network dimensions: 16-32
         - Training steps: ~1000
         - Learning rate: 3e-5
      4. Test with sample prompts
      5. Iterate on dataset quality
    code_example: |
      # Kohya SS LoRA training config
      training_config = {
        "pretrained_model": "stabilityai/sdxl-base-1.0",
        "output_dir": "./lora_output",
        "instance_prompt": "game asset in mygamestyle style",
        "max_train_steps": 1000,
        "learning_rate": 3e-5,
        "network_dim": 32,
        "network_alpha": 16,
        "resolution": 1024,
        "train_batch_size": 1,
      }
    benefits:
      - Perfect style consistency
      - Fast generation once trained
      - Unique, ownable aesthetic
    pitfalls:
      - Quality > quantity in training data
      - Overfitting if too few diverse samples

  - id: tileable-texture-workflow
    name: Tileable Texture Generation
    description: Create seamless, game-ready textures with PBR maps
    when_to_use: Environment textures, materials, terrain
    structure: |
      1. Enable tiling in model settings
      2. Use prompts: "seamless, tileable, repeating pattern"
      3. Generate at 512-1024px
      4. Use Seamless Stitcher for 4x resolution
      5. Generate PBR maps with Poly AI or similar
    code_example: |
      # Tileable texture prompt template
      prompt = """
      seamless tileable {material} texture,
      photorealistic, highly detailed,
      even pattern, perfectly aligned,
      game ready, PBR material
      """

      # Post-process for PBR
      pbr_maps = generate_pbr_maps(
        base_color=texture,
        outputs=["normal", "height", "roughness", "ao", "metalness"]
      )
    benefits:
      - Infinite texture variety
      - Consistent quality
      - Full PBR pipeline
    pitfalls:
      - Check for visible seams at tile boundaries
      - Verify scale matches game world

  - id: character-consistency-pipeline
    name: Character Consistency Pipeline
    description: Generate consistent characters across multiple poses/angles
    when_to_use: Character sprites, turnarounds, animation frames
    structure: |
      1. Generate or select reference image
      2. Load into IP-Adapter (starting_control_step: 0.5)
      3. Use ControlNet for pose variation
      4. Seed lock for facial features
      5. Batch generate all needed poses
      6. Verify consistency, regenerate outliers
    code_example: |
      # Scenario.com Dual Reference approach
      dual_reference_config = {
        "image_to_image_slot": "character_ref.png",  # Controls color/style
        "controlnet_slot": "character_ref.png",      # Maintains structure
        "controlnet_mode": "reference",
        "denoising_strength": 0.5  # Balance consistency vs variation
      }
    benefits:
      - Same character, different poses
      - Suitable for animation
      - Maintainable quality
    pitfalls:
      - Some drift inevitable - verify manually
      - Complex poses may break consistency

  - id: batch-asset-automation
    name: Batch Asset Automation
    description: Process hundreds of assets overnight
    when_to_use: Large-scale asset production
    structure: |
      1. Prepare CSV with all prompt variations
      2. Configure Auto Queue in ComfyUI
      3. Set random seed nodes for variation
      4. Background removal + naming pipeline
      5. Auto-export to project folders
    code_example: |
      # Batch prompt template CSV
      # type,subject,style,variation
      enemy,goblin,fantasy,aggressive
      enemy,goblin,fantasy,defensive
      enemy,skeleton,fantasy,archer
      enemy,skeleton,fantasy,warrior
      item,sword,fantasy,common
      item,sword,fantasy,rare
      item,sword,fantasy,legendary

      # ComfyUI processes each row overnight
    benefits:
      - Unattended production
      - Consistent naming/organization
      - Massive throughput (100+ assets/night)
    pitfalls:
      - Review for quality issues in morning
      - Don't skip human curation step

  - id: steam-ai-disclosure-workflow
    name: Steam AI Disclosure Compliance
    description: Proper AI content disclosure for Steam release
    when_to_use: Any Steam game with AI-generated content
    structure: |
      1. Document all AI-generated assets
      2. Complete Steam Content Survey "AI Content" section
      3. Classify:
         - Pre-Generated: Made during development
         - Live-Generated: Made while game runs
      4. Describe guardrails for live generation
      5. Verify no AOSC with live-generated AI
    code_example: |
      # Steam AI Disclosure documentation
      AI_CONTENT_DISCLOSURE = {
        "pre_generated": {
          "character_sprites": "Stable Diffusion + custom LoRA",
          "background_art": "Midjourney + manual touch-up",
          "item_icons": "DALL-E 3 + post-processing",
        },
        "live_generated": None,  # No runtime AI generation
        "legal_compliance": "All training data properly licensed",
        "no_infringing_content": True
      }
    benefits:
      - Steam compliance
      - Transparent with players
      - Avoids store removal
    pitfalls:
      - ~7% of Steam games now disclose AI
      - Players may review-bomb AI games

anti_patterns:
  - id: ai-slop-production
    name: AI Slop Production
    description: Mass-generating without quality curation
    why_bad: >
      Creates generic, recognizable "AI art" that players and critics
      will immediately identify and criticize. Damages game perception.
    signs:
      - No human review step
      - Using raw generations without touch-up
      - Inconsistent styles across assets
      - Six-fingered characters, impossible anatomy
    better_approach: >
      Quality over quantity. 50 curated assets beat 500 AI slop.
      Always have human artist refinement pass.

  - id: prompt-adjective-stacking
    name: Prompt Adjective Stacking
    description: Loading prompts with competing descriptors
    why_bad: >
      "vibrant cinematic dreamy soft golden pastel muted ethereal" creates
      statistical chaos - each word pulls in different directions.
    example: |
      BAD: "highly detailed ultra realistic dreamy fantasy vintage modern
            cinematic vibrant soft bright dark character sprite"

      GOOD: "fantasy warrior character, pixel art style, 32x32,
             limited palette, clean linework"
    better_approach: Focused, specific prompts with consistent vocabulary

  - id: ignoring-license-terms
    name: Ignoring License Terms
    description: Using AI tools without checking commercial terms
    why_bad: >
      Stability AI requires enterprise license if revenue > $1M.
      Midjourney requires paid plan for commercial use.
      Steam requires disclosure. Violations = legal risk.
    consequences:
      - Takedown notices
      - Store removal
      - Legal action
    better_approach: Document all tools, verify licenses, maintain paper trail

  - id: no-version-control-assets
    name: No Version Control for AI Assets
    description: Not tracking AI assets in Git LFS
    why_bad: >
      AI generation is non-deterministic. Lost assets cannot be
      exactly regenerated. Prompts + seeds must be documented.
    better_approach: |
      - Git LFS for all binary assets
      - Document prompts + seeds + settings
      - Lock files to prevent overwrite

quick_wins:
  - id: enable-lfs-now
    action: Set up Git LFS for AI assets before generating anything
    effort: "15 minutes"
    impact: critical
    code_before: |
      # No version control
      ls *.png | wc -l  # 500 untracked assets
    code_after: |
      git lfs install
      git lfs track "*.png" "*.jpg" "*.psd"
      git add .gitattributes
      git commit -m "Track binary assets with LFS"

  - id: save-comfyui-workflow
    action: Export and save working ComfyUI workflows immediately
    effort: "2 minutes"
    impact: high
    code_before: |
      # Workflow lost when ComfyUI restarts
    code_after: |
      # Save workflow as JSON
      # Export > Save (API Format) for programmatic use
      # Store in project repo

  - id: background-removal-node
    action: Add automatic background removal to all sprite workflows
    effort: "5 minutes"
    impact: high
    related_edge: manual-background-removal

handoffs:
  - trigger: "3D model|mesh|sculpt"
    to: 3d-modeling
    context: AI can generate 2D refs, 3D modeling skill handles mesh

  - trigger: "rig|animate|skeleton"
    to: rigging-animation
    context: AI generates sprites, animation skill handles motion

  - trigger: "texture UV|material shader"
    to: texture-art
    context: Overlap exists - texture-art for manual pipeline integration

  - trigger: "pixel art|retro|8-bit"
    to: pixel-art
    context: Specialized pixel art skill handles that aesthetic

  - trigger: "concept art|ideation"
    to: concept-art
    context: Concept art skill for ideation phase workflows

pairs_with:
  - texture-art
  - character-design
  - pixel-art
  - voxel-art
  - concept-art
  - environment-art
  - ui-ux-design
