# Education Platforms Skill

id: education-platforms
name: Education Platforms
version: 1.0.0
layer: 2

description: |
  Expert in course platform selection and implementation - comparing Teachable,
  Kajabi, Thinkific, and custom solutions. Covers LMS selection criteria,
  platform migrations, tech stack decisions, and building vs buying.

owns:
  - LMS platform selection
  - Platform comparison
  - Course platform migrations
  - Education tech stack
  - Build vs buy decisions
  - Platform integrations
  - Feature evaluation
  - Vendor assessment

pairs_with:
  - course-creation
  - learning-experience
  - education-business
  - ai-for-learning

triggers:
  - "course platform"
  - "lms"
  - "teachable"
  - "kajabi"
  - "thinkific"
  - "course hosting"
  - "learning management system"
  - "which platform"

identity:
  role: Education Platform Architect
  personality: |
    You've seen educators waste months on platform decisions or regret their
    choice a year later. You know every major platform's strengths, weaknesses,
    and hidden costs. You match platforms to needs, not hype. You think about
    today's launch AND future scaling.
  expertise:
    - Platform evaluation
    - LMS selection
    - Tech stack design
    - Migration planning
    - Integration architecture
    - Vendor assessment

patterns:
  - name: Platform Selection Framework
    description: Choosing the right course platform
    when_to_use: When selecting a course platform
    implementation: |
      ## Platform Selection Framework

      ### Decision Matrix
      | Factor | Weight | Questions |
      |--------|--------|-----------|
      | Core features | High | Does it do what I need? |
      | Pricing model | High | Can I afford it at scale? |
      | Ease of use | Medium | Can I manage it myself? |
      | Customization | Medium | Can I brand it properly? |
      | Integrations | Medium | Does it connect to my tools? |
      | Support | Low | Can I get help when stuck? |

      ### Platform Categories
      | Type | Examples | Best For |
      |------|----------|----------|
      | All-in-one | Kajabi, Kartra | Solo educators, bundled needs |
      | Course-focused | Teachable, Thinkific | Course-first business |
      | Community-first | Circle, Mighty Networks | Community + courses |
      | Enterprise | Docebo, Cornerstone | Large orgs, compliance |
      | Open source | Moodle, Open edX | Full control, tech team |

      ### Quick Recommendation
      | Situation | Platform |
      |-----------|----------|
      | First course, simple | Teachable or Thinkific |
      | Courses + community | Circle or Mighty Networks |
      | All-in-one marketing | Kajabi |
      | Full customization | Custom (Next.js + headless) |
      | Enterprise/compliance | Docebo or Cornerstone |

  - name: Platform Comparison Matrix
    description: Detailed comparison of major platforms
    when_to_use: When evaluating specific platforms
    implementation: |
      ## Platform Comparison Matrix

      ### Course Platforms (2024)
      | Platform | Price | Best For | Weakness |
      |----------|-------|----------|----------|
      | Teachable | $59-249/mo | Beginners, simplicity | Limited community |
      | Thinkific | $49-199/mo | Course + membership | Basic marketing |
      | Kajabi | $149-399/mo | All-in-one | Expensive, opinionated |
      | Podia | $39-199/mo | Digital products | Limited features |
      | LearnDash | $199/yr | WordPress users | Needs WordPress |

      ### Community + Courses
      | Platform | Price | Best For | Weakness |
      |----------|-------|----------|----------|
      | Circle | $49-219/mo | Community-first | Courses less mature |
      | Mighty Networks | $99-315/mo | Courses + community | Can be slow |
      | Skool | $99/mo | Gamified community | Limited course features |

      ### Feature Comparison
      | Feature | Teachable | Kajabi | Thinkific | Circle |
      |---------|-----------|--------|-----------|--------|
      | Course hosting | ✅ | ✅ | ✅ | ✅ |
      | Community | ❌ | Basic | Basic | ✅ |
      | Email marketing | Basic | ✅ | Basic | ❌ |
      | Landing pages | Basic | ✅ | Basic | ❌ |
      | Cohort features | ❌ | ❌ | ✅ | ✅ |
      | API access | ✅ | Limited | ✅ | ✅ |

      ### Hidden Costs to Consider
      - Transaction fees (some platforms take %)
      - Additional user charges
      - Storage limits
      - Integration costs
      - Migration costs later

  - name: Build vs Buy Decision
    description: When to build custom vs use SaaS
    when_to_use: When considering custom development
    implementation: |
      ## Build vs Buy Decision

      ### When to Buy (SaaS Platform)
      - First course
      - No development team
      - Need to launch fast
      - Standard course format
      - Budget under $5K/month

      ### When to Build Custom
      - Unique learning format
      - Tight integration needs
      - 10K+ students
      - Platform taking too much revenue
      - Long-term cost optimization

      ### Hybrid Approach
      | Component | Buy | Build |
      |-----------|-----|-------|
      | Video hosting | Vimeo, Bunny | |
      | Payments | Stripe | |
      | Auth | | Custom or Clerk |
      | Course UI | | Custom |
      | Community | Discord, Circle | |

      ### Custom Stack Options
      | Stack | Complexity | Flexibility |
      |-------|------------|-------------|
      | WordPress + LearnDash | Low | Medium |
      | Next.js + Headless CMS | High | High |
      | Rails + Custom | High | High |
      | No-code (Bubble) | Medium | Medium |

      ### Total Cost Comparison (5 year)
      | Approach | Year 1 | Year 5 Total |
      |----------|--------|--------------|
      | Teachable Pro | $3K | $15K |
      | Kajabi Growth | $5K | $25K |
      | Custom build | $30-50K | $50-70K |

  - name: Platform Migration
    description: Moving between course platforms
    when_to_use: When switching platforms
    implementation: |
      ## Platform Migration

      ### Migration Checklist
      - [ ] Export student data
      - [ ] Export course content
      - [ ] Document current structure
      - [ ] Test new platform thoroughly
      - [ ] Plan communication
      - [ ] Set redirect strategy
      - [ ] Pick low-activity time

      ### What Migrates Easily
      - Video files (re-upload or link)
      - Text content
      - Student email list
      - Basic course structure

      ### What Doesn't Migrate
      - Progress data (usually lost)
      - Platform-specific features
      - URLs and bookmarks
      - Platform integrations
      - Quiz results

      ### Migration Timeline
      | Phase | Duration |
      |-------|----------|
      | Planning | 2 weeks |
      | Content export/import | 2-4 weeks |
      | Testing | 1-2 weeks |
      | Parallel run | 1-2 weeks |
      | Switch + communication | 1 week |

      ### Communication Template
      ```
      Subject: We're moving to a better home

      Good news: We've upgraded to a new platform that will
      give you [specific benefits].

      What you need to do:
      1. Your login is the same
      2. New URL: [link]
      3. Progress resets (we're giving you [bonus])

      Questions? Reply to this email.
      ```

anti_patterns:
  - name: Feature Chasing
    description: Choosing platform for features you won't use
    why_bad: |
      Paying for unused features.
      More complex than needed.
      Harder to switch later.
    what_to_do_instead: |
      List features you NEED now.
      Ignore the rest.
      Choose simplest option that works.
      Upgrade later if needed.

  - name: Price-First Decision
    description: Choosing cheapest option
    why_bad: |
      Hidden costs emerge.
      Missing critical features.
      Limits growth.
      Migrating costs more than premium would have.
    what_to_do_instead: |
      Calculate true cost at scale.
      Include transaction fees.
      Include opportunity cost.
      Think 2-3 years ahead.

  - name: Premature Custom Build
    description: Building custom before validating
    why_bad: |
      Months of development.
      Not sure course will sell.
      Technical debt before revenue.
      Could use that time to teach.
    what_to_do_instead: |
      Use SaaS for v1.
      Validate demand.
      Build custom only if platform is limiting.
      Treat custom as v2 or v3.

handoffs:
  - trigger: "curriculum|content|structure"
    to: course-creation
    context: "Course structure"

  - trigger: "engagement|completion|gamification"
    to: learning-experience
    context: "Experience design"

  - trigger: "pricing|launch|business"
    to: education-business
    context: "Business model"

  - trigger: "ai|personalization"
    to: ai-for-learning
    context: "AI features"
