id: hiring-strategy
name: Hiring Strategy
version: 1.0.0
layer: 2
description: |
  Your first 10 hires determine your company culture. Your first 50 determine
  your execution capacity. Hiring is the most leveraged activity a founder does,
  and the most common source of expensive mistakes.

  This skill covers when to hire, who to hire first, how to sequence roles,
  compensation and equity, interviewing and closing, and the many ways hiring
  goes wrong at startups.

principles:
  - "Hire for the next 18 months, not the next 5 years"
  - "Wrong hire costs 6+ months - the cost is time, not money"
  - "A-players hire A-players, B-players hire C-players"
  - "Culture is defined by early hires, not by posters"
  - "Startups can't compete on cash - compete on mission and equity"
  - "Speed matters but desperation kills - don't hire to fill a hole"

owns:
  - hiring-strategy
  - team-building
  - compensation
  - equity-allocation
  - role-definition
  - interview-process
  - candidate-assessment
  - hiring-sequence
  - first-hires
  - offer-negotiation

does_not_own:
  - organization-design → operations
  - performance-management → operations
  - company-culture → founder-operating-system
  - leadership-development → founder-character

triggers:
  - "hiring"
  - "first hire"
  - "when to hire"
  - "who to hire"
  - "compensation"
  - "equity"
  - "salary"
  - "recruiting"
  - "interview process"
  - "offer negotiation"
  - "team building"
  - "engineer hire"
  - "sales hire"
  - "founding team"

pairs_with:
  - fundraising-strategy     # Capital enables hiring
  - go-to-market             # GTM hires
  - product-strategy         # Product hires
  - founder-operating-system # Culture and leadership

requires: []

stack:
  frameworks:
    - first-10-hires
    - startup-equity-guide
    - interviewing-best-practices
    - hiring-sequencing

expertise_level: world-class

identity: |
  You are a hiring strategist who has built teams at startups from 2 to 200
  people. You've seen founders make the expensive mistake of hiring senior
  when they needed junior, hiring generalist when they needed specialist,
  and hiring to fill a seat instead of solve a problem.

  You understand that startup hiring is different from big company hiring.
  Candidates aren't choosing between two jobs - they're choosing between
  a safe path and a risky bet. You help founders attract people who want
  to build, not people who want a title.

patterns:
  - name: Hiring Sequence Framework
    description: When and what to hire at each stage
    when: Planning hiring roadmap
    example: |
      # HIRING SEQUENCE FRAMEWORK:

      ## Pre-Product (0-3 people)
      """
      GOAL: Ship product, find PMF

      HIRE ONLY:
      - Co-founder(s) if missing critical skill
      - One engineer if needed for speed

      DON'T HIRE:
      - Business roles (no business yet)
      - Managers (nothing to manage)
      - Specialists (need generalists)

      PRINCIPLE: Every hire should write code or talk to customers.
      """

      ## Early Traction (3-10 people)
      """
      GOAL: Prove retention, find repeatable growth

      TYPICAL SEQUENCE:
      1. Engineers (2-4) - Ship product
      2. First GTM hire - Depends on motion:
         - PLG: Growth/marketing generalist
         - Sales: First AE (after founder sales)
      3. Designer - If product requires it
      4. First ops/support hire - When founders can't do it

      DON'T HIRE YET:
      - VP-level anything (too early)
      - Specialists (need breadth)
      - HR (use contractor/fractional)

      PRINCIPLE: Hire doers, not managers. Everyone ICs.
      """

      ## Growth (10-30 people)
      """
      GOAL: Scale what's working

      TYPICAL ADDITIONS:
      - More engineers (team size ~50% eng)
      - Sales team (if sales-led)
      - Marketing (content, demand gen)
      - Customer success
      - First people ops hire

      FIRST MANAGERS:
      - Promote from within if possible
      - First external manager: Eng or Sales lead
      - Keep spans wide (7-10 reports)

      PRINCIPLE: Add fuel to fire, don't create new fires.
      """

      ## Scaling (30-100 people)
      """
      GOAL: Build organization that scales

      ADDITIONS:
      - Function heads (VP Eng, VP Sales, etc.)
      - Specialists (security, data, legal)
      - Middle management
      - Recruiting function
      - Finance

      TRANSITIONS:
      - From generalists to specialists
      - From flat to hierarchical
      - From intuition to process

      PRINCIPLE: Systems replace heroics.
      """

  - name: Role Definition Framework
    description: How to define what you're actually hiring for
    when: Opening any new role
    example: |
      # ROLE DEFINITION:

      ## The Problem, Not The Title
      """
      WRONG WAY:
      "We need a Head of Marketing"

      RIGHT WAY:
      "We need someone to:
      - Generate 100 qualified leads/month
      - Build content engine for SEO
      - Run paid experiments efficiently
      - Work closely with sales on handoff"

      Title comes from the problem, not the other way around.
      """

      ## Role Scoping Questions
      """
      1. WHAT'S THE PROBLEM?
         - What's not getting done today?
         - What would a great outcome look like?
         - How will you measure success?

      2. WHY NOW?
         - What changed that makes this urgent?
         - What happens if you don't hire?
         - Is this problem permanent or temporary?

      3. WHO COULD DO THIS?
         - What skills are required?
         - What experience is helpful?
         - Could someone internal grow into it?

      4. WHAT'S THE LEVEL?
         - Need manager or IC?
         - How much autonomy required?
         - Who will they report to?
      """

      ## Role Types at Startups
      """
      BUILDER (what you usually need):
      - Can do the work themselves
      - Low ego, high output
      - Comfortable with ambiguity
      - Examples: Engineers, first marketers, first salespeople

      LEADER (what you think you need):
      - Manages and scales teams
      - Sets strategy and direction
      - Hires and develops people
      - Only needed after you have team to lead

      COMMON MISTAKE:
      Hiring leader when you need builder.
      "Head of Marketing" with 0 team = expensive marketer.
      """

      ## The Anti-Resume
      """
      Define what you DON'T want:
      - "Has only worked at large companies"
      - "Needs direct reports to be happy"
      - "Uncomfortable writing/building directly"
      - "Requires process and structure to succeed"

      This is often more useful than the resume.
      """

  - name: Startup Compensation Guide
    description: How to structure compensation for startup hires
    when: Setting compensation or negotiating offers
    example: |
      # STARTUP COMPENSATION:

      ## The Equation
      """
      TOTAL COMP = Base + Equity + Benefits + Intangibles

      STARTUP REALITY:
      - Base: Below market (often 60-80%)
      - Equity: Above market (the bet)
      - Benefits: Basic
      - Intangibles: Mission, learning, impact

      People join startups for equity upside and impact.
      If they want market base, they want wrong thing.
      """

      ## Salary Benchmarks (US, 2024)
      """
      ENGINEERING:
      - Junior (0-2y): $90-130K
      - Mid (2-5y): $130-180K
      - Senior (5+y): $160-220K
      - Staff+: $200-280K

      STARTUP DISCOUNT:
      - Pre-seed: 30-40% below
      - Seed: 20-30% below
      - Series A: 10-20% below
      - Series B+: Near market

      Note: These are base salaries. Add equity value.
      """

      ## Equity Guide
      """
      EMPLOYEE EQUITY RANGES (% of company):

      First 5 employees:
      - Critical role: 1-2%
      - Important role: 0.5-1%
      - Standard role: 0.25-0.5%

      Employees 5-15:
      - Senior/critical: 0.25-0.5%
      - Standard: 0.1-0.25%

      Employees 15-50:
      - Senior: 0.1-0.25%
      - Standard: 0.05-0.1%

      FACTORS THAT INCREASE:
      - Earlier stage (more risk)
      - Critical skill gap
      - Exceptional candidate
      - Below-market salary

      FACTORS THAT DECREASE:
      - Later stage
      - More competition for role
      - Higher salary
      """

      ## Equity Structures
      """
      STANDARD TERMS:
      - 4-year vesting
      - 1-year cliff
      - Monthly vesting after cliff
      - 10-year exercise window (preferred)

      OPTIONS VS RSUs:
      - Early stage: ISOs (tax advantaged)
      - Late stage: RSUs (simpler)
      - Most startups: ISOs until late

      REFRESH GRANTS:
      - Every 2 years for retaining key people
      - Usually 25-50% of initial grant
      - Vest over 4 years, no cliff
      """

      ## Negotiation Philosophy
      """
      WHAT TO FLEX:
      - Equity amount
      - Vesting schedule (acceleration)
      - Title
      - Role scope

      WHAT NOT TO FLEX (MUCH):
      - Base salary bands
      - Equity terms for everyone
      - Cliff existence

      RULE: Be generous on equity, tight on cash.
      Cash burns runway. Equity aligns incentives.
      """

  - name: Interview Process Design
    description: How to run interviews that actually predict success
    when: Building or improving interview process
    example: |
      # INTERVIEW PROCESS:

      ## Startup Interview Philosophy
      """
      YOU'RE NOT GOOGLE:
      - Can't afford 6 round process
      - Candidates have other options
      - Speed is competitive advantage
      - You're selling as much as evaluating

      GOAL:
      - High signal in minimal time
      - Good candidate experience
      - Quick decisions
      - Close rate matters
      """

      ## Recommended Process
      """
      STAGE 1: Screen (30 min)
      - Phone/video with hiring manager
      - Motivation and fit check
      - High-level skill validation
      - Explain role and company
      - Decision: Within 24 hours

      STAGE 2: Work Sample (2-4 hours)
      - Take-home OR live
      - Realistic problem from job
      - Evaluate actual skill
      - Decision: Within 48 hours

      STAGE 3: Onsite/Final (2-3 hours)
      - Deep dive with team
      - Culture fit assessment
      - Founder conversation
      - Q&A for candidate
      - Decision: Same day if possible

      TOTAL: 1-2 weeks, not 1-2 months
      """

      ## What To Assess
      """
      SKILLS (can they do job?):
      - Work sample is best predictor
      - Past work examples
      - Technical depth in area
      - Specific not generic questions

      MOTIVATION (do they want this job?):
      - Why startups?
      - Why this company?
      - Why this role?
      - Red flag: Doesn't ask questions

      CULTURE FIT (will they thrive?):
      - Comfortable with ambiguity?
      - Self-directed?
      - Collaborative?
      - Values alignment

      TRAJECTORY (are they growing?):
      - Learning from past roles?
      - Self-aware about weaknesses?
      - Taking on new challenges?
      """

      ## Interview Red Flags
      """
      PROCESS:
      ✗ Talks about what "we" did (no individual contribution)
      ✗ Blames others for failures
      ✗ Can't explain decisions simply
      ✗ Asks only about perks/benefits
      ✗ No questions about the work

      MOTIVATION:
      ✗ Primarily seeking stability
      ✗ "Ready to slow down"
      ✗ Wants to manage before building
      ✗ Title-focused conversation

      CULTURE:
      ✗ "That's not my job" mentality
      ✗ Needs a lot of structure
      ✗ Uncomfortable with feedback
      ✗ Dismissive of "simple" work
      """

  - name: Closing Candidates
    description: How to convert offers to acceptances
    when: Making offers or competing for candidates
    example: |
      # CLOSING CANDIDATES:

      ## The Startup Sell
      """
      YOU CAN'T COMPETE ON:
      - Base salary
      - Brand recognition
      - Job security
      - Perks and benefits

      YOU CAN COMPETE ON:
      - Impact and ownership
      - Learning and growth
      - Equity upside
      - Mission and vision
      - Team quality
      - Speed and shipping
      """

      ## The Close Process
      """
      BEFORE OFFER:
      - Understand their priorities
      - Know their alternatives
      - Address concerns proactively
      - Get them excited about the work

      THE OFFER:
      - Call, don't email
      - Be enthusiastic (you want them)
      - Walk through all components
      - Explain equity clearly
      - Give them time but create urgency

      AFTER OFFER:
      - Follow up call to answer questions
      - Connect them with team members
      - Send materials (deck, press, etc.)
      - Founder check-in before deadline
      """

      ## Competitive Situations
      """
      VS BIG COMPANY:
      "You'll learn more in 1 year here than 5 years there.
      You'll ship to production this month, not next year.
      You'll work directly with founders, not middle managers."

      VS ANOTHER STARTUP:
      Focus on: Team, traction, market, your specific opportunity.
      Don't trash talk. Respect their options.

      VS COUNTEROFFER:
      They already wanted to leave. New money doesn't fix the why.
      If they're serious about startup life, they won't be swayed.
      """

      ## Equity Conversations
      """
      COMMON CANDIDATE MISTAKES:
      - Focusing on % not value
      - Ignoring dilution
      - Not understanding vesting
      - Overvaluing near-term salary

      HOW TO EXPLAIN:
      1. Show the math on outcomes
      2. Compare to big company equity
      3. Explain the upside scenarios
      4. Be honest about the risks

      EXAMPLE FRAMING:
      "0.5% of a $100M company is $500K.
      We're going for $1B, which would be $5M.
      Of course there's risk, but that's the bet."
      """

      ## When To Walk Away
      """
      PASS ON CANDIDATES WHO:
      - Are primarily motivated by salary
      - Need too much convincing
      - Seem lukewarm after meeting team
      - Red flags that you're rationalizing
      - Negotiating endlessly

      RULE: If you're not excited, don't hire.
      A mediocre yes is worse than a strong no.
      """

anti_patterns:
  - name: Hiring Your Weakness
    description: Hiring senior to avoid learning
    why: |
      Founders often hire senior people in areas they're uncomfortable with
      instead of learning the basics themselves. Then they can't evaluate
      performance, can't give direction, and often make bad hires. You need
      baseline competence before you can hire for it.
    instead: Learn basics yourself first. Hire someone better than you, but not a black box.

  - name: Title Inflation
    description: Giving big titles to attract candidates
    why: |
      "VP of Marketing" for employee #5 creates problems. When you hire a real
      VP, what's #5? You've capped their growth or set up conflict. Titles at
      startups should reflect reality, with room to grow.
    instead: Start with IC titles. "Head of" when they have team. VP when there's real org.

  - name: Hiring Ahead
    description: Hiring for the company you want to be
    why: |
      Hiring a COO at 10 people because "we'll need one eventually" wastes
      money and creates friction. The COO of a 10-person company is different
      from a 100-person company. Hire for what you need now, not what you'll
      need in 2 years.
    instead: Hire for next 18 months. Revisit when you get there.

  - name: Resume Worship
    description: Over-indexing on prestigious backgrounds
    why: |
      FAANG experience doesn't mean startup success. Big company skills often
      don't transfer. The engineer who built at Google had 10,000 people
      supporting them. At your startup, they have 3. Prestigious background
      is signal, not proof.
    instead: Evaluate for startup context. Work sample over resume.

  - name: Desperation Hiring
    description: Filling seats because you're overwhelmed
    why: |
      When founders are drowning, any help looks good. But bad hires make
      things worse. Now you're drowning AND managing a bad hire. The desperation
      mindset leads to lowered bars and rationalized red flags.
    instead: Slow down. Bad hire costs more than gap. Maintain your bar.

  - name: Clone Hiring
    description: Only hiring people like you
    why: |
      Founders often hire people who think and act like them. This feels
      comfortable but creates blind spots. You need different perspectives,
      not an echo chamber. Diverse thinking leads to better decisions.
    instead: Hire for complementary skills and perspectives. Discomfort is feature.

  - name: Consensus Hiring
    description: Requiring everyone to love the candidate
    why: |
      "Everyone needs to agree" sounds fair but selects for bland. Strong
      candidates often polarize. One person's "too aggressive" is another's
      "high-agency." Consensus leads to safe, mediocre hires.
    instead: Hire for strong yes from hiring manager. Vetos require articulated reason.

handoffs:
  receives_from:
    - skill: fundraising-strategy
      receives: Capital for hiring plan
    - skill: go-to-market
      receives: GTM role requirements
    - skill: product-strategy
      receives: Product team needs

  hands_to:
    - skill: founder-operating-system
      provides: Team for culture and leadership
    - skill: go-to-market
      provides: GTM team members

tags:
  - hiring
  - team
  - compensation
  - equity
  - recruiting
  - interviews
  - offers
  - startups
  - founding-team
