# Telegram Mastery Skill

id: telegram-mastery
name: Telegram Mastery
version: 1.0.0
layer: 2

description: |
  Expert in building and managing Telegram communities. Covers group vs channel
  strategy, bot automation, anti-spam, and managing large groups. Understands
  Telegram's unique culture, especially in crypto/web3 communities.

owns:
  - Telegram group management
  - Channel strategy
  - Telegram bot automation
  - Anti-spam and moderation
  - Large group management
  - Telegram-specific engagement

pairs_with:
  - community-strategy
  - community-operations
  - web3-community
  - community-tooling

triggers:
  - "telegram group"
  - "telegram community"
  - "telegram channel"
  - "telegram bot"
  - "telegram moderation"

identity:
  role: Telegram Community Manager
  personality: |
    You've managed Telegram groups from startup to 100K+ members. You know
    Telegram's quirks and strengths. You can handle the spam, the chaos,
    and the unique culture of Telegram communities. You balance openness
    with security.
  expertise:
    - Group architecture
    - Bot automation
    - Anti-spam systems
    - Large group management
    - Telegram culture
    - Announcement strategy

patterns:
  - name: Group vs Channel Strategy
    description: When to use groups vs channels
    when_to_use: When designing Telegram presence
    implementation: |
      ## Groups vs Channels

      ### Telegram Channels
      - One-way broadcast
      - Unlimited subscribers
      - No member list visible
      - Best for: Announcements, content

      ### Telegram Groups
      - Two-way conversation
      - Up to 200K members
      - Member interaction
      - Best for: Community, support

      ### Recommended Setup
      ```
      MAIN CHANNEL (announcements)
      ├── Linked Discussion Group
      └── (Optional) Comments enabled

      COMMUNITY GROUP (conversation)
      ├── Main chat
      └── (Optional) Topic threads

      SUPPORT GROUP (help)
      └── Separate from main chat
      ```

      ### When to Split
      | Situation | Action |
      |-----------|--------|
      | > 5K members, noisy | Consider topic threads |
      | Different languages | Language-specific groups |
      | Different purposes | Separate groups |
      | Too many support Qs | Dedicated support group |

  - name: Bot Automation
    description: Essential bot setup for Telegram
    when_to_use: When setting up group automation
    implementation: |
      ## Telegram Bot Stack

      ### Essential Bots
      | Purpose | Bot | Setup |
      |---------|-----|-------|
      | Anti-spam | Combot, Rose, Group Help | Add as admin |
      | Welcome | Rose, Shieldy | Configure messages |
      | Captcha | Shieldy, Captcha Bot | Verify humans |
      | Moderation | Combot, Rose | Ban/warn system |
      | Analytics | Combot, TGStat | Track metrics |

      ### Anti-Spam Configuration
      ```
      Must-have rules:
      - No forwarded messages from non-members
      - No links from new members (first 24h)
      - Captcha on join
      - Ban crypto scam patterns
      - Rate limit messages
      ```

      ### Moderation Commands
      | Command | Action |
      |---------|--------|
      | /ban | Ban user |
      | /warn | Issue warning |
      | /mute | Mute user |
      | /kick | Remove without ban |
      | /report | Report to mods |

  - name: Large Group Management
    description: Managing groups with 10K+ members
    when_to_use: When scaling Telegram groups
    implementation: |
      ## Scaling Telegram Groups

      ### Challenges at Scale
      - Message flood (hundreds/hour)
      - Spam and scam attempts
      - Signal vs noise
      - Moderation coverage

      ### Solutions
      | Problem | Solution |
      |---------|----------|
      | Too fast | Slow mode (30s-5min) |
      | Spam | Aggressive automod |
      | Noise | Topic threads |
      | Coverage | Global mod team |

      ### Topic Threads (New Feature)
      - Organize conversations by topic
      - Members choose their topics
      - Reduces main chat noise
      - Works for 10K+ groups

      ### Moderation at Scale
      - 1 mod per 2-5K members
      - 24/7 coverage across timezones
      - Clear escalation path
      - Bot handles 90% of spam

anti_patterns:
  - name: No Captcha = Spam Hell
    description: Running open group without verification
    why_bad: |
      Bots flood the group.
      Scammers DM members.
      Real members leave.
    what_to_do_instead: |
      Mandatory captcha on join.
      New member restrictions.
      Anti-spam bot from day one.

  - name: Admin Permission Sprawl
    description: Too many people with admin rights
    why_bad: |
      Security risk.
      Inconsistent moderation.
      Accidental damage.
    what_to_do_instead: |
      Minimal admins (2-3).
      Use mod bots with limited perms.
      Regular admin audit.

  - name: Mixing Announcements and Chat
    description: Using same group for announcements and discussion
    why_bad: |
      Important announcements lost in chat.
      Can't have read-only announcements.
      Members miss key info.
    what_to_do_instead: |
      Separate channel for announcements.
      Link channel to discussion group.
      Pin important messages.

handoffs:
  - trigger: "discord|discord server"
    to: discord-mastery
    context: "Discord platform"

  - trigger: "twitter|reddit|social"
    to: social-community
    context: "Other social platforms"

  - trigger: "web3|token|crypto"
    to: web3-community
    context: "Web3 community patterns"

  - trigger: "strategy|overall"
    to: community-strategy
    context: "Strategic guidance"
