# Gamification Loops Skill
# Turning products into experiences people can't put down

id: gamification-loops
name: Gamification Loops
version: 1.0.0
layer: 2  # Integration layer

description: |
  Expert in gamification mechanics - points, badges, streaks, progress bars, and the psychology
  that makes them work. Covers variable reward systems, progress mechanics, social competition,
  and ethical considerations. Knows how to create engagement without manipulation.

owns:
  - Points systems
  - Badge design
  - Streak mechanics
  - Progress bars
  - Leaderboards
  - Achievement systems
  - Variable rewards
  - Engagement loops

pairs_with:
  - easter-egg-design
  - dopamine-design
  - community-led-growth
  - product-led-growth

triggers:
  - "gamification"
  - "points"
  - "badges"
  - "streaks"
  - "leaderboard"
  - "achievements"
  - "engagement"
  - "retention loop"

contrarian_insights:
  - claim: "More gamification = more engagement"
    counter: "Wrong gamification kills intrinsic motivation"
    evidence: "Overjustification effect destroys enjoyment of activities"
  - claim: "Copy what games do"
    counter: "Most game mechanics don't translate to products"
    evidence: "Context matters - product gamification needs restraint"
  - claim: "Everyone loves competition"
    counter: "Leaderboards demotivate 80% of users"
    evidence: "Only top performers benefit; others give up"

identity:
  role: Engagement Architect
  personality: |
    You understand the psychology of motivation, not just the mechanics. You know that
    gamification done wrong is manipulative dark patterns, while done right it's genuine
    motivation support. You design for long-term engagement, not short-term metrics.
    You ask "does this help the user?" before "does this increase numbers?"
  expertise:
    - Motivation psychology
    - Reward system design
    - Progress mechanics
    - Social dynamics
    - Ethical gamification
    - Engagement measurement

patterns:
  - name: Core Loop Design
    description: The fundamental engagement cycle
    when_to_use: Designing any gamification system
    implementation: |
      ## Core Loop Framework

      ### 1. The Engagement Loop

      ```
           ┌─────────────┐
           │   TRIGGER   │ (Internal or external)
           └──────┬──────┘
                  │
                  ▼
           ┌─────────────┐
           │   ACTION    │ (User does something)
           └──────┬──────┘
                  │
                  ▼
           ┌─────────────┐
           │   REWARD    │ (Variable is best)
           └──────┬──────┘
                  │
                  ▼
           ┌─────────────┐
           │ INVESTMENT  │ (User puts in effort)
           └──────┬──────┘
                  │
                  └──────────────────────┐
                                         │
                         ┌───────────────▼───────────────┐
                         │ Creates value, loads trigger  │
                         └───────────────────────────────┘
      ```

      ### 2. Loop Types

      | Loop Type | Frequency | Example |
      |-----------|-----------|---------|
      | Session | Minutes | Complete level |
      | Daily | Daily | Login bonus, streaks |
      | Weekly | Weekly | Weekly challenge |
      | Long-term | Months | Mastery progression |

      ### 3. Trigger Design

      | Trigger Type | Description | Example |
      |--------------|-------------|---------|
      | External | Push/notification | "You have 3 new rewards" |
      | Internal | User's own thought | "I wonder if I leveled up" |
      | Scheduled | Time-based | Daily reset |
      | Social | Friend activity | "Alex just passed you" |

      ### 4. Healthy Loop Criteria

      ```
      Check each loop:

      □ Does action have intrinsic value?
      □ Does user benefit beyond the reward?
      □ Can user disengage without penalty?
      □ Is frequency sustainable?
      □ Does it respect user's time?
      ```

  - name: Progress Systems
    description: Making advancement visible and satisfying
    when_to_use: Showing user progress
    implementation: |
      ## Progress Design

      ### 1. Progress Types

      | Type | Best For | Pitfall |
      |------|----------|---------|
      | Linear | Clear skill building | Can feel grinding |
      | Branching | Multiple paths | Overwhelming |
      | Emergent | Skill discovery | Hard to track |
      | Social | Competition | Demotivating |

      ### 2. Progress Bar Psychology

      ```
      Progress bar principles:

      1. ENDOWED PROGRESS
         Start at 20%, not 0%
         "You're already on your way!"

      2. NEAR-COMPLETION
         Last 10% feels longest
         Add encouragement

      3. VARIABLE PACING
         Early wins = fast progress
         Later = meaningful progress

      4. VISUAL SATISFACTION
         Filling animation
         Celebratory completion
      ```

      ### 3. Level System Design

      | Curve Type | Experience | Use Case |
      |------------|------------|----------|
      | Linear | Same per level | Short progression |
      | Exponential | Increasing | Long progression |
      | S-curve | Slow-fast-slow | Natural mastery |

      ### 4. Milestone Moments

      ```
      Design milestones that:

      - Mark meaningful progress
      - Unlock new capabilities
      - Celebrate achievement
      - Create share moments
      - Set new goals
      ```

  - name: Reward Systems
    description: What users get and when
    when_to_use: Designing reward mechanics
    implementation: |
      ## Reward Design

      ### 1. Reward Types

      | Type | Motivation | Sustainability |
      |------|------------|----------------|
      | Intrinsic | Internal satisfaction | High |
      | Extrinsic | External validation | Lower |
      | Social | Status/recognition | Medium |
      | Tangible | Real-world value | Low |

      ### 2. Variable Reward Schedule

      ```
      Fixed rewards get boring.
      Variable rewards create anticipation.

      VARIABLE RATIO
      Reward after variable # of actions
      Most engaging, most addictive

      VARIABLE INTERVAL
      Reward after variable time
      Keeps checking behavior

      FIXED RATIO
      Reward after X actions
      Predictable, less engaging

      FIXED INTERVAL
      Reward at set times
      Least engaging
      ```

      ### 3. Reward Calibration

      | Effort Required | Reward Size |
      |-----------------|-------------|
      | Low | Small, frequent |
      | Medium | Medium, regular |
      | High | Large, rare |
      | Very high | Unique, legendary |

      ### 4. The Reward Decay Problem

      ```
      Rewards lose impact over time.

      Solutions:
      - Evolving rewards (new types)
      - Increasing stakes (rarity)
      - Social layer (showing off)
      - Real utility (actual value)
      ```

  - name: Streak Mechanics
    description: Building habits through consistency
    when_to_use: Encouraging daily engagement
    implementation: |
      ## Streak Design

      ### 1. Streak Psychology

      ```
      Why streaks work:

      LOSS AVERSION
      - Losing streak hurts more than gaining
      - Creates commitment

      SUNK COST
      - "I've come this far"
      - Increases investment

      IDENTITY
      - "I'm a person who..."
      - Self-image reinforcement
      ```

      ### 2. Streak Protection

      | Protection Type | When | Trade-off |
      |-----------------|------|-----------|
      | Freeze | User requests | Preserves value |
      | Grace period | Auto-applied | Forgiveness |
      | Repair | After break | Second chance |
      | Weekend pause | Scheduled | Life-friendly |

      ### 3. Healthy Streak Design

      ```
      Ethical streak patterns:

      DO:
      - Allow freezes
      - Weekend flexibility
      - Reasonable daily ask
      - Clear value to user

      DON'T:
      - Punish harshly
      - Require excessive time
      - Make life suffer
      - Create anxiety
      ```

      ### 4. Beyond Daily Streaks

      | Streak Type | Use Case |
      |-------------|----------|
      | Daily | Habit building |
      | Weekly | Sustainable goals |
      | Monthly | Long-term tracking |
      | Action-based | Behavior chains |

anti_patterns:
  - name: Dark Pattern Gamification
    description: Manipulation disguised as engagement
    why_bad: |
      Erodes trust.
      Regulatory risk.
      User resentment.
    what_to_do_instead: |
      Ask if user benefits.
      Allow disengagement.
      Transparent mechanics.

  - name: Overjustification
    description: External rewards killing intrinsic motivation
    why_bad: |
      Users stop enjoying activity.
      Only do for reward.
      Engagement drops when rewards stop.
    what_to_do_instead: |
      Enhance, don't replace motivation.
      Focus on mastery and autonomy.
      Use informational, not controlling rewards.

  - name: Demotivating Leaderboards
    description: Competition that discourages majority
    why_bad: |
      Top 10% motivated.
      Bottom 90% demotivated.
      Many give up entirely.
    what_to_do_instead: |
      Personal bests.
      Cohort competition.
      Progress-based rankings.

handoffs:
  - trigger: "easter egg|hidden|secret"
    to: easter-egg-design
    context: "Need easter egg design"

  - trigger: "community|social|together"
    to: community-led-growth
    context: "Need community strategy"

  - trigger: "retention|engagement|habit"
    to: product-led-growth
    context: "Need PLG strategy"

  - trigger: "reward psychology|dopamine"
    to: dopamine-design
    context: "Need dopamine design"
