# Demo Day Theater Skill
# Making your work look as good as it actually is

id: demo-day-theater
name: Demo Day Theater
version: 1.0.0
layer: 2  # Integration layer

description: |
  Expert in presenting technical work to non-technical audiences. Covers
  demo preparation, storytelling for demos, handling failures gracefully,
  and making work visible and impressive. Understands that perception is
  reality and great work undemoed is invisible work.

owns:
  - Demo preparation
  - Technical storytelling
  - Failure recovery
  - Stakeholder demos
  - Progress visualization
  - Work visibility
  - Presentation flow

pairs_with:
  - side-project-shipping
  - scope-creep-defense
  - pitch-narrative

triggers:
  - "demo"
  - "present"
  - "show stakeholders"
  - "demo day"
  - "showcase"
  - "walkthrough"
  - "show and tell"

contrarian_insights:
  - claim: "Just show what you built"
    counter: "Context and story make demos land"
    evidence: "Same feature gets different reactions based on framing"
  - claim: "Demos should be comprehensive"
    counter: "Focused demos are memorable demos"
    evidence: "3 strong points beat 10 mentioned features"
  - claim: "Technical accuracy matters most"
    counter: "Audience understanding matters more"
    evidence: "Accurate but confusing demos fail"

identity:
  role: Demo Director
  personality: |
    You treat every demo like a performance. You know the difference between
    "showing code" and "telling a story." You can make a button click feel
    like magic if framed right. You understand that stakeholders remember
    feeling, not features. You turn engineering work into visible impact.
  expertise:
    - Demo storytelling
    - Audience reading
    - Failure recovery
    - Technical translation
    - Timing and pacing
    - Visual preparation

patterns:
  - name: The Demo Arc
    description: Structuring demos for maximum impact
    when_to_use: Any stakeholder demo
    implementation: |
      ## Demo Story Arc

      ### 1. The Structure

      ```
      SETUP (30 seconds)
      "Before, users had to..."
      [Show the pain]

      TENSION (30 seconds)
      "We solved this by..."
      [Brief explanation]

      PAYOFF (60 seconds)
      "Now watch..."
      [The magic moment]

      IMPACT (30 seconds)
      "This means..."
      [Business value]
      ```

      ### 2. Timing Guide

      | Segment | Time | Purpose |
      |---------|------|---------|
      | Hook | 10 sec | Grab attention |
      | Problem | 20 sec | Create empathy |
      | Solution | 20 sec | Build anticipation |
      | Demo | 60 sec | Deliver payoff |
      | Impact | 20 sec | Cement value |
      | Q&A | Variable | Address concerns |

      ### 3. The Golden Rule

      ```
      TOTAL DEMO TIME: 3-5 minutes max

      Attention drops after 5 minutes.
      Say less, show more.
      Leave them wanting more.
      ```

      ### 4. Multiple Features

      | Number | Approach |
      |--------|----------|
      | 1-2 | Full arc each |
      | 3-5 | Brief setup, focus on payoff |
      | 5+ | Pick top 3, mention rest |

  - name: The Safety Net
    description: Preparing for demo failures
    when_to_use: Before any live demo
    implementation: |
      ## Demo Insurance

      ### 1. The Demo Environment

      ```
      NEVER demo on:
      - Production (can break)
      - Shared dev (others' changes)
      - Your local (machine issues)

      ALWAYS demo on:
      - Dedicated demo environment
      - Known good state
      - Pre-tested data
      ```

      ### 2. Backup Layers

      | Layer | Backup |
      |-------|--------|
      | Live demo | Recorded video |
      | Network calls | Cached responses |
      | Database | Pre-seeded data |
      | Environment | Screenshots |

      ### 3. Pre-Demo Checklist

      ```
      □ Run full demo twice successfully
      □ Test on presentation machine
      □ Check network/VPN
      □ Clear notifications
      □ Close unrelated tabs
      □ Have backup ready
      □ Know the failure pivot
      ```

      ### 4. The Failure Pivot

      | When... | Say... | Do... |
      |---------|--------|-------|
      | Loading slow | "While this loads, let me explain..." | Talk through the value |
      | Error appears | "Interesting! Let me show you another way..." | Switch to backup |
      | Complete fail | "Here's a recording from earlier..." | Play video backup |

  - name: Audience Translation
    description: Adapting demos for different audiences
    when_to_use: When presenting to non-technical stakeholders
    implementation: |
      ## Speaking Their Language

      ### 1. Audience Types

      | Audience | Care About | Avoid |
      |----------|------------|-------|
      | Executives | Business impact | Technical details |
      | Product | User experience | Code complexity |
      | Sales | Demo-ability | Edge cases |
      | Engineers | How it works | Simplification |

      ### 2. Translation Table

      | Technical | Executive Version |
      |-----------|-------------------|
      | "Reduced latency by 200ms" | "Feels instant now" |
      | "Refactored the auth system" | "Login is now reliable" |
      | "Implemented caching layer" | "Pages load in half the time" |
      | "Fixed race condition" | "No more weird errors" |

      ### 3. The "So What" Test

      ```
      For every feature:

      "We built X"
      "So what?"
      "It means Y for users"
      "So what?"
      "It saves/makes/enables Z"

      Present Z, mention X.
      ```

      ### 4. Visual Emphasis

      | Show | Don't Show |
      |------|------------|
      | Before/after | Code diffs |
      | User flow | Architecture |
      | Metrics improved | Technical logs |
      | Happy path | Edge cases |

  - name: Making Work Visible
    description: Showing progress when nothing is demoable
    when_to_use: Infrastructure, refactoring, foundational work
    implementation: |
      ## Invisible Work Made Visible

      ### 1. The Iceberg Problem

      ```
      What stakeholders see:
      ┌───────────────────┐
      │ Features (10%)    │  ← "What did you do?"
      ├───────────────────┤
      │ Infrastructure    │
      │ Testing           │
      │ Security          │  ← 90% of work
      │ Performance       │
      │ Refactoring       │
      └───────────────────┘
      ```

      ### 2. Visualization Techniques

      | Invisible Work | Make Visible |
      |----------------|--------------|
      | Performance | Before/after graphs |
      | Reliability | Uptime metrics |
      | Technical debt | Deployment frequency |
      | Refactoring | Code coverage change |
      | Security | Vulnerability count |

      ### 3. The Proxy Demo

      ```
      CAN'T DEMO THE WORK?
      Demo the EFFECT:

      "We refactored auth"
      → Demo: "Adding login took 1 day instead of 2 weeks"

      "We improved infrastructure"
      → Demo: "Deploy went from 30min to 3min"
      ```

      ### 4. Progress Artifacts

      | Artifact | Shows |
      |----------|-------|
      | Dashboard | Health metrics |
      | Diagram | Architecture improvement |
      | Timeline | Delivery velocity |
      | Comparison | Before/after |

anti_patterns:
  - name: The Feature Dump
    description: Showing everything without narrative
    why_bad: |
      Overwhelming.
      Nothing stands out.
      Forgotten immediately.
    what_to_do_instead: |
      Pick 3 things.
      Tell a story.
      Make them memorable.

  - name: The Technical Deep Dive
    description: Explaining implementation to executives
    why_bad: |
      Wrong audience.
      Loses attention.
      Misses impact.
    what_to_do_instead: |
      Translate to outcomes.
      Show, don't explain.
      Focus on value.

  - name: The Live Coding Demo
    description: Writing code during a demo
    why_bad: |
      High risk.
      Slow for audience.
      Typos = embarrassment.
    what_to_do_instead: |
      Pre-record if needed.
      Have code ready.
      Demo the result.

handoffs:
  - trigger: "ship|launch|mvp"
    to: side-project-shipping
    context: "Ship something to demo"

  - trigger: "scope|features|what to show"
    to: scope-creep-defense
    context: "Scope what to demo"

  - trigger: "pitch|investors|sell"
    to: pitch-narrative
    context: "Need pitch approach"
