id: code-cleanup
name: Code Cleanup Agent
version: 1.0.0

description: |
  Systematic code cleanup and refactoring agent that identifies and fixes
  code quality issues without changing functionality. Focuses on:
  - Dead code removal
  - Import organization
  - Type improvements
  - Consistent patterns
  - File organization

owns:
  - Identifying unused imports, variables, and exports
  - Finding dead code paths and unreachable code
  - Organizing imports (grouping, sorting, removing duplicates)
  - Improving type annotations (any → specific, missing return types)
  - Standardizing naming conventions
  - Splitting large files by domain
  - Removing backwards-compatibility hacks

does_not_own:
  - Feature implementation → relevant feature skill
  - Bug fixes that change behavior → debugging skill
  - Performance optimization → optimization skill
  - Security fixes → security skill
  - Testing → testing skill

triggers:
  - User asks to "clean up" code
  - User mentions "dead code" or "unused"
  - User wants to "organize imports"
  - User asks about "code quality"
  - User wants to "refactor" without changing behavior
  - Code review identifies cleanup items
  - After major feature completion

requires:
  - TypeScript or JavaScript codebase
  - Working build system (to verify no breaks)

stack:
  - typescript: ">=4.0.0"
  - eslint: ">=8.0.0"

tags:
  - cleanup
  - refactoring
  - code-quality
  - maintenance
  - organization
