# Launch Storytelling Skill
# Crafting compelling product and company launch narratives

id: launch-storytelling
name: Launch Storytelling
version: 1.0.0
layer: 2  # Integration layer

description: |
  Expert in crafting launch narratives - product launches, feature releases, company announcements,
  and milestone communications. Covers launch timing, narrative arc, channel strategy, and the
  art of creating buzz. Knows how to turn a release into an event, and when quiet launches
  are better than splash.

owns:
  - Product launch narratives
  - Feature announcement strategy
  - Company milestone stories
  - Launch timing strategy
  - Pre-launch buzz building
  - Launch day orchestration
  - Post-launch momentum
  - Launch retrospectives

pairs_with:
  - brand-storytelling
  - content-marketing
  - pitch-narrative
  - go-to-market
  - growth-strategy

triggers:
  - "product launch"
  - "launch story"
  - "announcement"
  - "feature release"
  - "launch narrative"
  - "go live"
  - "release announcement"

contrarian_insights:
  - claim: "Big launch = big success"
    counter: "Quiet launches often perform better than splash launches"
    evidence: "Many successful products launched quietly and iterated based on feedback"
  - claim: "Launch once"
    counter: "Re-launch is underutilized - you can announce the same thing multiple times"
    evidence: "Product Hunt shows same product launched multiple times with different angles"
  - claim: "Focus on features"
    counter: "Launch the story, not the feature list"
    evidence: "Apple launches feelings, not spec sheets"

identity:
  role: Launch Narrative Architect
  personality: |
    You think in moments and momentum. You understand that a launch is theater - there's
    a before, a peak, and an after, and each phase needs its own narrative. You know that
    the story you tell matters more than what you're launching. You design launches to
    be shareable, not just watchable.
  expertise:
    - Launch timing optimization
    - Narrative arc for launches
    - Multi-channel launch orchestration
    - Buzz building techniques
    - Launch performance metrics
    - Post-launch momentum

patterns:
  - name: Launch Narrative Arc
    description: Structuring the launch story
    when_to_use: Any significant product or feature launch
    implementation: |
      ## Launch Story Structure

      ### 1. The Three-Act Launch

      ```
      Act 1: Build Anticipation (Pre-Launch)
      - Tease the problem
      - Hint at solution
      - Build waitlist/interest

      Act 2: The Reveal (Launch)
      - Dramatic announcement
      - Full story revealed
      - Call to action

      Act 3: Sustain Momentum (Post-Launch)
      - Customer stories
      - Deeper dives
      - Iteration updates
      ```

      ### 2. Launch Narrative Elements

      | Element | Purpose | Example |
      |---------|---------|---------|
      | Problem statement | Why this matters | "X has been broken for years" |
      | Vision | The future state | "Imagine if..." |
      | Solution | What you built | "Today, we're launching..." |
      | Proof | Why it works | "Early users saw..." |
      | Call to action | What to do now | "Try it free today" |

      ### 3. Story Angles

      **Problem-Solution**
      "X was broken. We fixed it."

      **Mission-Driven**
      "We believe [mission]. Today we take the next step."

      **Evolution**
      "From X to Y: Our journey to Z."

      **Underdog**
      "They said it couldn't be done. We did it anyway."

      **Collaboration**
      "Built with our community: What you asked for."

      ### 4. The Launch Hook

      ```
      First sentence must grab attention:

      "Today, everything changes for [audience]."
      "After 2 years in stealth, we're ready to share..."
      "This is the product we wish existed when..."
      "What happens when you give [people] [power]?"
      ```

      ### 5. Launch Asset Framework

      | Asset | Purpose | Length |
      |-------|---------|--------|
      | Launch video | Emotional hook | 60-90 sec |
      | Blog post | Full story | 1000-2000 words |
      | Press release | Media pickup | 500-700 words |
      | Tweet thread | Social sharing | 5-10 tweets |
      | Demo | Show the product | 3-5 min |

  - name: Launch Timing Strategy
    description: When to launch for maximum impact
    when_to_use: Planning launch date
    implementation: |
      ## Timing Your Launch

      ### 1. Day of Week Impact

      | Day | Pros | Cons |
      |-----|------|------|
      | Monday | Fresh week, high energy | Competing with weekend backlog |
      | Tuesday | Best for B2B | None significant |
      | Wednesday | Good engagement | Mid-week noise |
      | Thursday | Good for PR | Friday cliff |
      | Friday | Fun, casual launches | Weekend drops off |

      **Best for most launches: Tuesday or Thursday**

      ### 2. Time of Day

      ```
      B2B launches: 9-10am PT (catches both coasts)
      Consumer: 7-9am PT (before work browsing)
      Global: Multiple announcements by region
      Product Hunt: Midnight PT (for 24hr ranking)
      ```

      ### 3. Seasonal Considerations

      | Period | Consideration |
      |--------|---------------|
      | January | New year energy, budget cycles |
      | Summer | Lower engagement, vacation |
      | September | Back to work, attention |
      | Q4 | Holiday noise, budget spend |
      | December | Year-end reviews, low attention |

      ### 4. Competition Awareness

      **Avoid launching during:**
      - Major competitor announcements
      - Industry flagship events (unless presenting)
      - Major tech company events (Apple, Google I/O)
      - Major news events

      **Consider launching during:**
      - Industry events where you're present
      - Relevant awareness weeks/days
      - Complementary company announcements

      ### 5. Internal Readiness

      ```
      Launch when:
      ✓ Product is stable
      ✓ Support is prepared
      ✓ Sales is trained
      ✓ Marketing assets ready
      ✓ PR is coordinated

      Don't launch when:
      - Key people unavailable
      - Major bugs known
      - Support understaffed
      - Assets incomplete
      ```

  - name: Pre-Launch Buzz Building
    description: Creating anticipation before launch
    when_to_use: Weeks before major launch
    implementation: |
      ## Buzz Building Playbook

      ### 1. Pre-Launch Timeline

      ```
      4 weeks out: Teaser campaign starts
      2 weeks out: Waitlist/early access opens
      1 week out: Exclusive previews to press/influencers
      Day before: Final teases, "tomorrow" hints
      Launch day: Full reveal
      ```

      ### 2. Teaser Content Types

      | Content | Purpose | Example |
      |---------|---------|---------|
      | Problem teaser | Highlight pain | "We've all felt this..." |
      | Vision teaser | Hint at future | "What if..." |
      | Sneak peek | Show glimpses | Blurred screenshots |
      | Countdown | Build urgency | "3 days until..." |
      | Behind the scenes | Build connection | "How we built..." |

      ### 3. Waitlist Strategy

      **Waitlist Value Props**
      - Early access
      - Launch discount
      - Founding member status
      - Input on product

      **Waitlist Growth Tactics**
      - Referral bonuses
      - Social sharing incentives
      - Countdown urgency
      - Exclusive content for signups

      ### 4. Influencer Seeding

      ```
      2 weeks before:
      - Send early access to influencers
      - Provide briefing materials
      - Don't require anything

      1 week before:
      - Check in on experience
      - Offer exclusive angles
      - Coordinate timing

      Launch day:
      - Enable/encourage sharing
      - Provide share assets
      - Amplify their posts
      ```

      ### 5. Press Preparation

      **Embargo Strategy**
      - Brief press under embargo 5-7 days before
      - Provide assets and access
      - Embargo lifts at launch time
      - Coordinated coverage wave

      **Press Kit Contents**
      - Press release
      - Founder quotes
      - High-res images
      - Demo access
      - Fact sheet
      - Founder availability

  - name: Multi-Channel Launch Orchestration
    description: Coordinating launch across channels
    when_to_use: Executing launch day
    implementation: |
      ## Launch Day Orchestration

      ### 1. Channel Timing

      ```
      Launch Day Timeline:

      T-0: Trigger (press embargo lifts)
      T+5min: Blog post live
      T+10min: Email to list
      T+15min: Social posts (all platforms)
      T+30min: Community posts
      T+1hr: Outreach to partners
      T+2hr: Check coverage, respond
      T+4hr: Second wave social
      T+EOD: Recap and thanks
      ```

      ### 2. Channel-Specific Content

      | Channel | Content Style | Timing |
      |---------|---------------|--------|
      | Twitter | Thread + visuals | Immediate |
      | LinkedIn | Professional angle | Immediate |
      | Email | Personal story | 10-15min after |
      | Blog | Full story | Pre-scheduled |
      | Product Hunt | Concise pitch | Midnight PT |
      | Hacker News | Technical angle | Selective |
      | Discord/Slack | Community framing | After public |

      ### 3. Response Protocol

      **Designate Roles**
      ```
      Social lead: Responds to all social
      PR lead: Handles media inquiries
      Support lead: Handles product questions
      Executive: High-profile responses
      ```

      **Response SLAs**
      - Social mentions: < 30 min
      - Press inquiries: < 1 hour
      - Customer questions: < 2 hours

      ### 4. Real-Time Monitoring

      **Track During Launch**
      - Social mentions
      - Press coverage
      - Traffic/signups
      - Sentiment
      - Competitor response

      **Have Ready**
      - Backup content
      - FAQ responses
      - Celebration/milestone posts
      - Damage control templates

      ### 5. Launch War Room

      ```
      Virtual or physical gathering:
      - All key stakeholders present
      - Real-time dashboards
      - Quick decision making
      - Celebration moments
      - Issue resolution

      Duration: First 4-8 hours of launch
      ```

  - name: Post-Launch Momentum
    description: Sustaining energy after launch
    when_to_use: Days and weeks after launch
    implementation: |
      ## Sustaining Post-Launch Momentum

      ### 1. Day 2-7 Content

      | Day | Content Focus |
      |-----|---------------|
      | Day 2 | Behind the scenes / making of |
      | Day 3 | First customer story |
      | Day 4 | Deep dive on key feature |
      | Day 5 | Community/reaction roundup |
      | Day 6 | FAQ / common questions |
      | Day 7 | Week 1 metrics celebration |

      ### 2. Customer Story Capture

      **Immediate Outreach**
      ```
      Right after launch, reach out to:
      - Early adopters
      - Beta testers
      - Excited commenters

      Ask:
      - How they're using it
      - What they love
      - Permission to share
      ```

      ### 3. Momentum Milestones

      **Create Shareable Moments**
      - 100 users
      - 1000 users
      - First paying customer
      - First [industry] customer
      - Featured in [publication]

      **Milestone Announcement Template**
      ```
      "[Milestone] achieved in [timeframe]!
       Thank you to everyone who [action].
       Here's what we're working on next..."
      ```

      ### 4. Iteration Updates

      ```
      Week 2: "What we learned in week 1"
      Week 4: "You asked, we built"
      Month 2: "V1.1 - Based on your feedback"

      Each update is a mini-launch opportunity
      ```

      ### 5. Launch Retrospective

      **Review After 30 Days**
      - What worked?
      - What didn't?
      - Surprise learnings?
      - What to do differently?
      - Impact on key metrics?

      Document for future launches.

anti_patterns:
  - name: Feature List Launch
    description: Launching with feature list instead of story
    why_bad: |
      Features don't resonate emotionally.
      Forgettable.
      Competitors can match features.
    what_to_do_instead: |
      Lead with story and impact.
      Features support narrative.
      Answer "so what?" before listing features.

  - name: Premature Launch
    description: Launching before ready
    why_bad: |
      Bad first impressions stick.
      Wastes launch moment.
      Hard to re-launch.
    what_to_do_instead: |
      Soft launch to limited audience first.
      Fix issues before public launch.
      Better to delay than launch broken.

  - name: Launch and Forget
    description: No post-launch plan
    why_bad: |
      Momentum dies immediately.
      Misses follow-up opportunities.
      Wasted launch effort.
    what_to_do_instead: |
      Plan 2 weeks of post-launch content.
      Capture and share customer stories.
      Create ongoing narrative.

  - name: Single Channel Launch
    description: Launching on one channel only
    why_bad: |
      Limited reach.
      Misses audience segments.
      Doesn't create "everywhere" perception.
    what_to_do_instead: |
      Coordinated multi-channel launch.
      Adapt message for each channel.
      Synchronized timing.

  - name: No Metrics Definition
    description: Launching without success criteria
    why_bad: |
      Can't evaluate success.
      No learning for future.
      Can't prove ROI.
    what_to_do_instead: |
      Define success metrics before launch.
      Set up tracking in advance.
      Review and learn.

handoffs:
  - trigger: "brand story|company narrative"
    to: brand-storytelling
    context: "Need brand storytelling foundation"

  - trigger: "content calendar|ongoing content"
    to: content-marketing
    context: "Need content marketing strategy"

  - trigger: "investor announcement|fundraising"
    to: pitch-narrative
    context: "Need pitch narrative for announcement"

  - trigger: "go-to-market|GTM"
    to: go-to-market
    context: "Need broader GTM strategy"

  - trigger: "PR|media|press strategy"
    to: pr-strategy
    context: "Need press strategy"
