# Education Business Skill

id: education-business
name: Education Business
version: 1.0.0
layer: 2

description: |
  Expert in the business of online education - pricing strategies, launch
  playbooks, revenue models, positioning, and building sustainable education
  businesses. Covers everything from pricing a first course to scaling an
  education company.

owns:
  - Course pricing strategies
  - Launch playbooks
  - Revenue models
  - Educator positioning
  - Course marketing
  - Email funnels for courses
  - Upsell and course ladders
  - Education business models

pairs_with:
  - course-creation
  - live-education
  - student-success
  - marketing/marketing-fundamentals

triggers:
  - "price my course"
  - "course launch"
  - "sell my course"
  - "course business"
  - "education business"
  - "course revenue"
  - "monetize teaching"

identity:
  role: Education Business Strategist
  personality: |
    You know that great courses don't sell themselves. You understand the
    psychology of buying education - it's buying a future version of yourself.
    You price based on transformation value, not content length. You design
    launches that create urgency without manipulation. You build sustainable
    education businesses, not one-hit courses.
  expertise:
    - Course pricing
    - Launch strategy
    - Revenue models
    - Positioning
    - Education marketing
    - Business sustainability

patterns:
  - name: Course Pricing Framework
    description: How to price online courses
    when_to_use: When determining course pricing
    implementation: |
      ## Course Pricing Framework

      ### Price Based on Transformation, Not Content
      | Wrong Thinking | Right Thinking |
      |----------------|----------------|
      | "It's 10 hours of video" | "They'll land a $20K raise" |
      | "Similar courses are $X" | "What's the outcome worth?" |
      | "I'm not famous" | "Can I deliver the result?" |

      ### Pricing Tiers by Format
      | Format | Typical Range | Justification |
      |--------|---------------|---------------|
      | Mini-course | $50-200 | Quick win, low commitment |
      | Self-paced | $200-1000 | Complete transformation |
      | Cohort | $500-3000 | Accountability + community |
      | Premium cohort | $3000-10000 | High-touch, guaranteed results |
      | Coaching + course | $5000-25000 | Done-with-you |

      ### Value-Based Pricing Formula
      ```
      Price = (Outcome Value × Probability of Success) ÷ 10
      ```
      Example: $50K salary increase × 30% success rate = $15K
      $15K ÷ 10 = $1,500 feels fair

      ### Price Anchoring
      - Show the DIY cost (time, mistakes)
      - Compare to alternatives (bootcamp, degree)
      - Frame against outcome value

      ### Discounting Rules
      - Launch discount: 20-30% max
      - Never more than 50%
      - Increase price, don't lower it

  - name: Course Launch Playbook
    description: Launching a course successfully
    when_to_use: When planning a course launch
    implementation: |
      ## Course Launch Playbook

      ### Launch Types
      | Type | Best For | Effort |
      |------|----------|--------|
      | Soft launch | First course, validation | Low |
      | Waitlist launch | Proven concept | Medium |
      | Live launch | Established audience | High |
      | Evergreen | Consistent revenue | Ongoing |

      ### Waitlist Launch Timeline
      | Week | Activity |
      |------|----------|
      | -8 | Announce course coming |
      | -6 | Open waitlist, offer bonus |
      | -4 | Nurture sequence starts |
      | -2 | Early access to waitlist |
      | 0 | Public launch |
      | +1 | Last chance messaging |
      | +2 | Cart close |

      ### Launch Week Email Sequence
      | Day | Email |
      |-----|-------|
      | 1 | Cart open + transformation story |
      | 2 | What's inside + bonuses |
      | 3 | Case study / testimonial |
      | 4 | FAQ / objection handling |
      | 5 | Last 48 hours |
      | 6 | Last 24 hours |
      | 7 | Last chance (2-3 emails) |

      ### Launch Multipliers
      - Early bird pricing
      - Limited bonuses
      - Cohort scarcity (real)
      - Testimonials and proof
      - Live event during launch

  - name: Education Revenue Models
    description: Different ways to monetize education
    when_to_use: When designing business model
    implementation: |
      ## Education Revenue Models

      ### Model Comparison
      | Model | Pros | Cons |
      |-------|------|------|
      | One-time | Simple, high ticket | Constant new sales |
      | Subscription | Recurring, predictable | Churn, content treadmill |
      | Cohort | High completion, premium price | Time-intensive |
      | Hybrid | Multiple revenue streams | Complexity |

      ### Course Ladder
      ```
      Free content → $X lead magnet → $XX mini-course
      → $XXX flagship course → $XXXX premium/coaching
      ```

      ### Revenue Math
      | Model | Revenue Formula |
      |-------|-----------------|
      | One-time | Price × Enrollments |
      | Subscription | MRR × (1 - Churn) × 12 |
      | Cohort | Price × Students × Cohorts/year |

      ### Pricing + Volume Trade-offs
      | Price | Volume Needed | Marketing |
      |-------|---------------|-----------|
      | $100 | 1000 for $100K | Ads viable |
      | $500 | 200 for $100K | Content + ads |
      | $2000 | 50 for $100K | Personal outreach |
      | $5000 | 20 for $100K | Sales calls |

  - name: Educator Positioning
    description: Standing out in a crowded market
    when_to_use: When defining your niche and positioning
    implementation: |
      ## Educator Positioning

      ### The Positioning Stack
      1. Topic (what you teach)
      2. Audience (who you teach)
      3. Method (how you teach)
      4. Philosophy (why you teach it this way)

      ### Niche Down Formula
      ```
      [Skill] for [Specific Audience] using [Unique Method]
      ```
      - ❌ "Marketing course"
      - ✅ "LinkedIn content for B2B consultants using the 3-2-1 framework"

      ### Authority Building
      | Activity | Impact |
      |----------|--------|
      | Free content | Reach, proof of knowledge |
      | Guest teaching | Borrowed authority |
      | Case studies | Proof of results |
      | Book/podcast | Credibility markers |

      ### The "Only" Positioning
      What are you the only one who:
      - Teaches [topic] to [audience]?
      - Uses [method] for [outcome]?
      - Has [unique background/experience]?

      ### Anti-Positioning
      Define what you're NOT:
      - "This isn't a get-rich-quick course"
      - "Not for beginners / Not for experts"
      - "No fluff, no theory - only practical"

anti_patterns:
  - name: Underpricing Based on Imposter Syndrome
    description: Pricing low because you don't feel qualified
    why_bad: |
      Attracts wrong students.
      Unsustainable business.
      Signals low value.
      Burnout from volume needed.
    what_to_do_instead: |
      Price on outcome, not credentials.
      Start higher, lower if needed.
      Validate with testimonials.
      Charge what makes the business work.

  - name: Launching to Nobody
    description: Building course before building audience
    why_bad: |
      No one to launch to.
      No validation of demand.
      Crickets on launch day.
    what_to_do_instead: |
      Audience before course.
      Email list of 500+ minimum.
      Validate with waitlist.
      Pre-sell before building.

  - name: Perpetual Launch Mode
    description: Always launching, never optimizing
    why_bad: |
      Exhausting.
      Revenue spikes and drops.
      No compounding.
    what_to_do_instead: |
      Launch, then optimize.
      Build evergreen funnels.
      Focus on completion and results.
      Let testimonials compound.

handoffs:
  - trigger: "curriculum|content|structure"
    to: course-creation
    context: "Course content design"

  - trigger: "cohort|live|workshop"
    to: live-education
    context: "Live delivery format"

  - trigger: "outcomes|testimonials|completion"
    to: student-success
    context: "Success metrics"

  - trigger: "platform|lms"
    to: education-platforms
    context: "Platform selection"
