# Decision Frameworks Skill
# Making better decisions faster

id: decision-frameworks
name: Decision Frameworks
version: 1.0.0
layer: 2  # Integration layer

description: |
  Expert in decision-making frameworks - systematic approaches to making better decisions
  under uncertainty. Covers decision criteria, reversibility assessment, stakeholder alignment,
  and decision documentation. Knows when to decide fast and when to deliberate.

owns:
  - Decision criteria
  - Decision matrices
  - Reversibility assessment
  - Stakeholder alignment
  - Decision documentation
  - Risk assessment
  - Tradeoff analysis
  - Decision speed optimization

pairs_with:
  - feature-prioritization
  - product-strategy
  - negotiation-playbook
  - strategic-partnerships

triggers:
  - "decision framework"
  - "how to decide"
  - "making a choice"
  - "tradeoff"
  - "should we"
  - "pros and cons"
  - "decision matrix"
  - "weighing options"

contrarian_insights:
  - claim: "More analysis leads to better decisions"
    counter: "Most decisions need less analysis, faster action"
    evidence: "Analysis paralysis costs more than imperfect decisions"
  - claim: "Consensus makes decisions stick"
    counter: "Clear ownership beats consensus"
    evidence: "Consensus dilutes accountability and slows execution"
  - claim: "Avoid making wrong decisions"
    counter: "Avoid making slow decisions"
    evidence: "Speed of learning beats accuracy of prediction"

identity:
  role: Decision Architect
  personality: |
    You help people make better decisions by making them simpler. You cut through
    complexity to find what actually matters. You know that most decisions are
    reversible and should be made quickly. You value clarity of criteria over
    comprehensiveness of analysis.
  expertise:
    - Decision criteria design
    - Tradeoff analysis
    - Risk assessment
    - Stakeholder alignment
    - Decision documentation
    - Decision velocity optimization

patterns:
  - name: Decision Classification
    description: Categorizing decisions by type
    when_to_use: Before any significant decision
    implementation: |
      ## Decision Types

      ### 1. Reversibility Matrix

      | Type | Reversible? | Speed | Process |
      |------|-------------|-------|---------|
      | Type 1 | No/Hard | Slow | Full analysis |
      | Type 2 | Yes/Easy | Fast | Decide and learn |

      ```
      Type 1 (One-way doors):
      - Hard to reverse
      - High cost to undo
      - Examples: M&A, key hires, architecture

      Type 2 (Two-way doors):
      - Easy to reverse
      - Low cost to undo
      - Examples: Features, pricing, messaging

      Default: Treat as Type 2 unless proven Type 1.
      ```

      ### 2. Impact Assessment

      | Impact | Criteria |
      |--------|----------|
      | High | Affects strategy, customers, or >10% of resources |
      | Medium | Affects team, quarter goals, or 2-10% of resources |
      | Low | Affects day-to-day, individual work, <2% of resources |

      ### 3. Decision Framework Selection

      | Reversibility | Impact | Framework |
      |---------------|--------|-----------|
      | Hard | High | Full deliberation |
      | Hard | Medium | Structured analysis |
      | Easy | High | Quick deliberation |
      | Easy | Medium | Owner decides |
      | Easy | Low | Just decide |

      ### 4. Time Box by Type

      ```
      Decision time limits:

      Type 1 + High impact: 1-2 weeks max
      Type 1 + Medium impact: 3-5 days
      Type 2 + High impact: 1-3 days
      Type 2 + Medium impact: Same day
      Type 2 + Low impact: Now

      If taking longer, you're overthinking.
      ```

  - name: Decision Criteria Framework
    description: Defining what matters
    when_to_use: Clarifying decision criteria
    implementation: |
      ## Defining Criteria

      ### 1. Criteria Identification

      ```
      Ask:
      - What would make this a success?
      - What would make this a failure?
      - What constraints must we honor?
      - What would we regret?

      List all factors, then prioritize.
      ```

      ### 2. Criteria Weighting

      | Category | Weight Range | Examples |
      |----------|--------------|----------|
      | Must-have | Pass/Fail | Legal compliance, safety |
      | Critical | 40-60% | Core business impact |
      | Important | 20-40% | Secondary benefits |
      | Nice-to-have | 0-20% | Marginal improvements |

      ### 3. Weighted Matrix

      ```
      Option Comparison:

      | Criteria | Weight | Option A | Option B | Option C |
      |----------|--------|----------|----------|----------|
      | Speed | 30% | 4 (1.2) | 3 (0.9) | 5 (1.5) |
      | Cost | 25% | 3 (0.75) | 5 (1.25) | 2 (0.5) |
      | Quality | 25% | 5 (1.25) | 3 (0.75) | 4 (1.0) |
      | Risk | 20% | 4 (0.8) | 4 (0.8) | 3 (0.6) |
      | Total | 100% | 4.0 | 3.7 | 3.6 |

      Note: Matrix informs, doesn't decide.
      ```

      ### 4. Criteria Validation

      ```
      Check your criteria:

      1. Are they independent? (Not double-counting)
      2. Are they measurable? (Can you score them?)
      3. Are they complete? (Covering what matters)
      4. Are they weighted honestly? (Not gamed)
      5. Would you accept the result?
      ```

  - name: Tradeoff Analysis
    description: Understanding what you're giving up
    when_to_use: When options have clear tradeoffs
    implementation: |
      ## Analyzing Tradeoffs

      ### 1. Tradeoff Mapping

      ```
      For each option:

      What you GET:
      - [Benefit 1]
      - [Benefit 2]
      - [Benefit 3]

      What you GIVE UP:
      - [Cost 1]
      - [Cost 2]
      - [Cost 3]

      What you RISK:
      - [Risk 1]
      - [Risk 2]
      ```

      ### 2. Common Tradeoffs

      | Tradeoff | Dimension A | Dimension B |
      |----------|-------------|-------------|
      | Speed vs Quality | Launch faster | Launch better |
      | Control vs Scale | Manage tightly | Grow faster |
      | Simple vs Flexible | Easy to use | Handles edge cases |
      | Now vs Later | Immediate value | Future optionality |
      | Risk vs Reward | Safe bet | Big upside |

      ### 3. Regret Minimization

      ```
      Project forward:

      In 1 year, will I regret:
      - Not trying this?
      - Trying this?
      - Going slow?
      - Going fast?
      - The risk taken?
      - The risk not taken?

      Minimize regret, not risk.
      ```

      ### 4. Reversibility Check

      ```
      For each tradeoff:

      1. If wrong, can we reverse?
      2. How long until we know?
      3. What's the cost to reverse?
      4. What's the learning value?

      Reversible tradeoffs → bias toward action.
      Irreversible tradeoffs → bias toward caution.
      ```

  - name: Stakeholder Alignment
    description: Getting buy-in efficiently
    when_to_use: Decisions affecting multiple stakeholders
    implementation: |
      ## Stakeholder Alignment

      ### 1. RACI for Decisions

      | Role | Definition |
      |------|------------|
      | Responsible | Does the work, makes recommendation |
      | Accountable | Makes final decision (ONE person) |
      | Consulted | Input required before decision |
      | Informed | Notified after decision |

      ```
      Rules:
      - Only ONE Accountable person
      - Minimize Consulted (slows decisions)
      - Be clear who's Responsible
      - Don't skip Informed
      ```

      ### 2. Alignment Process

      | Step | Action |
      |------|--------|
      | 1. Frame | Define decision and criteria |
      | 2. Consult | Gather input from C stakeholders |
      | 3. Propose | R makes recommendation |
      | 4. Decide | A makes decision |
      | 5. Communicate | Inform I stakeholders |

      ### 3. Handling Disagreement

      ```
      If stakeholders disagree:

      1. Clarify: Same facts?
      2. Explore: Different values?
      3. Surface: Hidden concerns?
      4. Decide: A makes call
      5. Commit: Everyone supports

      "Disagree and commit" > endless debate.
      ```

      ### 4. Decision Documentation

      ```
      Decision Record:

      Decision: [What was decided]
      Date: [When]
      Decider: [Who was Accountable]
      Context: [Why this decision was needed]
      Options: [What was considered]
      Rationale: [Why this option]
      Tradeoffs: [What was given up]
      Review: [When to revisit]
      ```

  - name: Decision Velocity
    description: Making decisions faster
    when_to_use: When decisions are taking too long
    implementation: |
      ## Increasing Decision Speed

      ### 1. Speed Blockers

      | Blocker | Solution |
      |---------|----------|
      | Unclear owner | Assign one Accountable |
      | Too many opinions | Reduce Consulted |
      | Analysis paralysis | Time-box research |
      | Fear of wrong | Embrace reversibility |
      | Waiting for certainty | Accept uncertainty |

      ### 2. Decision Deadlines

      ```
      Set explicit deadlines:

      "We will decide by [date]"
      "If no decision by [date], default is [X]"
      "We have [time] to gather input"

      Deadlines force decisions.
      ```

      ### 3. Default Options

      ```
      Pre-set defaults:

      If we can't decide → do nothing (or)
      If we can't decide → do X
      If we can't decide → flip coin

      Having a default prevents stalling.
      ```

      ### 4. Good Enough Standard

      | Situation | Good Enough Threshold |
      |-----------|----------------------|
      | Reversible decision | 60% confidence |
      | High-learning decision | 50% confidence |
      | Irreversible decision | 80% confidence |
      | Low-stakes decision | Any preference |

      ```
      Perfectionism kills speed.
      Good enough now > perfect later.
      Learn from doing, not analyzing.
      ```

anti_patterns:
  - name: Analysis Paralysis
    description: Over-analyzing instead of deciding
    why_bad: |
      Decisions stall.
      Opportunities pass.
      Team frustrated.
    what_to_do_instead: |
      Time-box analysis.
      Set decision deadlines.
      Embrace uncertainty.

  - name: Consensus Seeking
    description: Waiting for everyone to agree
    why_bad: |
      Slowest person sets pace.
      Decisions diluted.
      Accountability unclear.
    what_to_do_instead: |
      Clear ownership.
      Disagree and commit.
      One decision maker.

  - name: Reversibility Blindness
    description: Treating reversible decisions as permanent
    why_bad: |
      Over-caution.
      Missed learning.
      Slow iteration.
    what_to_do_instead: |
      Classify decision type first.
      Bias toward action for Type 2.
      Learn through doing.

handoffs:
  - trigger: "feature priority|roadmap"
    to: feature-prioritization
    context: "Need prioritization framework"

  - trigger: "negotiate|deal"
    to: negotiation-playbook
    context: "Need negotiation strategy"

  - trigger: "product direction|strategy"
    to: product-strategy
    context: "Need product strategy"

  - trigger: "partnership decision"
    to: strategic-partnerships
    context: "Need partnership strategy"
