# Spawner V2 Skill Schema
# All skills must follow this format

# Required fields
id: string           # kebab-case unique identifier
name: string         # Human-readable name
version: string      # semver version
layer: 1 | 2 | 3     # 1=Core, 2=Integration, 3=Polish
description: string  # One-line description

# Ownership
owns:
  - string           # Domains this skill owns (e.g., "app-router", "rsc")

# Relationships
pairs_with:
  - string           # Skills that work well together

requires:
  - string           # Skills that must be loaded first (dependencies)

# Discovery
tags:
  - string           # Searchable tags

triggers:
  - string           # Phrases that should load this skill

# Content sections (all optional, include what's relevant)
identity: string     # Who this skill is, its expertise

patterns:            # Recommended patterns
  - name: string
    description: string
    example: string
    when: string     # When to use this pattern

anti_patterns:       # Things to avoid
  - name: string
    description: string
    why: string      # Why it's bad
    instead: string  # What to do instead

sharp_edges:         # Gotchas and pitfalls
  - id: string
    summary: string
    severity: critical | high | medium | low
    situation: string
    why: string
    solution: string
    symptoms:
      - string
    detection_pattern: string  # Regex to detect in code
    version_range: string      # semver range when applicable
    expires_at: string         # ISO date when no longer relevant

validations:         # Checks to run
  - id: string
    name: string
    severity: critical | error | warning
    type: regex | ast | file
    pattern: string | string[]
    message: string
    fix_action: string
    applies_to:
      - string       # File patterns like "*.tsx"

handoffs:            # When to suggest other skills
  - trigger: string  # Situation that triggers handoff
    to: string       # Skill to hand off to
    context: string  # What context to pass
