id: mission-planning
name: Mission Planning
category: space
version: 1.0.0
description: >
  Use when designing space missions, computing launch windows, optimizing
  trajectories, analyzing payload constraints, or planning mission phases
  and contingencies.

triggers:
  - "mission design"
  - "launch window"
  - "trajectory optimization"
  - "mission timeline"
  - "mass budget"
  - "propellant budget"
  - "mission phases"
  - "porkchop plot"
  - "C3"
  - "gravity assist"
  - "low thrust"
  - "mission architecture"
  - "LEO"
  - "GEO"
  - "interplanetary"

provides:
  - name: launch_window_analysis
    description: Compute launch windows for LEO, GEO, sun-sync, and interplanetary missions
  - name: trajectory_optimization
    description: Optimize trajectories including porkchop plots and gravity assists
  - name: mission_timeline
    description: Define mission phases from launch through disposal
  - name: mass_budget
    description: Spacecraft mass allocation and propellant sizing

knowledge_base:
  mission_types:
    by_destination:
      LEO: "< 2000 km altitude"
      MEO: "2000 - 35786 km"
      GEO: "35786 km (geostationary)"
      Lunar: "Moon orbit or surface"
      Interplanetary: "Beyond Earth-Moon system"
      Deep_Space: "Outer planets and beyond"
    by_orbit_type:
      - Circular
      - "Elliptical (Molniya, GTO)"
      - "Sun-synchronous"
      - "Frozen orbit"
      - "Halo/Libration point"
    by_purpose:
      - Earth Observation
      - Communications
      - Navigation
      - Science/Exploration
      - Human Spaceflight

  launch_sites:
    kennedy:
      name: "Kennedy Space Center"
      latitude: 28.524
      longitude: -80.651
      azimuth_range: "35-120 deg"
    vandenberg:
      name: "Vandenberg SFB"
      latitude: 34.632
      longitude: -120.611
      azimuth_range: "147-201 deg (polar/SSO)"
    baikonur:
      name: "Baikonur Cosmodrome"
      latitude: 45.965
      longitude: 63.305
      azimuth_range: "35-99 deg"
    kourou:
      name: "Guiana Space Centre"
      latitude: 5.232
      longitude: -52.769
      azimuth_range: "-10 to 93 deg"
    note: "Minimum achievable inclination = launch site latitude"

  launch_windows:
    leo_rendezvous:
      description: "Launch when site rotates under target orbital plane"
      frequency: "2 opportunities per day (ascending/descending)"
      duration: "~10 minutes typical"
    geo:
      description: "Target longitude alignment"
      frequency: "1 window per day"
      duration: "~90 minutes with GTO insertion"
    sun_sync:
      description: "Based on Local Time of Ascending Node (LTAN)"
      common_ltans:
        - "6:00 (dawn-dusk, low sun glint)"
        - "10:30 (morning, good illumination)"
        - "13:30 (afternoon, Landsat heritage)"
      inclination: "~98 deg for 700 km altitude"
    interplanetary:
      description: "Synodic period alignment for minimum energy transfer"
      earth_mars: "~26 months between opportunities"
      earth_venus: "~19 months between opportunities"
      window_duration: "~30 days around optimal"

  trajectory_optimization:
    porkchop_plot:
      description: "C3 contours vs departure/arrival dates"
      use: "Find minimum energy launch windows"
      parameters: "Departure date, arrival date, launch C3"
    gravity_assist:
      description: "Use planetary flyby to change velocity"
      benefit: "Free delta-v from planet's orbital motion"
      examples:
        - "VVEJGA (Venus-Venus-Earth-Jupiter)"
        - "Voyager grand tour"
    low_thrust:
      description: "Electric propulsion spiral transfers"
      characteristics:
        - "High Isp (1000-3000s)"
        - "Low thrust (mN to N)"
        - "Long transfer times"
        - "Continuous thrust arcs"

  mission_phases:
    typical_leo:
      - name: Launch
        duration: "~10 minutes"
        events: "Liftoff, Max-Q, stage separations, fairing jettison"
      - name: Orbit Insertion
        duration: "~1 hour"
        events: "Upper stage burn, separation, solar array deploy"
      - name: Commissioning
        duration: "~30 days"
        events: "Checkout, calibration, pointing verification"
      - name: Operations
        duration: "Mission life - 30 days"
        events: "Primary mission activities"
      - name: Disposal
        duration: "~30 days"
        events: "De-orbit burn, passivation, final contact"
    interplanetary:
      - Launch and Earth departure
      - Cruise with trajectory corrections (TCMs)
      - Approach and orbit insertion
      - Science operations
      - Extended mission (if funded)

  mass_budget:
    categories:
      - Structure (primary, secondary, mechanisms)
      - Power (solar arrays, batteries, electronics)
      - ADCS (wheels, thrusters, sensors)
      - Propulsion (engine, tanks, propellant)
      - Thermal (MLI, heaters, radiators)
      - Communications (transponder, antennas)
      - C&DH (computer, data recorder)
      - Payload (mission-specific)
    margins:
      early_phase: "30%+ contingency"
      preliminary: "20% contingency"
      critical_design: "10% contingency"
      flight: "0% (actual mass)"
    rocket_equation: "delta_v = Isp * g0 * ln(m_wet / m_dry)"

  propulsion_sizing:
    isp_by_type:
      cold_gas: 70
      monopropellant: 220
      bipropellant: 320
      ion: 3000
      hall: 1500
    tank_mass_fraction:
      cold_gas: 0.5
      monopropellant: 0.15
      bipropellant: 0.10
      electric: 0.05

patterns:
  - name: mission_concept_development
    steps:
      - "Define science/mission objectives"
      - "Derive requirements (orbit, pointing, data rate)"
      - "Select mission architecture"
      - "Trade study on orbit types"
      - "Preliminary mass and power budget"
      - "Identify launch vehicle options"

  - name: trajectory_design
    steps:
      - "Generate launch window candidates"
      - "Create porkchop plots for options"
      - "Select baseline trajectory"
      - "Design backup trajectories"
      - "Calculate delta-v budget with margins"
      - "Verify launch vehicle capability"

  - name: operations_planning
    steps:
      - "Define mission phases and transitions"
      - "Identify critical operations"
      - "Plan contingency procedures"
      - "Schedule ground contacts"
      - "Allocate data volume per pass"
      - "Document flight rules"

anti_patterns:
  - name: single_launch_window
    problem: "Mission fails if window missed"
    solution: "Always identify backup windows"
  - name: optimistic_mass_budget
    problem: "No margin for growth"
    solution: "20%+ contingency in early phases"
  - name: ignoring_station_keeping
    problem: "Orbit degrades over time"
    solution: "Budget delta-v for orbit maintenance"
  - name: single_string_critical_path
    problem: "Any failure ends mission"
    solution: "Redundancy for critical functions"
  - name: no_disposal_plan
    problem: "Space debris liability"
    solution: "Plan end-of-life from start (25-year rule)"

checklist:
  requirements:
    - "Science/mission objectives documented"
    - "Success criteria defined"
    - "Constraints identified (cost, schedule, mass)"
    - "Stakeholder requirements captured"
  trajectory:
    - "Launch windows identified"
    - "Primary trajectory designed"
    - "Backup trajectories available"
    - "Delta-v budget with margins"
  mass_budget:
    - "All subsystems accounted"
    - "Margins applied (20%+ for early phase)"
    - "Propellant sized for delta-v budget"
    - "Launch vehicle capability verified"
  timeline:
    - "All phases defined"
    - "Key events scheduled"
    - "Critical operations identified"
    - "Contingency time included"
  risk:
    - "Failure modes identified"
    - "Redundancy plan in place"
    - "Contingency procedures documented"
    - "Abort options defined"
