# Idea Maze Skill
# Finding ideas worth building - the Paul Graham way

id: idea-maze
name: Idea Maze Navigation
category: strategy
version: 1.0.0
last_updated: 2025-12-19

description: |
  Most startup ideas are bad. Not because founders lack creativity, but because
  they're solving invented problems instead of lived ones.

  Paul Graham's essays reveal a pattern: the best ideas come from living in the
  future and noticing what's missing. Schlep blindness hides gold. Organic ideas
  beat brainstormed ones. Frighteningly ambitious ideas are often easier.

  This skill synthesizes PG's idea-finding wisdom into actionable guidance.

triggers:
  keywords:
    - startup idea
    - idea validation
    - finding ideas
    - schlep blindness
    - problem worth solving
    - market opportunity
    - idea maze
    - organic ideas
    - pivot
    - what to build
  contexts:
    - Starting a new project
    - Questioning current direction
    - Feeling stuck on what to build
    - Evaluating pivot options

principles:
  - name: Live in the future, notice what is missing
    description: |
      The best ideas come from living on the edge of technology or culture,
      then noticing problems that don't exist yet for most people but will.
      Not "what should exist" but "what's obviously missing from my life."
    source: "How to Get Startup Ideas"
    examples:
      good: "I build AI tools daily and keep hitting this friction..."
      bad: "I bet people will want a social network for pet owners"

  - name: Solve your own problems
    description: |
      You are the best customer you'll ever have. You understand the pain
      deeply. You can iterate daily. Founders who build for themselves
      have unfair advantages in understanding the problem.
    source: "How to Get Startup Ideas"
    examples:
      good: "As a developer, I hate writing documentation. Built a tool."
      bad: "Researched the market, doctors seem to have problems"

  - name: Schlep blindness hides opportunity
    description: |
      The best ideas often look like tedious hard work. That's why no one
      does them. The schlep (boring grind) is a moat. If it were easy and
      fun, someone would have done it. Embrace the schlep.
    source: "Schlep Blindness"
    examples:
      good: "Stripe handled the pain of payment integration that everyone avoided"
      bad: "Let's build another photo sharing app"

  - name: Frighteningly ambitious often beats conservative
    description: |
      Big ideas attract talent, investors, and press. They're harder to
      execute but paradoxically often easier to succeed at because there's
      less competition at the top. Small ideas attract small outcomes.
    source: "Frighteningly Ambitious Startup Ideas"
    examples:
      good: "Replace email" (Slack), "Replace money" (Stripe)
      bad: "Slightly better to-do list app"

  - name: Organic beats brainstormed
    description: |
      Ideas that grow from lived experience are stronger than ideas
      manufactured in brainstorm sessions. If you have to ask "what should
      I build," you probably shouldn't build anything yet. Go get more
      experience until ideas are obvious.
    source: "Organic Startup Ideas"
    examples:
      good: "I kept needing this, finally built it"
      bad: "We brainstormed 50 ideas and voted on the best one"

anti_patterns:
  - name: Solution looking for a problem
    description: Technology-first thinking, then hunting for use cases
    example: "We have blockchain expertise, what can we apply it to?"
    why_bad: You'll never understand the problem as well as someone living it.
    fix: Start with problems you personally have. Build tech to solve them.

  - name: Market research as oracle
    description: Relying on reports and surveys instead of lived experience
    example: "TAM is $50B according to Gartner, let's build in this space"
    why_bad: Market research tells you the past, not the future you want to create.
    fix: Talk to users. Live the problem. Feel the pain firsthand.

  - name: Tarpit ideas
    description: Ideas that look good but have structural problems
    example: "Social network for X" / "Marketplace for Y"
    why_bad: |
      These attract many founders but rarely work. Network effects are brutal
      to bootstrap. Two-sided marketplaces have chicken-egg problems.
    fix: Understand why incumbents won. Find the wedge. Or choose a different idea.

  - name: The sitcom startup
    description: Ideas that sound good in a TV pitch but aren't real problems
    example: "It's like Uber but for dog walking!"
    why_bad: If you have to explain it as "X for Y," it might be a forced analogy.
    fix: Can you describe the problem without referencing another company?

  - name: Scratching a different itch
    description: Building for users you don't understand
    example: "Farmers need an app to..." (said by someone who's never farmed)
    why_bad: You'll miss nuance, build wrong, iterate slowly.
    fix: Build for yourself. Or deeply embed with users for months.

frameworks:
  - name: PG Idea Quality Test
    when_to_use: Evaluating a startup idea
    structure:
      - "Problem: Is this a problem you personally have?"
      - "Frequency: How often does this problem occur?"
      - "Intensity: How much does it hurt when it happens?"
      - "Willingness to pay: Would you pay to solve this?"
      - "Growing: Is this problem getting bigger over time?"
      - "Underserved: Why hasn't this been solved well yet?"

  - name: Schlep Analysis
    when_to_use: Finding hidden opportunity
    structure:
      - "What tasks do you avoid because they're boring/hard?"
      - "What would you pay someone else to do?"
      - "What do experts do manually that could be automated?"
      - "What requires calling someone when it should be self-serve?"
      - "What's a process everyone complains about but accepts?"

  - name: The Mom Test for Ideas
    when_to_use: Validating problem exists
    structure:
      - "Ask about their life, not your idea"
      - "Ask about specifics in the past, not hypotheticals"
      - "Talk less, listen more"
      - "Look for emotional weight"
      - "Follow up on vagueness until concrete"
    questions:
      - "What's the hardest part about [doing X]?"
      - "Tell me about the last time you faced this problem"
      - "What have you tried? What didn't work?"
      - "What would it be worth to you to solve this?"

  - name: Idea Journal Practice
    when_to_use: Building idea generation muscle
    structure:
      - "Daily: Notice and write down frictions"
      - "Weekly: Review patterns in your notes"
      - "Monthly: Deep dive on most repeated problems"
      - "Quarterly: Evaluate top ideas against PG criteria"
    notes: |
      Ideas compound. Most good founders have notebooks full of ideas
      before they find the one worth pursuing.

handoffs:
  receives_from:
    - skill: founder-character
      receives: The mindset to notice opportunities

  hands_to:
    - skill: product-strategy
      provides: Validated problem to solve
    - skill: early-stage-hustle
      provides: Idea to execute on
    - skill: talk-to-users
      provides: Hypothesis to validate

resources:
  essential:
    - title: "How to Get Startup Ideas"
      author: "Paul Graham"
      url: "http://paulgraham.com/startupideas.html"
      type: essay
      why: "The definitive essay on finding startup ideas"
    - title: "Schlep Blindness"
      author: "Paul Graham"
      url: "http://paulgraham.com/schlep.html"
      type: essay
      why: "Why the best opportunities are hidden in boring work"

  recommended:
    - title: "Frighteningly Ambitious Startup Ideas"
      author: "Paul Graham"
      url: "http://paulgraham.com/ambitious.html"
      type: essay
      why: "Why big ideas are often more achievable"
    - title: "Organic Startup Ideas"
      author: "Paul Graham"
      url: "http://paulgraham.com/organic.html"
      type: essay
      why: "Ideas that grow naturally from experience"
    - title: "The Mom Test"
      author: "Rob Fitzpatrick"
      type: book
      why: "How to validate ideas through conversation"
