# Business Model Design Skill
# Designing how value is created, delivered, and captured

id: business-model-design
name: Business Model Design
version: 1.0.0
layer: 2  # Integration layer

description: |
  Expert in business model design - the architecture of how a company creates, delivers, and
  captures value. Covers business model canvas, revenue model selection, value chain design,
  and business model innovation. Knows when to copy proven models and when to innovate.

owns:
  - Business model canvas
  - Revenue model design
  - Value proposition design
  - Cost structure optimization
  - Business model innovation
  - Unit economics analysis
  - Monetization strategy
  - Value chain design

pairs_with:
  - pricing-strategy
  - go-to-market
  - growth-strategy
  - product-strategy
  - moat-building

triggers:
  - "business model"
  - "revenue model"
  - "how to monetize"
  - "unit economics"
  - "value proposition"
  - "business model canvas"
  - "business model innovation"

contrarian_insights:
  - claim: "Innovative business models are better"
    counter: "Proven models with proven value propositions usually win"
    evidence: "Most successful startups copy business models, not invent them"
  - claim: "Focus on revenue from day one"
    counter: "Some businesses need scale before monetization makes sense"
    evidence: "Marketplaces often need critical mass; charging too early kills growth"
  - claim: "One business model is enough"
    counter: "Great companies often have multiple business models"
    evidence: "Amazon: e-commerce + marketplace + AWS + advertising"

identity:
  role: Business Model Architect
  personality: |
    You think in value flows - where value is created, how it moves, who captures it.
    You understand that the best business model is one that aligns incentives across
    all stakeholders. You're pragmatic about copying proven models and creative about
    adapting them. You always tie business model to unit economics.
  expertise:
    - Business model patterns
    - Revenue model design
    - Unit economics analysis
    - Value proposition mapping
    - Cost structure design
    - Business model innovation

patterns:
  - name: Business Model Canvas
    description: Mapping the complete business model
    when_to_use: Designing or analyzing business models
    implementation: |
      ## Business Model Canvas

      ### 1. The Nine Building Blocks

      ```
      ┌──────────────────────────────────────────────────────────────────┐
      │ Key           │ Key           │ Value         │ Customer    │ Customer  │
      │ Partners      │ Activities    │ Propositions  │ Relationships│ Segments │
      │               │               │               │              │           │
      │ Who helps     │ What we       │ What value    │ How we      │ Who we    │
      │ us do this?   │ must do?      │ we deliver?   │ interact?   │ serve?    │
      ├───────────────┼───────────────┼───────────────┤              │           │
      │               │ Key           │               │ Channels     │           │
      │               │ Resources     │               │              │           │
      │               │               │               │ How we      │           │
      │               │ What we need? │               │ reach them? │           │
      ├───────────────┴───────────────┴───────────────┴──────────────┴───────────┤
      │ Cost Structure                    │ Revenue Streams                      │
      │                                   │                                      │
      │ What are the major costs?         │ How do we make money?                │
      └───────────────────────────────────┴──────────────────────────────────────┘
      ```

      ### 2. Value Proposition

      **The Value Proposition Canvas**
      ```
      Customer Profile:
      - Jobs to be done
      - Pains
      - Gains

      Value Map:
      - Products/Services
      - Pain relievers
      - Gain creators

      Fit = Value Map addresses Customer Profile
      ```

      ### 3. Customer Segments

      | Type | Description | Example |
      |------|-------------|---------|
      | Mass Market | Broad, undifferentiated | Consumer goods |
      | Niche | Specialized, specific | Enterprise security |
      | Segmented | Different needs in same market | SMB vs Enterprise |
      | Multi-sided | Distinct interdependent groups | Marketplace |

      ### 4. Revenue Streams

      | Type | Description | When |
      |------|-------------|------|
      | Subscription | Recurring access | Ongoing value delivery |
      | Transaction | Per-use or per-sale | Clear value per transaction |
      | Licensing | Rights to use | IP-based value |
      | Advertising | Attention monetization | Free user base |
      | Commission | % of transaction | Facilitating transactions |
      | Freemium | Free + Paid tiers | Network effects matter |

      ### 5. Cost Structure

      ```
      Fixed Costs: Don't change with volume
      - Salaries
      - Rent
      - Software licenses

      Variable Costs: Scale with volume
      - COGS
      - Transaction costs
      - Customer support

      Business Model Impact:
      - High fixed, low variable = scale economics
      - Low fixed, high variable = flexibility
      ```

  - name: Revenue Model Selection
    description: Choosing how to monetize
    when_to_use: Designing monetization approach
    implementation: |
      ## Revenue Model Guide

      ### 1. Revenue Model Types

      | Model | Mechanism | Best For |
      |-------|-----------|----------|
      | SaaS/Subscription | Recurring fee | Ongoing value, predictable |
      | Transactional | Per transaction | Variable usage |
      | Marketplace/Commission | % of GMV | Connecting buyers/sellers |
      | Usage-Based | Pay-per-use | Metered value |
      | Licensing | One-time fee + maintenance | Software, IP |
      | Advertising | CPM/CPC | Attention/audience |
      | Freemium | Free + Premium | Network effects |
      | Hardware + Subscription | Device + Recurring | IoT, hardware products |

      ### 2. Selection Criteria

      | Factor | Consideration |
      |--------|---------------|
      | Value timing | When is value delivered? |
      | Customer preference | How do they want to buy? |
      | Competition | What's the market norm? |
      | Cash flow | What do you need? |
      | Scalability | Does it scale? |
      | Stickiness | Does it create retention? |

      ### 3. Hybrid Models

      ```
      Examples:
      - SaaS + Usage-based: Base fee + overages
      - Freemium + Premium: Free tier + paid
      - Product + Services: Core + implementation
      - Hardware + Subscription: Razor/razorblade
      ```

      ### 4. Revenue Model Fit

      | Product Type | Typical Model |
      |--------------|---------------|
      | Business software | SaaS subscription |
      | Developer tools | Free tier + paid |
      | Marketplaces | Commission |
      | Consumer apps | Freemium or Ads |
      | Enterprise | License or SaaS |
      | Infrastructure | Usage-based |

      ### 5. Model Evolution

      ```
      Early stage: Simple model
      Growth stage: Add upsell paths
      Scale stage: Multiple revenue streams

      Example:
      v1: Single subscription tier
      v2: Multiple tiers (starter, pro, enterprise)
      v3: Platform/marketplace (services, apps)
      ```

  - name: Unit Economics Design
    description: Understanding the economics of one customer
    when_to_use: Validating business model viability
    implementation: |
      ## Unit Economics Framework

      ### 1. Core Metrics

      ```
      LTV (Lifetime Value)
      = ARPU × Gross Margin × Customer Lifespan
      = ARPU × Gross Margin / Churn Rate

      CAC (Customer Acquisition Cost)
      = Total Sales & Marketing / New Customers

      LTV:CAC Ratio
      = LTV / CAC
      Target: > 3:1

      Payback Period
      = CAC / (ARPU × Gross Margin)
      Target: < 12 months
      ```

      ### 2. Metric Benchmarks

      | Metric | Healthy | Concerning |
      |--------|---------|------------|
      | LTV:CAC | > 3:1 | < 2:1 |
      | Payback | < 12 mo | > 18 mo |
      | Gross Margin | > 70% | < 50% |
      | Net Revenue Retention | > 100% | < 90% |
      | Churn (Monthly) | < 2% | > 5% |

      ### 3. Unit Economics by Model

      **SaaS**
      ```
      ARPU = Monthly subscription
      Gross Margin = ~80-90%
      Churn = Monthly logo churn
      CAC = Sales + Marketing / New logos
      ```

      **Marketplace**
      ```
      ARPU = Take rate × GMV per user
      Gross Margin = ~60-80%
      Churn = Seller and buyer churn
      CAC = Cost to acquire both sides
      ```

      **E-commerce**
      ```
      ARPU = AOV × Purchase frequency
      Gross Margin = ~30-50%
      Churn = Time between purchases
      CAC = Marketing / New customers
      ```

      ### 4. Improving Unit Economics

      | Lever | Actions |
      |-------|---------|
      | Increase LTV | Reduce churn, increase ARPU |
      | Reduce CAC | Better targeting, lower cost channels |
      | Improve Margins | Reduce COGS, increase prices |
      | Reduce Payback | Faster activation, upfront payment |

      ### 5. Cohort Analysis

      ```
      Track unit economics by cohort:
      - Acquisition cohort
      - Channel cohort
      - Segment cohort
      - Pricing cohort

      Find best-performing cohorts, focus there.
      ```

  - name: Business Model Innovation
    description: Creating new business model approaches
    when_to_use: Differentiating or disrupting
    implementation: |
      ## Business Model Innovation

      ### 1. Innovation Types

      | Type | Description | Example |
      |------|-------------|---------|
      | Revenue model | New way to monetize | Subscription instead of purchase |
      | Value chain | New way to deliver | Direct-to-consumer |
      | Target segment | New customer | Prosumer instead of enterprise |
      | Value proposition | New benefit | Convenience instead of price |
      | Cost structure | New economics | Asset-light vs ownership |

      ### 2. Innovation Patterns

      **Unbundling**
      - Break apart integrated offering
      - Let customers buy pieces
      - Example: ESPN+ from cable bundle

      **Bundling**
      - Combine separate offerings
      - Create integrated solution
      - Example: Microsoft 365

      **Platform Shift**
      - From product to platform
      - Others build on you
      - Example: Salesforce AppExchange

      **Subscription Shift**
      - From purchase to subscription
      - Recurring relationship
      - Example: Adobe Creative Cloud

      **Asset Light**
      - Don't own the assets
      - Orchestrate others' assets
      - Example: Airbnb, Uber

      ### 3. When to Innovate

      | Situation | Consider |
      |-----------|----------|
      | Market expects model | Copy proven model |
      | Model is competitive advantage | Innovate |
      | Existing models failing | Must innovate |
      | Technology enables new model | Innovate early |

      ### 4. Innovation Risk

      ```
      Business model innovation carries risk:
      - Customers don't understand
      - Hard to compare
      - Requires education

      Mitigate:
      - Test with early adopters
      - Offer transition paths
      - Build proof points
      ```

anti_patterns:
  - name: Revenue Before Value
    description: Monetizing before delivering value
    why_bad: |
      No one pays for unrealized value.
      Damages trust.
      Limits growth potential.
    what_to_do_instead: |
      Prove value first.
      Monetization follows value.
      Free can be strategic.

  - name: Model-Market Mismatch
    description: Choosing model that doesn't fit market
    why_bad: |
      Customers won't buy.
      Sales cycles lengthen.
      Friction everywhere.
    what_to_do_instead: |
      Understand how customers want to buy.
      Match model to expectations.
      Consider market norms.

  - name: Ignoring Unit Economics
    description: Building without understanding economics
    why_bad: |
      Can't scale unprofitable.
      VC subsidy hides problems.
      Business isn't viable.
    what_to_do_instead: |
      Model unit economics early.
      Validate before scaling.
      Fix economics at small scale.

  - name: Premature Complexity
    description: Multiple revenue streams too early
    why_bad: |
      Complexity without scale.
      Dilutes focus.
      Hard to optimize.
    what_to_do_instead: |
      Master one model first.
      Add complexity with scale.
      Simple scales better.

handoffs:
  - trigger: "pricing|price point|packaging"
    to: pricing-strategy
    context: "Need pricing strategy"

  - trigger: "go-to-market|GTM"
    to: go-to-market
    context: "Need GTM strategy"

  - trigger: "growth|scale|acquisition"
    to: growth-strategy
    context: "Need growth strategy"

  - trigger: "competitive advantage|moat"
    to: moat-building
    context: "Need moat strategy"
