# Customer Success Skill
# Turning users into advocates - the engine of sustainable growth

id: customer-success
name: Customer Success
category: product
version: 1.0.0
last_updated: 2025-12-19

description: |
  Acquisition is expensive. Retention is profitable. Customer success is the
  discipline of ensuring customers achieve their desired outcomes with your
  product - which leads to retention, expansion, and advocacy.

  This skill covers onboarding that activates, health scoring that predicts,
  retention plays that save, and expansion strategies that grow accounts.

triggers:
  keywords:
    - customer success
    - onboarding
    - retention
    - churn
    - activation
    - nps
    - health score
    - expansion revenue
    - upsell
    - customer lifecycle
    - time to value
  file_patterns:
    - "**/onboarding/**"
    - "**/activation/**"
    - "**/retention/**"
  contexts:
    - Reducing churn
    - Improving onboarding
    - Building customer health dashboards

principles:
  - name: Time to value is everything
    description: |
      The faster users get value, the more likely they stick. Measure and
      optimize time to first value moment. Remove every obstacle between
      signup and aha moment.
    examples:
      good: User sees value in first session, under 5 minutes
      bad: Value requires days of setup, learning, configuration

  - name: Proactive beats reactive
    description: |
      Reach out before problems escalate. Health scores predict churn before
      it happens. Intervention when metrics dip is worth 10x intervention
      after cancellation request.
    examples:
      good: Alert when usage drops, proactive check-in call
      bad: Notice churn only when credit card fails

  - name: Segment for relevance
    description: |
      Not all customers are the same. High-touch for enterprise, tech-touch
      for SMB, self-serve for individuals. Match effort to customer value
      and needs.
    examples:
      good: Dedicated CSM for enterprise, automated sequences for self-serve
      bad: Same email blast to everyone regardless of tier

  - name: Measure leading indicators
    description: |
      Revenue is a lagging indicator. By the time it drops, damage is done.
      Track leading indicators: engagement, feature adoption, support tickets,
      NPS changes.
    examples:
      good: Dashboard with daily engagement, weekly feature adoption, monthly NPS
      bad: Only looking at MRR and wondering why it dropped

  - name: Make expansion natural
    description: |
      Upselling should feel like helping, not selling. When customers outgrow
      their tier, expansion is a solution. When they hit limits, upgrade is
      obvious.
    examples:
      good: Usage-based nudge when approaching limits with clear value prop
      bad: Aggressive sales calls pushing features they do not need

anti_patterns:
  - name: Onboarding as checklist
    description: Long list of tasks with no clear path to value
    example: 15-step setup wizard that takes an hour to complete
    why_bad: Users give up. Completion rate plummets. Value never reached.
    fix: Minimum viable onboarding to first value. Progressive disclosure after.

  - name: Vanity health scores
    description: Health scores that look good but do not predict churn
    example: Score based on logins only, ignoring actual value delivery
    why_bad: False confidence. Real churn signals missed.
    fix: Validate scores against actual churn data. Iterate until predictive.

  - name: Spray and pray outreach
    description: Mass emails that ignore customer context
    example: Same monthly newsletter to churning and expanding customers
    why_bad: Irrelevant noise. Trained to ignore your emails.
    fix: Segment and personalize. Different messages for different states.

  - name: Saving at cancellation
    description: Only trying to retain at the moment of churn
    example: Discount offer when clicking cancel button
    why_bad: Too late. Trust already gone. Discounts attract price-sensitive churners.
    fix: Intervene early when health declines. Build relationship before crisis.

  - name: Ignoring power users
    description: All focus on at-risk, none on advocates
    example: No program for happy customers to refer, review, or expand
    why_bad: Missed expansion. Missed advocacy. Missed word-of-mouth.
    fix: Success program for happy customers. Make it easy to advocate.

frameworks:
  - name: Customer Lifecycle Stages
    when_to_use: Designing customer journey
    structure:
      - "Onboarding: First 7-30 days, focus on activation"
      - "Adoption: Months 1-3, feature expansion"
      - "Value Realization: Months 3-6, proving ROI"
      - "Expansion: Months 6+, growth and advocacy"
      - "Renewal: Annual milestone, re-validation"

  - name: Health Score Components
    when_to_use: Building predictive health score
    structure:
      - "Product usage: DAU/WAU, feature adoption, depth of use"
      - "Support health: Ticket volume, sentiment, response satisfaction"
      - "Relationship: Meeting cadence, stakeholder engagement"
      - "Business fit: Growth trajectory, use case fit"
      - "Risk signals: Payment issues, competitor mentions, complaints"
    notes: Weight by correlation with actual churn data

  - name: Intervention Playbook
    when_to_use: Responding to health score drops
    structure:
      - "Green (80-100): Expansion focus, advocacy asks"
      - "Yellow (60-79): Proactive check-in, address concerns"
      - "Orange (40-59): Executive outreach, recovery plan"
      - "Red (0-39): All-hands, executive escalation, save attempt"

  - name: Onboarding Metrics
    when_to_use: Measuring onboarding effectiveness
    structure:
      - "Activation rate: Percent reaching key value moment"
      - "Time to value: Duration from signup to activation"
      - "Onboarding completion: Percent finishing key steps"
      - "Day 1/7/30 retention: Percent returning"

handoffs:
  receives_from:
    - skill: product-strategy
      receives: Activation definitions and value moments
    - skill: email-systems
      receives: Automated sequence infrastructure

  hands_to:
    - skill: growth-strategy
      provides: Retention insights for acquisition targeting
    - skill: analytics-architecture
      provides: Health score and lifecycle event definitions

resources:
  essential:
    - title: Customer Success by Nick Mehta
      type: book
      why: Foundational text on customer success discipline
    - title: Gainsight
      url: https://www.gainsight.com/resources
      type: resource
      why: Industry-leading CS resources

  recommended:
    - title: ChurnZero Blog
      url: https://churnzero.com/blog
      type: blog
      why: Practical CS tactics and benchmarks
