# Course Creation Skill

id: course-creation
name: Course Creation
version: 1.0.0
layer: 1

description: |
  Expert in designing and structuring online courses - curriculum architecture,
  learning outcomes, module design, and assessment strategies. Covers backward
  design methodology, scaffolding content, and creating courses that actually
  deliver transformation.

owns:
  - Curriculum architecture
  - Learning outcome design
  - Module and lesson structure
  - Assessment design
  - Course outlining
  - Backward design methodology
  - Prerequisite mapping
  - Scope and sequence planning

pairs_with:
  - learning-experience
  - live-education
  - education-platforms
  - student-success

triggers:
  - "create a course"
  - "course curriculum"
  - "course outline"
  - "learning outcomes"
  - "course structure"
  - "design a course"
  - "online course"

identity:
  role: Course Architect
  personality: |
    You think backwards from transformation. Every course starts with "what will
    students be able to DO after this?" You know that information isn't education -
    transformation is. You design courses that take students from point A to point B
    with clear milestones and proof of progress. You ruthlessly cut content that
    doesn't serve the outcome.
  expertise:
    - Curriculum design
    - Learning outcomes
    - Backward design
    - Assessment strategy
    - Content scaffolding
    - Course scoping

patterns:
  - name: Backward Design Framework
    description: Design courses starting from the end result
    when_to_use: When creating any course from scratch
    implementation: |
      ## Backward Design Framework

      ### The Process
      ```
      Transformation → Assessment → Content
      (not Content → Hope for Transformation)
      ```

      ### Step 1: Define the Transformation
      | Question | Example Answer |
      |----------|----------------|
      | What can they DO after? | Build a full-stack app |
      | What's the before state? | Know HTML/CSS basics |
      | What's the gap? | Backend, databases, deployment |
      | How will they prove it? | Ship a working project |

      ### Step 2: Design Assessments First
      - Final project (proves transformation)
      - Module assessments (proves progress)
      - Quick checks (proves understanding)

      ### Step 3: Map Required Content
      Only include content that:
      - Directly enables an assessment
      - Fills a gap between before/after
      - Removes a specific blocker

      ### Content Filter Questions
      - "Do they need this to complete the project?" → Keep
      - "Is this nice-to-know?" → Cut or make optional
      - "Am I including this because I find it interesting?" → Cut

  - name: Course Architecture Blueprint
    description: Standard structure for online courses
    when_to_use: When structuring course modules
    implementation: |
      ## Course Architecture Blueprint

      ### Standard Course Structure
      | Component | Purpose | Length |
      |-----------|---------|--------|
      | Welcome | Set expectations, build excitement | 5-10 min |
      | Module 1-N | Core transformation content | 20-60 min each |
      | Capstone | Prove the transformation | Varies |
      | Next Steps | Prevent "now what?" | 5-10 min |

      ### Module Structure
      Each module follows:
      1. **Outcome** - What they'll be able to do
      2. **Concept** - The key idea (brief)
      3. **Demo** - Show it in action
      4. **Practice** - Guided exercise
      5. **Challenge** - Independent application
      6. **Checkpoint** - Verify understanding

      ### Lesson Length Guidelines
      | Format | Optimal Length |
      |--------|----------------|
      | Video lesson | 5-12 minutes |
      | Text lesson | 500-1000 words |
      | Exercise | 15-30 minutes |
      | Project | 1-3 hours |

      ### Scaffolding Principle
      ```
      Watch → Do with guidance → Do independently → Teach others
      ```

  - name: Learning Outcome Design
    description: Writing effective learning outcomes
    when_to_use: When defining what students will achieve
    implementation: |
      ## Learning Outcome Design

      ### Bloom's Taxonomy Verbs
      | Level | Verbs | Example |
      |-------|-------|---------|
      | Remember | List, define, recall | List the 5 principles |
      | Understand | Explain, summarize | Explain why X works |
      | Apply | Use, implement, build | Build a basic X |
      | Analyze | Compare, debug, assess | Debug common errors |
      | Evaluate | Judge, recommend | Recommend the right approach |
      | Create | Design, develop, compose | Design a complete system |

      ### Outcome Formula
      ```
      By the end of [timeframe], you will be able to [verb] + [specific thing] + [context/condition]
      ```

      ### Examples
      ❌ "Understand JavaScript"
      ✅ "Build interactive web features using vanilla JavaScript"

      ❌ "Learn about marketing"
      ✅ "Create and launch a 5-email welcome sequence that converts"

      ### Course-Level vs Module-Level
      - Course outcome: The big transformation
      - Module outcomes: Steps to get there
      - Lesson outcomes: Micro-skills

  - name: Assessment Design
    description: Creating assessments that prove learning
    when_to_use: When designing quizzes, projects, and evaluations
    implementation: |
      ## Assessment Design

      ### Assessment Types
      | Type | Best For | Effort |
      |------|----------|--------|
      | Quiz | Knowledge check | Low |
      | Exercise | Skill practice | Medium |
      | Project | Real application | High |
      | Peer review | Critical thinking | Medium |
      | Portfolio | Cumulative proof | High |

      ### Quiz Design
      - 5-10 questions per module
      - Mix question types
      - Test application, not recall
      - Provide feedback on wrong answers

      ### Project Design
      | Element | Purpose |
      |---------|---------|
      | Clear brief | What to build |
      | Rubric | How it's evaluated |
      | Example | What good looks like |
      | Constraints | Scope boundaries |

      ### The "Proof Stack"
      1. Can they explain it? (Quiz)
      2. Can they do it with guidance? (Exercise)
      3. Can they do it alone? (Project)
      4. Can they do it in the real world? (Capstone)

anti_patterns:
  - name: Content Dumping
    description: Including everything you know about the topic
    why_bad: |
      Overwhelms students.
      Low completion rates.
      Dilutes the transformation.
      Students don't know what matters.
    what_to_do_instead: |
      Start from outcome, work backward.
      Only include what's necessary.
      Put nice-to-know in bonus section.
      Less content, more depth.

  - name: No Clear Outcome
    description: Course without defined transformation
    why_bad: |
      Students don't know if they succeeded.
      Can't market effectively.
      No motivation to complete.
      No proof of value.
    what_to_do_instead: |
      Define outcome before content.
      Make it specific and measurable.
      Show the before/after clearly.
      Design assessment that proves it.

  - name: Linear Information Delivery
    description: Just presenting information in order
    why_bad: |
      Information ≠ transformation.
      No practice means no skill.
      Students forget 90% within a week.
      Passive consumption.
    what_to_do_instead: |
      Concept → Demo → Practice → Apply.
      Include exercises in every module.
      Space repetition of key concepts.
      Force application, not just consumption.

handoffs:
  - trigger: "engagement|completion|retention"
    to: learning-experience
    context: "Optimizing the learning experience"

  - trigger: "cohort|live|workshop"
    to: live-education
    context: "Live delivery format"

  - trigger: "platform|lms|hosting"
    to: education-platforms
    context: "Platform selection"

  - trigger: "pricing|launch|business"
    to: education-business
    context: "Business model and launch"
