# Email Systems Skill
# The most underrated growth channel - done right

id: email-systems
name: Email Systems
category: integration
version: 1.0.0
last_updated: 2025-12-19

description: |
  Email has the highest ROI of any marketing channel. $36 for every $1 spent.
  Yet most startups treat it as an afterthought - bulk blasts, no personalization,
  landing in spam folders.

  This skill covers transactional email that works, marketing automation that
  converts, deliverability that reaches inboxes, and the infrastructure decisions
  that scale.

triggers:
  keywords:
    - email
    - transactional email
    - email marketing
    - email automation
    - drip campaign
    - newsletter
    - email sequence
    - resend
    - sendgrid
    - postmark
    - mailgun
    - deliverability
    - email templates
  file_patterns:
    - "**/email*.ts"
    - "**/mail*.ts"
    - "**/notify*.ts"
    - "**/templates/email/**"
  code_patterns:
    - "resend"
    - "sendgrid"
    - "postmark"
    - "nodemailer"

principles:
  - name: Transactional vs Marketing separation
    description: |
      Transactional emails (password reset, receipts) need 100% delivery.
      Marketing emails (newsletters, promos) have lower priority. Use separate
      IP addresses and providers to protect transactional deliverability.
    examples:
      good: "Password resets via Postmark, marketing via ConvertKit"
      bad: "All emails through one SendGrid account"

  - name: Permission is everything
    description: |
      Only email people who asked to hear from you. Double opt-in for marketing.
      Easy unsubscribe. Clean your list ruthlessly. Bad lists destroy deliverability.
    examples:
      good: "Confirmed subscription + one-click unsubscribe"
      bad: "Scraped email list, hidden unsubscribe, bought contacts"

  - name: Deliverability is infrastructure
    description: |
      SPF, DKIM, DMARC are not optional. Warm up new IPs. Monitor bounce rates.
      Deliverability is earned through technical setup and good behavior.
    examples:
      good: "All DNS records configured, dedicated IP warmed for 4 weeks"
      bad: "Using free tier shared IP, no authentication records"

  - name: One email, one goal
    description: |
      Each email should have exactly one purpose and one CTA. Multiple asks
      means nothing gets clicked. Clear single action.
    examples:
      good: "Click here to verify your email" (one button)
      bad: "Verify email, check out our blog, follow us on Twitter, refer a friend..."

  - name: Timing and frequency matter
    description: |
      Wrong time = low open rates. Too frequent = unsubscribes. Let users
      set preferences. Test send times. Respect inbox fatigue.
    examples:
      good: "Weekly digest on Tuesday 10am user's timezone, preference center"
      bad: "Daily emails at random times, no way to reduce frequency"

anti_patterns:
  - name: HTML email soup
    description: Complex HTML with broken rendering across clients
    example: Tables nested 10 deep, custom fonts, complex CSS
    why_bad: Email clients render differently. Outlook breaks everything.
    fix: Use email-first frameworks (MJML, React Email). Test in Litmus/Email on Acid.

  - name: No plain text fallback
    description: Sending HTML-only emails
    example: Only HTML version, no text/plain multipart
    why_bad: Some clients strip HTML. Accessibility issues. Spam signal.
    fix: Always include plain text version with key info.

  - name: Huge image emails
    description: Emails that are mostly images with little text
    example: One big image as the entire email body
    why_bad: Images blocked by default. Spam trigger. Slow loading.
    fix: Real text with images as enhancement. Alt text on images.

  - name: No monitoring
    description: Sending emails without tracking deliverability
    example: Fire and forget, no bounce handling, no feedback loops
    why_bad: Silent failures. List decay. Reputation damage.
    fix: Track bounces, complaints, opens. Remove bad addresses. Set up feedback loops.

  - name: Personalization theater
    description: Fake personalization that insults intelligence
    example: "Hi {first_name}," with nothing else personalized
    why_bad: Token personalization is transparent. Actually annoying.
    fix: Real personalization based on behavior, or don't fake it.

frameworks:
  - name: Transactional Email Architecture
    when_to_use: Setting up email infrastructure from scratch
    structure:
      - "Provider selection: Postmark for transactional (best deliverability)"
      - "Authentication: SPF + DKIM + DMARC records"
      - "Templates: React Email or MJML for consistency"
      - "Queuing: Background jobs with retry logic"
      - "Monitoring: Bounce rates, complaint rates, delivery rates"

  - name: Onboarding Sequence
    when_to_use: New user activation emails
    structure:
      - "Day 0: Welcome + single key action"
      - "Day 1: Quick win tutorial"
      - "Day 3: Feature highlight (based on usage)"
      - "Day 7: Case study / social proof"
      - "Day 14: Check-in + help offer"
    notes: Behavior-triggered beats time-triggered

  - name: Re-engagement Campaign
    when_to_use: Activating dormant users
    structure:
      - "Email 1: We miss you + new features"
      - "Email 2: What you left behind (their data)"
      - "Email 3: Last chance before account cleanup"
      - "Sunset: Remove from list if no engagement"

  - name: Email Provider Selection
    when_to_use: Choosing email infrastructure
    structure:
      - "Transactional: Postmark (best deliverability) or Resend (modern DX)"
      - "Marketing: ConvertKit (creators) or Customer.io (product-led)"
      - "All-in-one: SendGrid (scale) but separate transactional"
      - "Self-hosted: Avoid unless you really know what you are doing"

handoffs:
  receives_from:
    - skill: copywriting
      receives: Email copy and sequences
    - skill: customer-success
      receives: Onboarding flow design
    - skill: marketing
      receives: Campaign requirements

  hands_to:
    - skill: analytics-architecture
      provides: Email event tracking
    - skill: devops
      provides: Infrastructure requirements

resources:
  essential:
    - title: "React Email"
      url: "https://react.email"
      type: tool
      why: "Modern email templating with React components"
    - title: "Postmark Guides"
      url: "https://postmarkapp.com/guides"
      type: resource
      why: "Best practices for transactional email"

  recommended:
    - title: "Resend"
      url: "https://resend.com"
      type: tool
      why: "Developer-friendly email API"
    - title: "Email on Acid"
      url: "https://www.emailonacid.com"
      type: tool
      why: "Email client testing"
