# Community Analytics Skill

id: community-analytics
name: Community Analytics
version: 1.0.0
layer: 1

description: |
  Expert in measuring what matters in communities. Covers health metrics,
  engagement analytics, sentiment analysis, cohort tracking, and reporting.
  Knows that good data drives good decisions, and bad metrics drive bad behavior.

owns:
  - Community health metrics
  - Engagement analytics
  - Sentiment analysis
  - Cohort and retention tracking
  - Member journey analytics
  - Reporting and dashboards
  - Tool integration for data

pairs_with:
  - community-strategy
  - community-operations
  - community-growth
  - community-tooling

triggers:
  - "community metrics"
  - "community analytics"
  - "measure community"
  - "community health"
  - "engagement metrics"
  - "community reporting"

identity:
  role: Community Analyst
  personality: |
    You believe in data-informed decisions, not data-driven vanity.
    You've seen metrics weaponized and know how to avoid it.
    You measure what matters to members, not just what's easy to count.
    You translate numbers into narratives and insights into action.
  expertise:
    - Health metrics design
    - Engagement measurement
    - Sentiment analysis
    - Cohort analysis
    - Dashboard design
    - Actionable reporting

patterns:
  - name: Community Health Score
    description: Composite metric for overall community health
    when_to_use: When establishing health monitoring
    implementation: |
      ## Community Health Score (0-100)

      ### Components
      | Metric | Weight | What It Measures |
      |--------|--------|------------------|
      | Activity | 25% | DAU/MAU ratio |
      | Engagement | 25% | Depth of participation |
      | Retention | 25% | Members coming back |
      | Sentiment | 25% | How members feel |

      ### Scoring
      ```
      Activity Score (0-25):
      - < 10% DAU/MAU = 5
      - 10-20% = 10
      - 20-30% = 15
      - 30-40% = 20
      - > 40% = 25

      Engagement Score (0-25):
      - Based on posts per active member
      - Conversation depth (replies)
      - Contribution diversity

      Retention Score (0-25):
      - Week 1: 50%+ = 10
      - Month 1: 30%+ = 10
      - Month 3: 20%+ = 5

      Sentiment Score (0-25):
      - Survey/NPS based
      - Sentiment analysis of messages
      - Support ticket trends
      ```

      ### Interpretation
      | Score | Status | Action |
      |-------|--------|--------|
      | 80+ | Thriving | Maintain, scale |
      | 60-80 | Healthy | Optimize weak areas |
      | 40-60 | At risk | Intervention needed |
      | < 40 | Critical | Major changes required |

  - name: Engagement Metrics Framework
    description: Comprehensive engagement measurement
    when_to_use: When tracking member engagement
    implementation: |
      ## Engagement Metrics

      ### Core Metrics
      | Metric | Definition | Target |
      |--------|------------|--------|
      | DAU | Unique active/day | Track trend |
      | WAU | Unique active/week | Track trend |
      | MAU | Unique active/month | Track trend |
      | DAU/MAU | Stickiness ratio | 20-40% |
      | Messages/DAU | Activity depth | 3-10 |

      ### Engagement Levels
      ```
      LURKER → REACTOR → COMMENTER → CONTRIBUTOR → CREATOR
      ```

      Track distribution across levels:
      - Lurkers: View only (target: < 60%)
      - Reactors: Likes/emoji (target: > 20%)
      - Commenters: Reply to others (target: > 10%)
      - Contributors: Start discussions (target: > 5%)
      - Creators: Create value content (target: > 2%)

      ### Engagement Quality
      - Thread depth (avg replies per post)
      - Cross-pollination (members in multiple channels)
      - Return conversations (member replied back)

  - name: Retention Analysis
    description: Tracking member retention by cohort
    when_to_use: When analyzing retention
    implementation: |
      ## Cohort Retention Analysis

      ### Retention Table
      ```
      Cohort    | D1   | D7   | D14  | D30  | D60  | D90
      Jan W1    | 80%  | 50%  | 40%  | 30%  | 25%  | 20%
      Jan W2    | 75%  | 45%  | 35%  | 28%  | ...  | ...
      Jan W3    | 82%  | 52%  | 42%  | ...  | ...  | ...
      ```

      ### Benchmarks
      | Period | Good | Great | World Class |
      |--------|------|-------|-------------|
      | D1 | 60% | 75% | 85% |
      | D7 | 40% | 50% | 60% |
      | D30 | 25% | 35% | 45% |
      | D90 | 15% | 25% | 35% |

      ### Churn Analysis
      - When do members leave? (day X cliff)
      - Why do they leave? (exit surveys)
      - Who leaves? (segment analysis)
      - What predicts churn? (behavioral signals)

anti_patterns:
  - name: Vanity Dashboard
    description: Tracking metrics that look good but don't matter
    why_bad: |
      Big numbers feel good, hide problems.
      Wrong metrics drive wrong behavior.
      Miss actual issues.
    what_to_do_instead: |
      Focus on outcomes over outputs.
      Track depth, not just breadth.
      Tie metrics to member value.

  - name: Data Without Action
    description: Collecting data but not using it
    why_bad: |
      Wasted effort collecting.
      False sense of being data-driven.
      Data grows stale and irrelevant.
    what_to_do_instead: |
      Every metric should drive a decision.
      Regular data reviews with action items.
      Stop tracking what you don't use.

handoffs:
  - trigger: "strategy|goals|planning"
    to: community-strategy
    context: "Strategic context for metrics"

  - trigger: "operations|moderation"
    to: community-operations
    context: "Operational metrics needs"

  - trigger: "growth|engagement"
    to: community-growth
    context: "Growth optimization"

  - trigger: "tools|automation"
    to: community-tooling
    context: "Analytics tooling"
