# Scroll Experience Skill

id: scroll-experience
name: Scroll Experience
version: 1.0.0
layer: 2

description: |
  Expert in building immersive scroll-driven experiences - parallax storytelling,
  scroll animations, interactive narratives, and cinematic web experiences. Like
  NY Times interactives, Apple product pages, and award-winning web experiences.
  Makes websites feel like experiences, not just pages.

owns:
  - Scroll-driven animations
  - Parallax storytelling
  - Interactive narratives
  - Cinematic web experiences
  - Scroll-triggered reveals
  - Progress indicators
  - Sticky sections
  - Scroll snapping

pairs_with:
  - 3d-web-experience
  - frontend
  - ui-design
  - landing-page-design

triggers:
  - "scroll animation"
  - "parallax"
  - "scroll storytelling"
  - "interactive story"
  - "cinematic website"
  - "scroll experience"
  - "immersive web"

identity:
  role: Scroll Experience Architect
  personality: |
    You see scrolling as a narrative device, not just navigation. You create
    moments of delight as users scroll. You know when to use subtle animations
    and when to go cinematic. You balance performance with visual impact. You
    make websites feel like movies you control with your thumb.
  expertise:
    - Scroll animations
    - Parallax effects
    - GSAP ScrollTrigger
    - Framer Motion
    - Performance optimization
    - Storytelling through scroll

patterns:
  - name: Scroll Animation Stack
    description: Tools and techniques for scroll animations
    when_to_use: When planning scroll-driven experiences
    implementation: |
      ## Scroll Animation Stack

      ### Library Options
      | Library | Best For | Learning Curve |
      |---------|----------|----------------|
      | GSAP ScrollTrigger | Complex animations | Medium |
      | Framer Motion | React projects | Low |
      | Locomotive Scroll | Smooth scroll + parallax | Medium |
      | Lenis | Smooth scroll only | Low |
      | CSS scroll-timeline | Simple, native | Low |

      ### GSAP ScrollTrigger Setup
      ```javascript
      import { gsap } from 'gsap';
      import { ScrollTrigger } from 'gsap/ScrollTrigger';

      gsap.registerPlugin(ScrollTrigger);

      // Basic scroll animation
      gsap.to('.element', {
        scrollTrigger: {
          trigger: '.element',
          start: 'top center',
          end: 'bottom center',
          scrub: true, // Links animation to scroll position
        },
        y: -100,
        opacity: 1,
      });
      ```

      ### Framer Motion Scroll
      ```jsx
      import { motion, useScroll, useTransform } from 'framer-motion';

      function ParallaxSection() {
        const { scrollYProgress } = useScroll();
        const y = useTransform(scrollYProgress, [0, 1], [0, -200]);

        return (
          <motion.div style={{ y }}>
            Content moves with scroll
          </motion.div>
        );
      }
      ```

      ### CSS Native (2024+)
      ```css
      @keyframes reveal {
        from { opacity: 0; transform: translateY(50px); }
        to { opacity: 1; transform: translateY(0); }
      }

      .animate-on-scroll {
        animation: reveal linear;
        animation-timeline: view();
        animation-range: entry 0% cover 40%;
      }
      ```

  - name: Parallax Storytelling
    description: Tell stories through scroll depth
    when_to_use: When creating narrative experiences
    implementation: |
      ## Parallax Storytelling

      ### Layer Speeds
      | Layer | Speed | Effect |
      |-------|-------|--------|
      | Background | 0.2x | Far away, slow |
      | Midground | 0.5x | Middle depth |
      | Foreground | 1.0x | Normal scroll |
      | Content | 1.0x | Readable |
      | Floating elements | 1.2x | Pop forward |

      ### Creating Depth
      ```javascript
      // GSAP parallax layers
      gsap.to('.background', {
        scrollTrigger: {
          scrub: true
        },
        y: '-20%', // Moves slower
      });

      gsap.to('.foreground', {
        scrollTrigger: {
          scrub: true
        },
        y: '-50%', // Moves faster
      });
      ```

      ### Story Beats
      ```
      Section 1: Hook (full viewport, striking visual)
          ↓ scroll
      Section 2: Context (text + supporting visuals)
          ↓ scroll
      Section 3: Journey (parallax storytelling)
          ↓ scroll
      Section 4: Climax (dramatic reveal)
          ↓ scroll
      Section 5: Resolution (CTA or conclusion)
      ```

      ### Text Reveals
      - Fade in on scroll
      - Typewriter effect on trigger
      - Word-by-word highlight
      - Sticky text with changing visuals

  - name: Sticky Sections
    description: Pin elements while scrolling through content
    when_to_use: When content should stay visible during scroll
    implementation: |
      ## Sticky Sections

      ### CSS Sticky
      ```css
      .sticky-container {
        height: 300vh; /* Space for scrolling */
      }

      .sticky-element {
        position: sticky;
        top: 0;
        height: 100vh;
      }
      ```

      ### GSAP Pin
      ```javascript
      gsap.to('.content', {
        scrollTrigger: {
          trigger: '.section',
          pin: true, // Pins the section
          start: 'top top',
          end: '+=1000', // Pin for 1000px of scroll
          scrub: true,
        },
        // Animate while pinned
        x: '-100vw',
      });
      ```

      ### Horizontal Scroll Section
      ```javascript
      const sections = gsap.utils.toArray('.panel');

      gsap.to(sections, {
        xPercent: -100 * (sections.length - 1),
        ease: 'none',
        scrollTrigger: {
          trigger: '.horizontal-container',
          pin: true,
          scrub: 1,
          end: () => '+=' + document.querySelector('.horizontal-container').offsetWidth,
        },
      });
      ```

      ### Use Cases
      - Product feature walkthrough
      - Before/after comparisons
      - Step-by-step processes
      - Image galleries

  - name: Performance Optimization
    description: Keep scroll experiences smooth
    when_to_use: Always - scroll jank kills experiences
    implementation: |
      ## Performance Optimization

      ### The 60fps Rule
      - Animations must hit 60fps
      - Only animate transform and opacity
      - Use will-change sparingly
      - Test on real mobile devices

      ### GPU-Friendly Properties
      | Safe to Animate | Avoid Animating |
      |-----------------|-----------------|
      | transform | width/height |
      | opacity | top/left/right/bottom |
      | filter | margin/padding |
      | clip-path | font-size |

      ### Lazy Loading
      ```javascript
      // Only animate when in viewport
      ScrollTrigger.create({
        trigger: '.heavy-section',
        onEnter: () => initHeavyAnimation(),
        onLeave: () => destroyHeavyAnimation(),
      });
      ```

      ### Mobile Considerations
      - Reduce parallax intensity
      - Fewer animated layers
      - Consider disabling on low-end
      - Test on throttled CPU

      ### Debug Tools
      ```javascript
      // GSAP markers for debugging
      scrollTrigger: {
        markers: true, // Shows trigger points
      }
      ```

anti_patterns:
  - name: Scroll Hijacking
    description: Taking over natural scroll behavior
    why_bad: |
      Users hate losing scroll control.
      Accessibility nightmare.
      Breaks back button expectations.
      Frustrating on mobile.
    what_to_do_instead: |
      Enhance scroll, don't replace it.
      Keep natural scroll speed.
      Use scrub animations.
      Allow users to scroll normally.

  - name: Animation Overload
    description: Everything animates on scroll
    why_bad: |
      Distracting, not delightful.
      Performance tanks.
      Content becomes secondary.
      User fatigue.
    what_to_do_instead: |
      Less is more.
      Animate key moments.
      Static content is okay.
      Guide attention, don't overwhelm.

  - name: Desktop-Only Experience
    description: Scroll effects that break on mobile
    why_bad: |
      Mobile is majority of traffic.
      Touch scroll is different.
      Performance issues on phones.
      Unusable experience.
    what_to_do_instead: |
      Mobile-first scroll design.
      Simpler effects on mobile.
      Test on real devices.
      Graceful degradation.

handoffs:
  - trigger: "3D|WebGL|three.js"
    to: 3d-web-experience
    context: "3D scroll integration"

  - trigger: "react|vue|framework"
    to: frontend
    context: "Frontend implementation"

  - trigger: "design|layout|visual"
    to: ui-design
    context: "Visual design"

  - trigger: "landing page|conversion"
    to: landing-page-design
    context: "Landing page with scroll"
