# Marketing Fundamentals Skill
# Core marketing principles for startups

id: marketing-fundamentals
name: Marketing Fundamentals
category: marketing
description: |
  Core marketing principles for startups. Covers positioning, messaging,
  channels, and growth. Focus on what works for resource-constrained teams.

triggers:
  - marketing strategy
  - positioning
  - messaging
  - customer acquisition
  - growth channels
  - brand
  - go-to-market

principles:
  - name: Positioning First
    description: |
      Before tactics, nail positioning. Who is it for? What category?
      How is it different? What is the proof? Positioning drives everything.
      Bad positioning cannot be fixed by better tactics.
    examples:
      - Define target customer precisely
      - Choose category strategically
      - Articulate differentiation clearly
      - Support claims with evidence

  - name: Do Things That Do Not Scale
    description: |
      Early marketing is manual. Handwritten emails. Personal outreach.
      One-on-one demos. Things that teach you about customers before
      scaling. Premature scaling wastes money on wrong messages.
    examples:
      - Personal outreach to first 100 customers
      - Manual onboarding to learn friction points
      - Direct conversations before surveys
      - Quality over quantity early

  - name: One Channel Deeply
    description: |
      Startups win by going deep on one channel, not shallow on many.
      Master one acquisition channel before diversifying. Most successful
      startups found one channel that worked and scaled it.
    examples:
      - Choose channel that matches audience behavior
      - Develop expertise before switching
      - Measure true CAC and LTV per channel
      - Scale what works before experimenting

  - name: Message Market Fit
    description: |
      The words you use matter as much as the product. Test messaging
      continuously. The right message can 10x conversion. Message market
      fit is as important as product market fit.
    examples:
      - Test headlines and value props
      - Use customer language not internal language
      - A/B test continuously
      - Measure comprehension not just clicks

  - name: Distribution is Product
    description: |
      How people find you is part of the product. Build distribution
      into the product itself. Viral loops, integrations, content,
      community. Distribution afterthought means distribution failure.
    examples:
      - Design sharing into product
      - Build where customers already are
      - Create content customers want to share
      - Make referrals natural not forced

anti_patterns:
  - name: Spray and Pray
    description: Trying every channel superficially instead of mastering one
    indicators:
      - Many channels, none working
      - No clear winner after months
      - Spreading budget thin
    instead: Pick one channel, go deep, measure properly

  - name: Brand Before Traction
    description: Investing in brand campaigns before product-market fit
    indicators:
      - Brand spend without conversion tracking
      - Awareness campaigns pre-PMF
      - Logo redesigns instead of customer research
    instead: Focus on direct response until PMF proven

  - name: Build It And They Will Come
    description: Assuming good product markets itself
    indicators:
      - No marketing plan
      - Waiting for organic growth
      - Product team doing marketing part-time
    instead: Marketing is day one, not after launch

  - name: Premature Scaling
    description: Scaling marketing before message and channel validated
    indicators:
      - High spend, low conversion
      - Scaling what has not been proven
      - Hiring before playbook
    instead: Prove unit economics at small scale first

  - name: Copying Competitors
    description: Using competitor tactics without understanding context
    indicators:
      - Same channels as competitors
      - Similar messaging
      - Following industry standard approach
    instead: Find your unique angle and channel

guidance:
  vibe-coder: |
    Marketing is how people find your product. Start with:
    1. Who exactly is this for? Be specific.
    2. What problem does it solve? In their words.
    3. Where do these people hang out online?
    4. What would make them want to share this?

    Do not spend money on ads yet. Start with personal outreach.
    Talk to potential customers. Learn their language. Use it.

  builder: |
    Focus on positioning first:
    1. Target customer: Who gets most value?
    2. Category: What bucket does this fit in?
    3. Differentiation: Why this over alternatives?
    4. Proof: What evidence supports claims?

    Pick ONE channel to master. Most startups find success in:
    - Content/SEO (long game, compounds)
    - Community (if your audience gathers)
    - Direct outreach (always works early)
    - Paid (if unit economics work)

  developer: |
    Technical founders: marketing is not optional or someone else job.

    Distribution > Product in most markets. Build marketing into product:
    - Shareable outputs (reports, badges, exports)
    - API/integrations where users are
    - Content that ranks for problems you solve
    - Community around the problem space

    Measure: CAC, LTV, payback period, channel efficiency.

  expert: |
    Marketing strategy checklist:

    Positioning:
    - April Dunford framework: competitive alternatives, unique attributes,
      value, customer segment, market category

    Channels (prioritize by):
    - Where does target customer spend attention?
    - What is the CAC ceiling given LTV?
    - What is defensible over time?

    Message testing:
    - Headlines: problem-focused vs solution-focused vs outcome-focused
    - Social proof: which type converts best?
    - CTA: what action, what friction?

    Scale only proven playbooks. Document everything.

handoff:
  before:
    - Ensure product has some initial users or validation
    - Know who the target customer is
  after:
    - Growth tracking and optimization
    - Channel expansion
  related_skills:
    - seo
    - viral-marketing
    - analytics

sources:
  - Obviously Awesome by April Dunford (positioning)
  - Traction by Gabriel Weinberg (channels)
  - Do Things That Dont Scale by Paul Graham
  - Zero to One chapter on distribution
