id: ground-station-ops
name: Ground Station Operations
category: space
version: 1.0.0
description: >
  Use when designing ground station networks, scheduling satellite contacts,
  processing telemetry, commanding spacecraft, or analyzing link budgets.

triggers:
  - "ground station"
  - "satellite contact"
  - "pass prediction"
  - "AOS"
  - "LOS"
  - "telemetry"
  - "commanding"
  - "uplink"
  - "downlink"
  - "antenna tracking"
  - "link budget"
  - "G/T"
  - "EIRP"

provides:
  - name: contact_scheduling
    description: Satellite pass prediction and scheduling
  - name: telemetry_processing
    description: Telemetry decommutation, calibration, and monitoring
  - name: command_management
    description: Command encoding, verification, and execution tracking
  - name: link_analysis
    description: Ground station link budget analysis

knowledge_base:
  ground_segment_architecture:
    components:
      antenna_system:
        description: "Tracks satellite, receives/transmits RF"
        types:
          - "Parabolic dish (3-13m typical)"
          - "Phased array"
          - "Flat panel"
        parameters:
          - "Diameter"
          - "Gain"
          - "G/T"
          - "Tracking rate"
      rf_frontend:
        components:
          - "Low Noise Amplifier (LNA)"
          - "High Power Amplifier (HPA)"
          - "Diplexer"
          - "Frequency converter"
      modem:
        functions:
          - "Modulation/demodulation"
          - "Error correction encoding/decoding"
          - "Bit/frame synchronization"
      station_computer:
        functions:
          - "Antenna control"
          - "Pass automation"
          - "Data routing"

  contact_scheduling:
    pass_parameters:
      AOS: "Acquisition of Signal - satellite rises above minimum elevation"
      LOS: "Loss of Signal - satellite drops below minimum elevation"
      TCA: "Time of Closest Approach - maximum elevation"
      duration: "LOS - AOS time"
      max_elevation: "Highest point in pass"
    typical_values:
      min_elevation: "5-10 degrees"
      leo_pass_duration: "5-15 minutes"
      passes_per_day: "4-6 for single station"
    scheduling_algorithm:
      priority_factors:
        - "Maximum elevation (higher = better link)"
        - "Pass duration"
        - "Satellite priority"
        - "Activity type requirements"
      conflict_resolution:
        - "Priority-based"
        - "Time-sharing if possible"
        - "Alternative station"

  telemetry_processing:
    ccsds_standards:
      packet_structure:
        - "Primary header (6 bytes)"
        - "Secondary header (optional)"
        - "User data"
        - "Error control"
      tm_transfer_frame:
        size: "Typically 1115 bytes"
        sync_marker: "1ACFFC1D (hex)"
    processing_levels:
      level_0: "Raw frames with sync"
      level_1: "Decommutated packets"
      level_2: "Calibrated engineering units"
      level_3: "Derived parameters"
    telemetry_point:
      definition:
        - "Mnemonic (short name)"
        - "Data type (int8, uint16, float32)"
        - "Byte/bit offset"
        - "Calibration (raw to engineering)"
        - "Limits (warning, critical)"
    limit_checking:
      status: "Nominal, Warning, Critical, Stale"
      actions:
        - "Alert operators"
        - "Trigger procedures"
        - "Auto-safing"

  commanding:
    command_types:
      realtime: "Execute immediately upon receipt"
      time_tagged: "Execute at specified time"
      stored_sequence: "Part of on-board sequence"
    verification:
      levels:
        - "Command echo (received correctly)"
        - "Execution acknowledgment"
        - "Effect verification (telemetry change)"
    authorization:
      criticality_levels: "1-5 (5 = most critical)"
      two_person_rule: "Required for hazardous commands"
      audit_trail: "All commands logged"
    command_constraints:
      - "Spacecraft state prerequisites"
      - "Timing constraints"
      - "Mutual exclusion"

  link_analysis:
    parameters:
      eirp: "Effective Isotropic Radiated Power (dBW)"
      g_over_t: "Antenna figure of merit (dB/K)"
      path_loss: "20*log10(4*pi*d/lambda)"
      atmospheric_loss: "Increases at low elevation"
      eb_n0: "Energy per bit to noise density"
    link_closure:
      required_margin: "3 dB typical"
      check: "Eb/N0_achieved > Eb/N0_required + margin"
    data_volume:
      calculation: "Rate * time * overhead_factor"
      planning: "Match to mission data generation"

patterns:
  - name: pass_operations
    steps:
      - "Pre-pass configuration (30 min before)"
      - "Antenna acquisition (at AOS)"
      - "Two-way link establishment"
      - "Execute contact plan"
      - "Real-time monitoring"
      - "Post-pass data processing"
      - "Quick-look report"

  - name: telemetry_database_setup
    steps:
      - "Define all telemetry points"
      - "Specify calibrations"
      - "Set limit thresholds"
      - "Configure displays"
      - "Test with known data"
      - "Validate against specification"

  - name: command_procedure
    steps:
      - "Select command from database"
      - "Enter parameters"
      - "Verify against constraints"
      - "Authorize (1 or 2 person)"
      - "Uplink"
      - "Verify echo"
      - "Confirm execution"
      - "Log outcome"

anti_patterns:
  - name: single_ground_station
    problem: "Limited contact time per day"
    solution: "Network of geographically distributed stations"
  - name: no_command_verification
    problem: "Erroneous commands sent without detection"
    solution: "Mandatory echo check and authorization"
  - name: ignoring_weather
    problem: "Rain fade causes link dropout"
    solution: "Weather monitoring and adaptive scheduling"
  - name: no_telemetry_archive
    problem: "Historical data lost"
    solution: "Permanent archive with retrieval capability"
  - name: manual_scheduling
    problem: "Human error and inefficiency"
    solution: "Automated scheduling with conflict resolution"

checklist:
  station_configuration:
    - "Antenna systems calibrated"
    - "Frequency coordination complete"
    - "Network connectivity tested"
    - "Backup power available"
  operations_readiness:
    - "Pass predictions generated"
    - "Contact schedule published"
    - "Telemetry definitions loaded"
    - "Command database verified"
  each_contact:
    - "Pre-pass checklist complete"
    - "Antenna tracking verified"
    - "Link margin acceptable"
    - "Telemetry flowing"
    - "Commands verified before uplink"
    - "Post-pass data archived"
