# Pivot Patterns Skill
# Changing direction without losing momentum

id: pivot-patterns
name: Pivot Patterns
category: strategy
version: 1.0.0
last_updated: 2025-12-19

description: |
  Most successful startups pivoted. Instagram was a check-in app. Slack was
  a game. YouTube was a dating site. The ability to recognize when to pivot
  and execute the pivot without losing momentum is a core founder skill.

  This skill covers pivot signals, types of pivots, preserving momentum during
  change, and communicating pivots to investors and team.

triggers:
  keywords:
    - pivot
    - direction change
    - product market fit
    - not working
    - change strategy
    - new direction
    - repositioning
    - iteration
  contexts:
    - Evaluating whether to pivot
    - Executing a pivot
    - Communicating change to stakeholders

principles:
  - name: Pivot from learning, not frustration
    description: |
      Pivoting because things are hard is wrong. Pivoting because you learned
      something is right. Every pivot should be backed by evidence, not emotions.
    examples:
      good: After 100 user interviews, clear pattern shows different problem worth solving
      bad: Growth is slow, lets try something else this week

  - name: Preserve what works
    description: |
      Good pivots keep something - the team, the technology, the insight, the
      customers. Full restarts are rarely necessary. Find what to keep.
    examples:
      good: Pivot from consumer to B2B keeping core tech and team
      bad: Throw everything away and start completely fresh

  - name: Speed matters more than certainty
    description: |
      Once you decide to pivot, execute fast. Analysis paralysis during pivots
      burns runway without learning. Commit and move.
    examples:
      good: Decision made Monday, new landing page Wednesday, outreach Friday
      bad: Three months debating which pivot direction

  - name: Communicate with conviction
    description: |
      Pivots create uncertainty. Leadership requires projecting confidence even
      when uncertain. Share the learning that drove the pivot. Own the decision.
    examples:
      good: We learned X, which means Y is a bigger opportunity. Here is the plan.
      bad: I guess the last thing was not working so we are trying this now

  - name: One pivot at a time
    description: |
      Change one variable at a time. Market, product, or business model. Changing
      everything at once makes learning impossible.
    examples:
      good: Keep same customers, new product
      bad: New customers, new product, new business model simultaneously

anti_patterns:
  - name: Pivot addiction
    description: Constantly changing direction before learning
    example: New idea every few weeks, never committing long enough to learn
    why_bad: Thrashing without progress. Team whiplash. No deep learning.
    fix: Minimum commitment periods. 6-8 weeks before evaluating.

  - name: Ignoring signals
    description: Persisting despite clear evidence it is not working
    example: 200 user interviews saying no, still building the same thing
    why_bad: Hope is not a strategy. Evidence matters. Runway burns.
    fix: Define upfront what evidence would trigger pivot consideration.

  - name: Stealth pivot
    description: Pivoting without communicating to investors or team
    example: Quietly building something different, hoping no one notices
    why_bad: Trust destroyed when discovered. Misalignment compounds.
    fix: Proactive communication. Share learning and reasoning.

  - name: Pivot as blame
    description: Blaming the market or idea instead of learning from it
    example: That market was bad, this new market will be better
    why_bad: Same mistakes in new market. No actual learning.
    fix: Extract learnings. What did we get wrong? What will we do differently?

  - name: Keeping the wrong people
    description: Pivoting strategy but keeping team misaligned with new direction
    example: Pivoting to B2B but keeping consumer-focused team
    why_bad: Culture and skill mismatch. Slow execution. Resentment.
    fix: Honest assessment of team fit. Hard conversations early.

frameworks:
  - name: Types of Pivots
    when_to_use: Understanding pivot options
    structure:
      - "Zoom-in: One feature becomes the product"
      - "Zoom-out: Product becomes one feature of bigger product"
      - "Customer segment: Same product, different customer"
      - "Customer need: Same customer, different need"
      - "Platform: Product becomes platform"
      - "Business model: Same product, different monetization"
      - "Channel: Same product, different go-to-market"
      - "Technology: Same value prop, different technology"

  - name: Pivot Decision Framework
    when_to_use: Deciding whether to pivot
    structure:
      - "Have you talked to 50+ users about the problem?"
      - "Is there a clear pattern in why it is not working?"
      - "Did you discover a better opportunity during research?"
      - "Do you have sufficient runway to execute a pivot?"
      - "Is the team aligned on the need to change?"
    notes: Need strong yes on most to justify pivot

  - name: Pivot Execution Checklist
    when_to_use: Executing a pivot decision
    structure:
      - "Document learnings from previous direction"
      - "Define hypothesis for new direction"
      - "Communicate to team with conviction"
      - "Update investors with learning story"
      - "Adjust hiring and priorities"
      - "Set clear milestones for new direction"
      - "Preserve assets and relationships that transfer"

  - name: Investor Communication Template
    when_to_use: Telling investors about pivot
    structure:
      - "What we learned: The data and insights that changed our view"
      - "The opportunity: Why new direction is bigger or better"
      - "What transfers: Team, tech, insights we are keeping"
      - "The plan: Milestones and timeline for new direction"
      - "The ask: What support we need from investors"

handoffs:
  receives_from:
    - skill: idea-maze
      receives: Understanding of what makes a good idea
    - skill: talk-to-users
      receives: User research insights

  hands_to:
    - skill: early-stage-hustle
      provides: New direction to execute on
    - skill: product-strategy
      provides: Revised product vision

resources:
  essential:
    - title: The Lean Startup
      author: Eric Ries
      type: book
      why: Original framework for validated learning and pivots

  recommended:
    - title: Pivot Stories on YC Blog
      url: https://www.ycombinator.com/blog
      type: resource
      why: Real pivot stories from successful companies
