# Pivot Patterns Skill
# Changing direction without losing momentum

id: pivot-patterns
name: Pivot Patterns
category: strategy
version: 1.0.0
last_updated: 2025-12-19

description: |
  Most successful startups pivoted. Instagram was a check-in app. Slack was
  a game. YouTube was a dating site. The ability to recognize when to pivot
  and execute the pivot without losing momentum is a core founder skill.

  This skill covers pivot signals, types of pivots, preserving momentum during
  change, and communicating pivots to investors and team.

triggers:
  keywords:
    - pivot
    - direction change
    - product market fit
    - not working
    - change strategy
    - new direction
    - repositioning
    - iteration
  contexts:
    - Evaluating whether to pivot
    - Executing a pivot
    - Communicating change to stakeholders

principles:
  - name: Pivot from learning, not frustration
    description: |
      Pivoting because things are hard is wrong. Pivoting because you learned
      something is right. Every pivot should be backed by evidence, not emotions.
    examples:
      good: After 100 user interviews, clear pattern shows different problem worth solving
      bad: Growth is slow, lets try something else this week

  - name: Preserve what works
    description: |
      Good pivots keep something - the team, the technology, the insight, the
      customers. Full restarts are rarely necessary. Find what to keep.
    examples:
      good: Pivot from consumer to B2B keeping core tech and team
      bad: Throw everything away and start completely fresh

  - name: Speed matters more than certainty
    description: |
      Once you decide to pivot, execute fast. Analysis paralysis during pivots
      burns runway without learning. Commit and move.
    examples:
      good: Decision made Monday, new landing page Wednesday, outreach Friday
      bad: Three months debating which pivot direction

  - name: Communicate with conviction
    description: |
      Pivots create uncertainty. Leadership requires projecting confidence even
      when uncertain. Share the learning that drove the pivot. Own the decision.
    examples:
      good: We learned X, which means Y is a bigger opportunity. Here is the plan.
      bad: I guess the last thing was not working so we are trying this now

  - name: One pivot at a time
    description: |
      Change one variable at a time. Market, product, or business model. Changing
      everything at once makes learning impossible.
    examples:
      good: Keep same customers, new product
      bad: New customers, new product, new business model simultaneously

anti_patterns:
  - name: Pivot addiction
    description: Constantly changing direction before learning
    example: New idea every few weeks, never committing long enough to learn
    why_bad: Thrashing without progress. Team whiplash. No deep learning.
    fix: Minimum commitment periods. 6-8 weeks before evaluating.

  - name: Ignoring signals
    description: Persisting despite clear evidence it is not working
    example: 200 user interviews saying no, still building the same thing
    why_bad: Hope is not a strategy. Evidence matters. Runway burns.
    fix: Define upfront what evidence would trigger pivot consideration.

  - name: Stealth pivot
    description: Pivoting without communicating to investors or team
    example: Quietly building something different, hoping no one notices
    why_bad: Trust destroyed when discovered. Misalignment compounds.
    fix: Proactive communication. Share learning and reasoning.

  - name: Pivot as blame
    description: Blaming the market or idea instead of learning from it
    example: That market was bad, this new market will be better
    why_bad: Same mistakes in new market. No actual learning.
    fix: Extract learnings. What did we get wrong? What will we do differently?

  - name: Keeping the wrong people
    description: Pivoting strategy but keeping team misaligned with new direction
    example: Pivoting to B2B but keeping consumer-focused team
    why_bad: Culture and skill mismatch. Slow execution. Resentment.
    fix: Honest assessment of team fit. Hard conversations early.

  - name: Pivot Addiction
    description: Constantly changing direction before learning anything
    why: Thrashing without progress. Team whiplash. No depth. No moat.
    instead: Minimum 6-8 week commitment before evaluating. Let learning accumulate.

  - name: Ignoring Evidence
    description: Persisting despite overwhelming signals it's not working
    why: Hope is not a strategy. Evidence matters. Runway burns while you deny reality.
    instead: Define upfront what evidence would trigger pivot consideration. Honor it.

  - name: Stealth Pivot
    description: Pivoting without communicating to investors or team
    why: Trust destroyed when discovered. Misalignment compounds. Support evaporates.
    instead: Proactive communication. Share the learning. Bring people along.

  - name: Blame Pivot
    description: Blaming market or idea instead of extracting learnings
    why: Same mistakes in new market. No actual growth. Pattern repeats.
    instead: What did we learn? What will we do differently? Show the evolution.

  - name: Complete Restart
    description: Throwing everything away instead of preserving assets
    why: Wastes accumulated value. Demoralizes team. Starts from zero.
    instead: Identify what's working. Keep team, tech, relationships, insights. Build on them.

  - name: Multi-Variable Pivot
    description: Changing customer, product, and business model simultaneously
    why: Impossible to learn what worked or didn't. Too many variables.
    instead: Change one thing at a time. Test. Learn. Then change next variable.

patterns:
  - name: Learning-Driven Pivot
    description: Pivot based on accumulated evidence and user insights, not frustration
    when: Data shows clear pattern indicating different opportunity
    example: |
      After 100 user interviews, consistent pattern emerges: they need X not Y
      Instagram: Check-in app → Photo filters (users only used photos)
      YouTube: Dating site → Video sharing (people just shared videos)
      Evidence accumulates. Pattern becomes clear. Pivot with conviction.

  - name: Preserve the Asset
    description: Keep what's working (team, tech, customers, insight) while changing what's not
    when: Executing any pivot to maintain momentum
    example: |
      Slack: Game failed, but team communication tool worked → Kept tech, changed market
      Twitter: Podcasting platform failed → Kept status update feature, dropped rest
      What do you have that's valuable? Build the pivot around it.

  - name: Zoom-In Pivot
    description: Make one successful feature into the entire product
    when: One feature shows significantly stronger engagement than others
    example: |
      Instagram: Photo filters in check-in app → Just filters
      Burbn had check-in, photos, points → Pivoted to just photo sharing
      What do users actually use? Make that the whole product.

  - name: Customer Segment Pivot
    description: Keep the product, change who you sell it to
    when: Wrong customer segment but right solution
    example: |
      Slack: Built for gamers → Sold to businesses
      Yammer: Built for company-wide → Sold to teams
      Who has the money and pain? Go there, even if it wasn't your original plan.

  - name: Speed Over Certainty
    description: Once pivot decision is made, execute fast and learn quickly
    when: Pivot decision has been made with sufficient evidence
    example: |
      Decision Monday → New landing page Wednesday → User outreach Friday
      Indecision burns runway. Make the call. Move fast. Learn.
      Perfect pivot plan doesn't exist. Good enough plan executed fast wins.

  - name: Narrative Control
    description: Frame the pivot as evolution based on learning, not failure
    when: Communicating pivot to team, investors, and users
    example: |
      "We learned X, which led us to discover Y is the bigger opportunity"
      Not: "The last thing didn't work so we're trying this now"
      Own the narrative. Show the learning. Demonstrate momentum.

frameworks:
  - name: Types of Pivots
    when_to_use: Understanding pivot options
    structure:
      - "Zoom-in: One feature becomes the product"
      - "Zoom-out: Product becomes one feature of bigger product"
      - "Customer segment: Same product, different customer"
      - "Customer need: Same customer, different need"
      - "Platform: Product becomes platform"
      - "Business model: Same product, different monetization"
      - "Channel: Same product, different go-to-market"
      - "Technology: Same value prop, different technology"

  - name: Pivot Decision Framework
    when_to_use: Deciding whether to pivot
    structure:
      - "Have you talked to 50+ users about the problem?"
      - "Is there a clear pattern in why it is not working?"
      - "Did you discover a better opportunity during research?"
      - "Do you have sufficient runway to execute a pivot?"
      - "Is the team aligned on the need to change?"
    notes: Need strong yes on most to justify pivot

  - name: Pivot Execution Checklist
    when_to_use: Executing a pivot decision
    structure:
      - "Document learnings from previous direction"
      - "Define hypothesis for new direction"
      - "Communicate to team with conviction"
      - "Update investors with learning story"
      - "Adjust hiring and priorities"
      - "Set clear milestones for new direction"
      - "Preserve assets and relationships that transfer"

  - name: Investor Communication Template
    when_to_use: Telling investors about pivot
    structure:
      - "What we learned: The data and insights that changed our view"
      - "The opportunity: Why new direction is bigger or better"
      - "What transfers: Team, tech, insights we are keeping"
      - "The plan: Milestones and timeline for new direction"
      - "The ask: What support we need from investors"

handoffs:
  receives_from:
    - skill: idea-maze
      receives: Understanding of what makes a good idea
    - skill: talk-to-users
      receives: User research insights

  hands_to:
    - skill: early-stage-hustle
      provides: New direction to execute on
    - skill: product-strategy
      provides: Revised product vision

resources:
  essential:
    - title: The Lean Startup
      author: Eric Ries
      type: book
      why: Original framework for validated learning and pivots

  recommended:
    - title: Pivot Stories on YC Blog
      url: https://www.ycombinator.com/blog
      type: resource
      why: Real pivot stories from successful companies
