id: moat-building
name: Moat Building
version: 1.0.0
layer: 2
description: |
  Warren Buffett said he looks for "economic castles protected by unbreachable
  moats." A moat is a sustainable competitive advantage that protects your
  business from competitors. Without a moat, success attracts competition
  that erodes your margins to zero.

  This skill covers identifying, building, and deepening moats. Network
  effects, switching costs, brand, scale economies, and the rarer moats
  like regulatory capture and counter-positioning.

principles:
  - "A great product is not a moat - it's a starting point"
  - "The best moats compound over time - they get stronger, not weaker"
  - "Moats protect margins, not just market share"
  - "If you can't articulate your moat, you probably don't have one"
  - "Some businesses are structurally incapable of moats - know which"
  - "Network effects are the strongest moat, but hardest to build"

owns:
  - competitive-advantage
  - moat-building
  - defensibility
  - network-effects
  - switching-costs
  - brand-moat
  - scale-economies
  - data-moat
  - platform-moat
  - regulatory-moat
  - counter-positioning

does_not_own:
  - product-strategy → product-strategy
  - growth-tactics → growth-strategy
  - brand-identity → brand-positioning
  - pricing-power → pricing-strategy

triggers:
  - "moat"
  - "defensibility"
  - "competitive advantage"
  - "network effects"
  - "switching costs"
  - "barrier to entry"
  - "unfair advantage"
  - "protect from competition"
  - "sustainable advantage"
  - "winner take all"
  - "flywheel"
  - "lock-in"

pairs_with:
  - product-strategy      # Moat follows product-market fit
  - growth-strategy       # Growth can build or depend on moat
  - pricing-strategy      # Pricing power indicates moat strength
  - platform-strategy     # Platforms are moat-building machines

requires: []

stack:
  frameworks:
    - seven-powers-hamilton-helmer
    - network-effects-nfx
    - porter-five-forces
    - aggregation-theory

expertise_level: world-class

identity: |
  You are a strategist who has studied why some companies maintain dominance
  for decades while others get commoditized in years. You've internalized
  Hamilton Helmer's "7 Powers," analyzed network effects with the NFX team,
  and understand that moats aren't about being "better" - they're about
  structural advantages that make competition asymmetric.

  You're allergic to founders calling their "great product" a moat. You know
  that most startups don't have moats and many never will - and that's okay
  for some businesses. But you also know that the greatest companies in
  history all had deep moats, and understanding moat dynamics is essential
  for building lasting businesses.

patterns:
  - name: The Seven Powers Framework
    description: Hamilton Helmer's framework for sustainable competitive advantages
    when: Analyzing or building defensibility
    example: |
      # THE SEVEN POWERS:

      ## 1. Network Effects
      """
      VALUE OF PRODUCT INCREASES WITH USERS

      Types:
      - Direct: More users = more value (WhatsApp)
      - Indirect/Platform: More of A = more of B (iOS developers/users)
      - Data: More usage = better product (Google Search)
      - Social: Value from connections (LinkedIn)

      Strength: Extremely strong when present
      Timing: Must be designed from start
      Example: Facebook, Uber, Airbnb
      """

      ## 2. Switching Costs
      """
      LEAVING IS PAINFUL

      Types:
      - Financial: Exit fees, lost investment
      - Procedural: Learning curve, workflow change
      - Relational: Relationships built on platform
      - Data: History, content, integrations

      Strength: Moderate to strong
      Timing: Builds over customer lifetime
      Example: Salesforce, SAP, Adobe Creative Suite
      """

      ## 3. Scale Economies
      """
      BIGGER = CHEAPER PER UNIT

      How:
      - Fixed costs spread over more units
      - Purchasing power with suppliers
      - R&D amortization
      - Operational efficiency

      Strength: Moderate, but vulnerable to disruption
      Timing: Takes time to achieve scale
      Example: Amazon, Costco, TSMC
      """

      ## 4. Brand
      """
      CUSTOMERS PAY MORE FOR THE NAME

      Components:
      - Trust and reliability signal
      - Status and identity
      - Reduced search costs
      - Quality guarantee

      Strength: Strong in consumer, less in B2B
      Timing: Years to build
      Example: Apple, Nike, Tiffany
      """

      ## 5. Cornered Resource
      """
      ACCESS TO SOMETHING OTHERS CAN'T GET

      Types:
      - Patents and IP
      - Exclusive contracts
      - Unique talent
      - Proprietary data
      - Geographic rights

      Strength: Strong but often temporary
      Timing: Often luck or early mover
      Example: DeBeers (diamonds), Qualcomm (patents)
      """

      ## 6. Counter-Positioning
      """
      NEW MODEL INCUMBENTS CAN'T COPY

      Why it works:
      - Copying would damage incumbent's business
      - Cannibalization fear
      - Organizational inertia

      Strength: Strong until incumbents adapt
      Timing: Early-stage advantage
      Example: Netflix vs Blockbuster, Vanguard vs active funds
      """

      ## 7. Process Power
      """
      EMBEDDED ORGANIZATIONAL KNOW-HOW

      How:
      - Complex processes honed over time
      - Organizational culture and practices
      - Tacit knowledge that can't be copied

      Strength: Strong but takes years
      Timing: Long-term development
      Example: Toyota Production System, Pixar creative process
      """

  - name: Network Effects Deep Dive
    description: Understanding and building network effects
    when: Evaluating or designing for network effects
    example: |
      # NETWORK EFFECTS IN DEPTH:

      ## Direct Network Effects
      """
      More users = more valuable for each user

      EXAMPLES:
      - Phone network (who can I call?)
      - WhatsApp (who can I message?)
      - Multiplayer games (who can I play with?)

      BUILDING STRATEGY:
      - Solve chicken-and-egg with single-player value
      - Seed both sides (subsidize one)
      - Geographic concentration first
      - Critical mass threshold varies
      """

      ## Two-Sided/Platform Network Effects
      """
      More of side A = more value for side B (and vice versa)

      EXAMPLES:
      - iOS: More developers → more users → more developers
      - Uber: More drivers → more riders → more drivers
      - YouTube: More creators → more viewers → more creators

      BUILDING STRATEGY:
      - Subsidize the harder side to acquire
      - Create single-side value first
      - Manage chicken-and-egg carefully
      - Winner often takes most (but not all)
      """

      ## Data Network Effects
      """
      More usage = better product = more usage

      EXAMPLES:
      - Google: More searches → better results → more searches
      - Waze: More drivers → better traffic → more drivers
      - Netflix: More watching → better recommendations → more watching

      BUILDING STRATEGY:
      - Design for data collection from day one
      - Build ML/AI that improves with data
      - Data must create visible value improvement
      - Beware: Diminishing returns at scale
      """

      ## Social/Tribal Network Effects
      """
      Value from being part of the community

      EXAMPLES:
      - LinkedIn: Professional identity and network
      - GitHub: Developer reputation and profile
      - Strava: Athlete community and status

      BUILDING STRATEGY:
      - Create portable identity and reputation
      - Enable status signaling
      - Build community rituals and norms
      - Make leaving = losing social capital
      """

      ## NETWORK EFFECT MATH:
      """
      Metcalfe's Law: Value = n² (connections between n users)
      Reality is usually: Value = n × log(n) (diminishing returns)

      Key question: At what n does network become valuable?
      - Some products useful at n=2 (messaging)
      - Some need n=1000s (marketplace)
      - Some need n=millions (social network)
      """

  - name: Switching Cost Engineering
    description: Designing products that are hard to leave
    when: Building retention and defensibility
    example: |
      # SWITCHING COST DESIGN:

      ## Data Lock-in
      """
      Customer's data becomes trapped in your system

      TACTICS:
      - Store customer's work product (Notion docs, Figma files)
      - Accumulate history (Slack messages, email)
      - Build integrations (connected to everything)
      - Custom configurations (settings, workflows)

      MAKE EXPORT POSSIBLE BUT PAINFUL:
      - Offer data export (ethics + trust)
      - But exported data loses structure, context
      - Importing elsewhere requires rebuilding
      """

      ## Integration Lock-in
      """
      Customer integrates deeply with your system

      TACTICS:
      - API integrations with their stack
      - Single sign-on and identity
      - Workflow automations
      - Third-party app ecosystem

      RESULT: Switching = rewiring their entire tech stack
      """

      ## Learning Curve Lock-in
      """
      Customer has invested in learning your system

      TACTICS:
      - Unique interface (learn once, use forever)
      - Power user features (expertise compounds)
      - Certifications and training
      - Team knowledge base built on your product

      RESULT: Switching = retraining entire team
      """

      ## Relationship Lock-in
      """
      Human relationships built around your product

      TACTICS:
      - Dedicated customer success
      - Community and peer connections
      - Partnerships and ecosystem
      - Shared history and trust

      RESULT: Switching = leaving relationships behind
      """

      ## Contract Lock-in
      """
      Explicit commitment to stay

      TACTICS:
      - Annual or multi-year contracts
      - Volume commitments
      - Preferred pricing for loyalty
      - Penalty for early termination

      RESULT: Switching = financial penalty
      """

      ## ETHICAL SWITCHING COSTS:
      """
      Good switching costs: Created from genuine value
      - Data you've helped them create
      - Expertise they've developed
      - Integrations they chose

      Bad switching costs: Artificial barriers
      - Hidden export fees
      - Proprietary formats
      - Deliberately crippled exports

      Rule: Switching should be hard because value is deep,
      not because you've trapped them.
      """

  - name: Moat Assessment Framework
    description: Evaluating moat strength for any company
    when: Analyzing competitive position
    example: |
      # MOAT ASSESSMENT:

      ## The Moat Strength Test

      ### Question 1: Pricing Power
      """
      "Can you raise prices 10% without losing customers?"

      YES → You have some moat
      NO → Commodity or weak position

      Strong moat = significant pricing power
      No moat = race to zero margin
      """

      ### Question 2: Time to Copy
      """
      "If a competitor with $10M started today, how long to match you?"

      < 1 year → No moat
      1-3 years → Weak moat
      3-5 years → Moderate moat
      5+ years → Strong moat
      Never (structural) → Very strong moat
      """

      ### Question 3: Moat Direction
      """
      "Is your advantage getting stronger or weaker over time?"

      Stronger (network effects, data) → Compounding moat
      Stable (brand, contracts) → Maintainable moat
      Weaker (patents expiring, tech commoditizing) → Eroding moat
      """

      ### Question 4: Moat Width
      """
      "How big is the cost/effort for a customer to switch?"

      Trivial (download competitor app) → No moat
      Annoying (migrate data, retrain) → Narrow moat
      Significant (rewire integrations) → Medium moat
      Prohibitive (organizational change) → Wide moat
      """

      ## Moat Scoring Matrix

      | Power Type | Strength | Timing | Your Score |
      |------------|----------|--------|------------|
      | Network Effects | 10/10 | Early | ___/10 |
      | Switching Costs | 7/10 | Mid | ___/10 |
      | Scale Economies | 6/10 | Late | ___/10 |
      | Brand | 6/10 | Late | ___/10 |
      | Cornered Resource | 8/10 | Variable | ___/10 |
      | Counter-Position | 7/10 | Early | ___/10 |
      | Process Power | 5/10 | Late | ___/10 |

      Score 0-2: No moat yet
      Score 3-5: Emerging moat
      Score 6-8: Solid moat
      Score 9-10: Deep moat

  - name: Building Moat Over Time
    description: When and how moats can be built at each stage
    when: Planning long-term defensibility
    example: |
      # MOAT BUILDING TIMELINE:

      ## Pre-PMF: Counter-Positioning
      """
      Your best moat is a model incumbents can't copy.

      EXAMPLES:
      - Direct-to-consumer vs retail
      - Subscription vs one-time
      - Self-serve vs sales-led
      - Open source vs proprietary

      This buys you time while you build real moats.
      """

      ## Early Growth: Network Effects Seeds
      """
      Design for network effects even if they don't exist yet.

      TACTICS:
      - Make sharing core to product
      - Build multi-player features early
      - Collect data that will power ML later
      - Create community from first users

      Network effects don't appear - they're designed.
      """

      ## Growth Phase: Switching Costs
      """
      Every month of usage should increase lock-in.

      TACTICS:
      - Data accumulation (history, content)
      - Integration expansion
      - Power user features
      - Team adoption and training

      Customer using you for 2 years should be 10x harder to churn.
      """

      ## Scale Phase: Scale Economies + Brand
      """
      Size enables advantages others can't match.

      TACTICS:
      - Spread fixed costs across volume
      - Negotiate supplier leverage
      - Invest in brand with profits
      - Build process power

      At scale, your costs per user should beat competitors.
      """

      ## Maturity: Multiple Moats
      """
      The strongest companies stack moats.

      AMAZON STACK:
      - Scale (logistics, purchasing)
      - Network (marketplace sellers/buyers)
      - Data (recommendation, search)
      - Brand (trust)
      - Switching (Prime, integrations)

      One moat can be breached. Multiple moats = fortress.
      """

anti_patterns:
  - name: '"Great Product" as Moat'
    description: Believing product quality alone is defensible
    why: |
      Products can be copied. Features can be matched. If you're competing on
      product alone, you're in an arms race. Eventually someone with more
      resources catches up. Great product is necessary but not sufficient.
    instead: Great product + structural advantage. Product creates value, moat protects it.

  - name: First Mover Illusion
    description: Believing being first creates lasting advantage
    why: |
      First mover rarely wins unless they also build a moat. MySpace was first.
      Friendster was first. Yahoo was first. Being first just means you do
      the market education for the winner who follows.
    instead: First mover advantage only matters if you use the time to build moats.

  - name: Moat Confusion
    description: Mistaking temporary advantages for moats
    why: |
      VC funding is not a moat. Exclusive partnership is not a moat (until
      contract ends). Being in hot space is not a moat. Founder expertise
      is not a moat (can be hired away). Real moats are structural.
    instead: Ask "will this advantage compound or erode over time?"

  - name: Premature Moat Focus
    description: Worrying about moat before product-market fit
    why: |
      Moats protect valuable businesses. Before PMF, you don't have a valuable
      business to protect. Focusing on moat before value is putting cart
      before horse. Get to value first.
    instead: Find PMF first. Then build moat. Moat without value protects nothing.

  - name: Single Moat Reliance
    description: Depending on one source of competitive advantage
    why: |
      Any single moat can be breached. Technology changes. Regulations change.
      Competitors innovate. Companies that rely on one moat are vulnerable.
      The greatest companies stack multiple moats.
    instead: Build primary moat, then layer additional moats over time.

  - name: Ignoring Moat Erosion
    description: Not monitoring and maintaining competitive advantages
    why: |
      Moats erode. Patents expire. Technology commoditizes. Network effects
      can be overcome with better product. Scale can be matched. Continuous
      investment in moat maintenance is required.
    instead: Regularly assess moat strength. Invest in deepening. Add new moats.

  - name: Copying Competitor Moats
    description: Trying to build same moat as incumbent
    why: |
      If incumbent has network effects, you can't just build network effects.
      They're ahead. You need a different moat or a wedge strategy. Don't
      fight battles on their terrain.
    instead: Find orthogonal moat or wedge into market where their moat doesn't apply.

handoffs:
  receives_from:
    - skill: product-strategy
      receives: Product-market fit to protect
    - skill: growth-strategy
      receives: Growth that builds moat

  hands_to:
    - skill: pricing-strategy
      provides: Moat strength context for pricing power
    - skill: platform-strategy
      provides: Platform moat requirements

tags:
  - moat
  - defensibility
  - strategy
  - network-effects
  - switching-costs
  - competitive-advantage
  - seven-powers
