# Product Strategy Skill Test Cases
# Tests for: spawner-v2/skills/strategy/product-strategy

skill_id: product-strategy
skill_path: strategy/product-strategy

tests:
  # Open-ended test - holistic skill application
  - id: product-strategy-open-01
    type: open-ended
    name: Create product strategy for B2B SaaS
    prompt: |
      You're the Head of Product at an early-stage B2B SaaS startup.

      Context:
      - Product: Invoice management software for small businesses
      - Current: 200 paying customers, $15k MRR, 8% monthly churn
      - Team: 2 engineers, 1 designer, you
      - Runway: 12 months
      - Competitors: Freshbooks, Quickbooks, Wave

      Create a product strategy for the next 6 months that addresses:
      - How to reduce churn
      - What to build vs what NOT to build
      - How to differentiate from larger competitors
      - How to prioritize with limited resources
    evaluation_criteria:
      - Problem-focused vs feature-focused thinking
      - Resource-aware prioritization
      - Clear success metrics
      - Differentiation strategy
      - Churn analysis approach

  # Trap test 1 - targets build-it-they-will-come sharp edge
  - id: product-strategy-trap-01
    type: trap
    name: Founder pitches new product idea
    sharp_edge_targeted: build-it-they-will-come
    prompt: |
      A founder comes to you excited about their startup idea:

      "I've been a freelance designer for 10 years and I'm tired of chasing invoices.
      I want to build an AI-powered invoicing platform that automatically follows up
      with clients, predicts payment likelihood, and integrates with design tools
      like Figma and Adobe.

      I've already sketched the UI, defined the feature set, and I'm ready to hire
      engineers. I think we can build an MVP in 3 months and launch by Q2.

      What do you think? Should I start building?"
    expected_catch: |
      Should identify:
      1. No validation - zero customer interviews mentioned
      2. Solution-first thinking - already defined features before validating problem
      3. Assumptions need testing - is this a widespread problem? Willingness to pay?
      4. Recommend customer discovery before building
      5. The Mom Test - talk about their life, not your idea
      Not just "great idea, here's how to build it faster."

  # Trap test 2 - targets feature-factory-trap sharp edge
  - id: product-strategy-trap-02
    type: trap
    name: Review this product roadmap
    sharp_edge_targeted: feature-factory-trap
    prompt: |
      Review this Q1 product roadmap and give feedback:

      **Q1 Roadmap - Project Management Tool**

      January:
      - Add Gantt chart view
      - Slack integration
      - Mobile app improvements

      February:
      - Calendar sync (Google, Outlook)
      - Custom fields for tasks
      - Dark mode

      March:
      - Time tracking feature
      - Resource allocation view
      - API for developers

      Success criteria: Ship all features by March 31.

      Is this a good roadmap?
    expected_catch: |
      Should identify:
      1. This is a feature factory - output focused, not outcome focused
      2. No "why" - what problems do these solve?
      3. No metrics - how do we know if they worked?
      4. No prioritization rationale - why these features?
      5. Success = shipping, not impact
      6. Recommend outcome-based roadmap instead
      Not just "looks good, maybe add one more feature."
