# Early Stage Hustle Skill
# Do things that don't scale - the pre-scale playbook

id: early-stage-hustle
name: Early Stage Hustle
category: strategy
version: 1.0.0
last_updated: 2025-12-19

description: |
  Before product-market fit, your job is to learn as fast as possible.
  That means doing things that won't scale - manual onboarding, concierge
  service, recruiting users one by one.

  Paul Graham's "Do Things That Don't Scale" is the bible here. This skill
  synthesizes the hustle playbook that creates escape velocity.

triggers:
  keywords:
    - early stage
    - pre-pmf
    - do things that don't scale
    - manual onboarding
    - concierge
    - first users
    - launch
    - mvp
    - traction
    - bootstrapping users
  contexts:
    - Just launched
    - Pre-product market fit
    - First 100 users
    - Getting initial traction

principles:
  - name: Do things that don't scale
    description: |
      Scalable solutions are for later. Now, do whatever it takes to make
      users successful - even if it means doing their work for them.
      The insights from manual work inform what to automate.
    source: "Do Things That Don't Scale"
    examples:
      good: "Airbnb founders personally photographed listings"
      bad: "We need to build automated photographer matching first"

  - name: Recruit users manually
    description: |
      Don't wait for organic growth. Go where your users are and bring them
      one by one. The first 10 users you handpicked will tell you more than
      10,000 from paid ads.
    source: "Do Things That Don't Scale"
    examples:
      good: "Stripe went to YC companies and installed manually"
      bad: "Launch and wait for signups"

  - name: Make something people want
    description: |
      The only thing that matters pre-PMF. All the hustle in the world won't
      save a product people don't want. Listen to users. Iterate daily.
    source: YC Motto
    examples:
      good: "Changed the product 3 times based on what users actually needed"
      bad: "Users don't get our vision, we need to educate them"

  - name: Launch before you're ready
    description: |
      If you're not embarrassed by v1, you launched too late. The market
      doesn't care about your feelings. Shipping teaches you faster than
      building. Launch, learn, iterate.
    source: "Do Things That Don't Scale"
    examples:
      good: "Shipped with bugs, fixed them based on real user feedback"
      bad: "Just a few more features and we'll be ready..."

  - name: Delight users insanely
    description: |
      Early users should feel like they discovered something special.
      Go above and beyond. Respond in minutes. Send handwritten notes.
      These users become evangelists.
    source: "Do Things That Don't Scale"
    examples:
      good: "Wufoo sent handwritten thank-you notes"
      bad: "Users are just data points"

anti_patterns:
  - name: Premature automation
    description: Building systems before understanding the problem
    example: "Building automated onboarding before you've onboarded 10 users manually"
    why_bad: |
      You'll automate the wrong thing. Manual work reveals what actually
      needs to be done. Automation locks in assumptions.
    fix: Do it manually 50 times. Then automate what's clear.

  - name: Launch perfectionism
    description: Waiting until it's "ready" to ship
    example: "Polishing UI for 6 months before showing anyone"
    why_bad: |
      You're not learning. The market moves. You'll build wrong.
      Every day not shipped is a day not learning.
    fix: Launch when core value works. Fix everything else based on feedback.

  - name: Spray and pray growth
    description: Trying to reach everyone instead of finding true fans
    example: "Let's get on Product Hunt, TechCrunch, and run Facebook ads all at once"
    why_bad: |
      Vanity metrics without retention. You need 100 users who love you,
      not 10,000 who bounce. Spray and pray teaches nothing.
    fix: Focus on one channel. Go deep. Make users successful.

  - name: Hiring before fire
    description: Building team before proving the product works
    example: "Let's hire a marketing team to help us find users"
    why_bad: |
      Founders should do everything first. You need to understand every
      function. Hiring multiplies what you've figured out.
    fix: Do it yourself until you're drowning. Then hire.

  - name: Building in stealth
    description: Staying hidden because you're afraid of judgment or copying
    example: "We can't tell anyone what we're building, they might steal it"
    why_bad: |
      Ideas are worth nothing. Execution is everything. Stealth prevents
      feedback and learning. No one will steal your idea.
    fix: Talk about it constantly. Get feedback everywhere. Execute faster.

  - name: Premature Automation
    description: Building systems before understanding the problem through manual work
    why: You automate the wrong thing. Manual work reveals what's actually needed.
    instead: Do it manually 50 times. Then automate what's clearly repetitive. Not before.

  - name: Launch Perfectionism
    description: Waiting until it's polished before showing users
    why: Every day not shipping is a day not learning. Market moves while you polish.
    instead: Ship when core value works. Fix everything else based on real feedback.

  - name: Spray and Pray Growth
    description: Trying to reach everyone instead of making specific users successful
    why: Vanity metrics without retention. You need 100 who love you, not 10,000 who bounce.
    instead: One channel. One user type. Deep success before broad reach.

  - name: Hiring Before Doing
    description: Hiring people to do work founders should do first
    why: Founders need to understand every function. Hiring multiplies what you've learned.
    instead: Do it yourself until drowning. Document what works. Then hire.

  - name: Stealth Mode
    description: Building in secret to avoid copying or criticism
    why: Feedback is oxygen. Ideas are worthless. Execution matters. No one will steal it.
    instead: Talk about it everywhere. Get feedback constantly. Ship publicly. Execute faster.

  - name: Feature Scope Creep
    description: Adding features before validating core value
    why: Complexity kills learning velocity. Users want one thing to work great.
    instead: Ship minimal core value. Add features only when users repeatedly request them.

patterns:
  - name: Collison Installation
    description: Physically help users start using your product on the spot
    when: Acquiring first users and learning onboarding friction
    example: |
      Patrick Collison would go to startups and help them integrate Stripe right there
      Don't send docs. Don't schedule a call. Do it with them. Now.
      You learn everything about real friction. They become successful users.

  - name: Concierge MVP
    description: Deliver the outcome manually before building automation
    when: Testing demand before building complex systems
    example: |
      Food on the Table founder personally meal-planned for users for months
      Zappos bought shoes from stores before building inventory
      Prove people want the outcome. Learn the details. Then automate.

  - name: Insane Responsiveness
    description: Reply to every user message within minutes, not hours or days
    when: Building early user loyalty and learning velocity
    example: |
      Wufoo sent handwritten thank-you notes to users
      Ben Silbermann (Pinterest) personally emailed early users
      Speed of response signals you care. Users become evangelists.

  - name: Founder-Led Sales
    description: Founders personally close every early deal, don't delegate
    when: Learning what message resonates and building product intuition
    example: |
      Every YC company: Founders sell until pattern is clear
      You learn objections, positioning, what features actually matter
      Sales teaches product. Don't outsource this learning.

  - name: Small Batch Shipping
    description: Ship tiny improvements daily based on what you learned yesterday
    when: Pre-PMF when learning velocity matters most
    example: |
      Deploy 3x per day based on user feedback from morning
      Fastest learning wins. Shipping is learning.
      Weekly sprints are too slow pre-PMF.

  - name: Desperation-Driven Quality
    description: Make early users so successful they have to tell others
    when: Building word-of-mouth before having marketing budget
    example: |
      Do their work for them. Fix issues instantly. Delight insanely.
      Every early user is a potential evangelist or case study.
      10 users who love you beat 1000 who are indifferent.

frameworks:
  - name: The Collison Installation
    when_to_use: Getting your first users
    structure:
      - "Find someone who should use your product"
      - "Go to where they are (office, conference, online)"
      - "Ask: Can I show you something?"
      - "If they like it: Can I set you up right now?"
      - "Do it for them on the spot"
      - "Follow up relentlessly"
    notes: |
      Patrick Collison would offer to help startups integrate Stripe
      right there, on their laptop. The installation, not the ask.

  - name: Concierge MVP
    when_to_use: Testing a service before building it
    structure:
      - "Promise the outcome manually"
      - "Deliver with human effort behind the scenes"
      - "Charge money from day 1"
      - "Learn what users actually need"
      - "Automate only the patterns that repeat"
    example: |
      Food on the Table founder personally meal-planned for users
      for months before building any software.

  - name: First 10 Users Playbook
    when_to_use: Getting initial traction from zero
    structure:
      - "List 50 people you know who might need this"
      - "Message each personally (no mass email)"
      - "Ask to show them (not to sign up)"
      - "Watch them use it (screenshare or in-person)"
      - "Ask: would you pay for this?"
      - "If yes, close the sale now"
    notes: Your first users should be people you can reach directly.

  - name: Weekly User Learnings
    when_to_use: Staying connected to users
    structure:
      - "Talk to 10 users every week (not optional)"
      - "Ask what's broken, frustrating, missing"
      - "Watch them use the product"
      - "Log every insight"
      - "Pick top 3 learnings"
      - "Ship improvements by Friday"

handoffs:
  receives_from:
    - skill: idea-maze
      receives: Idea to execute on
    - skill: founder-character
      receives: Relentlessly resourceful mindset

  hands_to:
    - skill: talk-to-users
      provides: User conversation patterns
    - skill: product-strategy
      provides: Learnings for product direction
    - skill: growth-strategy
      provides: Foundation for scalable growth

resources:
  essential:
    - title: "Do Things That Don't Scale"
      author: "Paul Graham"
      url: "http://paulgraham.com/ds.html"
      type: essay
      why: "The definitive essay on early-stage hustle"
    - title: "How to Get Your First Customers"
      author: "YC"
      url: "https://www.ycombinator.com/library/5v-how-to-get-your-first-customers"
      type: video
      why: "Practical first-user acquisition tactics"

  recommended:
    - title: "How to Launch"
      author: "YC"
      url: "https://www.ycombinator.com/library/6u-how-to-launch"
      type: video
      why: "Launch strategies from YC partners"
    - title: "The Mom Test"
      author: "Rob Fitzpatrick"
      type: book
      why: "How to talk to users without lying to yourself"
