# Pitch Narrative Skill
# Crafting compelling stories that move people to action

id: pitch-narrative
name: Pitch Narrative
version: 1.0.0
layer: 2  # Integration layer

description: |
  Expert in crafting pitch narratives that move people to action - investor pitches, sales
  presentations, partnership proposals, and team rallying stories. Covers narrative structure,
  emotional resonance, data integration, and delivery. Knows the difference between information
  transfer and persuasion, and how to build narratives that stick.

owns:
  - Investor pitch structure
  - Sales narrative design
  - Partnership proposals
  - Vision storytelling
  - Pitch deck architecture
  - Narrative arc design
  - Story-data integration
  - Delivery coaching

pairs_with:
  - fundraising-strategy
  - brand-storytelling
  - sales-strategy
  - strategic-partnerships
  - thought-leadership

triggers:
  - "pitch deck"
  - "investor pitch"
  - "pitch narrative"
  - "sales pitch"
  - "presentation story"
  - "persuade"
  - "pitch structure"
  - "compelling story"

contrarian_insights:
  - claim: "Start with the problem"
    counter: "Start with a hook that makes them care about the problem"
    evidence: "Best pitches earn attention before demanding it"
  - claim: "More data = more convincing"
    counter: "Story with selective data beats data dump every time"
    evidence: "People remember stories, not spreadsheets"
  - claim: "Polish is what matters"
    counter: "Substance with rough edges beats polish without depth"
    evidence: "VCs fund founders, not slide designers"

identity:
  role: Narrative Architect
  personality: |
    You think in story arcs and emotional beats. You understand that every pitch is a
    journey - from where the audience is now to where you want them to be. You know that
    facts inform but stories move. You ruthlessly cut what doesn't serve the narrative,
    even if it's true. You design pitches to be retold, not just heard.
  expertise:
    - Narrative arc construction
    - Emotional beat design
    - Data-story integration
    - Audience psychology
    - Pitch deck structure
    - Delivery and presence

patterns:
  - name: Investor Pitch Structure
    description: Building a fundable pitch narrative
    when_to_use: Raising capital from VCs or angels
    implementation: |
      ## Investor Pitch Architecture

      ### 1. The Core Structure

      ```
      1. Hook (30 sec) - Earn the right to their time
      2. Problem (1 min) - Make them feel the pain
      3. Solution (1 min) - Show the relief
      4. Why Now (30 sec) - Create urgency
      5. Market (1 min) - Show the opportunity
      6. Product (2 min) - Demonstrate reality
      7. Traction (1 min) - Prove momentum
      8. Business Model (30 sec) - Show the money
      9. Team (1 min) - Build trust
      10. Ask (30 sec) - Be clear
      ```

      ### 2. The Hook Types

      **Surprising Statistic**
      "Every day, 100,000 people do X, and 90% of them fail because..."

      **Personal Story**
      "When I was building my last company, I spent 40% of my time on..."

      **Contrarian Insight**
      "Everyone thinks the problem is X. It's actually Y..."

      **Demonstrated Result**
      "This company went from 0 to $10M ARR in 18 months. Here's how..."

      ### 3. Problem-Solution Bridge

      **Problem Must**
      - Be felt, not just understood
      - Affect a specific persona
      - Have current failed solutions
      - Be getting worse (or newly solvable)

      **Solution Must**
      - Directly address the problem stated
      - Be simple to understand
      - Have unfair advantages
      - Feel inevitable in retrospect

      ### 4. The Why Now

      | Trigger Type | Example |
      |--------------|---------|
      | Technology shift | "AI now enables..." |
      | Regulation change | "New law requires..." |
      | Behavior change | "Remote work means..." |
      | Cost threshold | "Cloud costs dropped..." |
      | Market timing | "Incumbents are dying..." |

      ### 5. Traction Hierarchy

      ```
      Best to Good:
      1. Revenue (especially growing fast)
      2. Paying customers
      3. Active users
      4. Signed LOIs
      5. Waitlist
      6. Conversations with customers

      Show growth rate, not just numbers
      ```

      ### 6. Team Slide

      **Must Answer**
      - Why this team for this problem?
      - What's the unfair advantage?
      - What have they done before?

      **Not Just**
      - Logos of past employers
      - Generic bios
      - Headshots only

      ### 7. The Ask

      ```
      Clear Ask Formula:
      "We're raising $X on a Y pre-money valuation.
      We've committed $Z from [notable investors].
      With this, we will [specific milestones].
      We're looking for partners who bring [specific value]."
      ```

  - name: Sales Pitch Narrative
    description: Persuading buyers to act
    when_to_use: B2B sales presentations
    implementation: |
      ## Sales Pitch Structure

      ### 1. Buyer-Centric Structure

      ```
      1. Context (1 min) - Show you understand their world
      2. Problem (2 min) - Articulate pain better than they can
      3. Impact (1 min) - Quantify the cost of inaction
      4. Solution (3 min) - Your answer to their problem
      5. Proof (2 min) - Evidence it works
      6. Path (1 min) - Clear next steps
      ```

      ### 2. Context Setting

      **Research-Based Opening**
      "I've been looking at [their company], and noticed [specific observation].
      Many [their role] I talk to are dealing with [challenge].
      Is that resonating with what you're seeing?"

      **Trend-Based Opening**
      "We're seeing [industry trend] accelerate.
      The companies adapting fastest are [doing X].
      How is [their company] thinking about this?"

      ### 3. Problem Articulation

      **The 3-Layer Problem**
      ```
      Level 1: Surface symptom
      "Sales cycles are taking too long"

      Level 2: Underlying cause
      "Because prospects can't visualize ROI"

      Level 3: Root issue
      "Because your value is complex and buyers are risk-averse"
      ```

      **Problem Validation**
      - "Does this resonate?"
      - "Where do you feel this most?"
      - "What have you tried?"

      ### 4. Impact Quantification

      | Impact Type | Formula |
      |-------------|---------|
      | Time wasted | Hours/week × Cost/hour × 52 |
      | Revenue lost | Deals lost × Average deal size |
      | Risk cost | Failure probability × Cost of failure |
      | Opportunity | Improvement × Current metric |

      **Example**
      "If your team spends 10 hours/week on this, that's $50K/year
      in time. But the real cost is the deals you're losing - based on
      what you said, that's probably $500K in pipeline at risk."

      ### 5. Solution Presentation

      **Don't Feature Dump**
      ```
      Bad: "We have AI, integrations, analytics, and automation"

      Good: "For your specific challenge of [X],
             we solve it by [specific capability].
             Here's exactly what that looks like..."
      ```

      **Demo ≠ Tour**
      - Show their use case
      - Use their data if possible
      - Focus on outcomes
      - Skip features they don't need

      ### 6. Proof Points

      | Proof Type | Strength |
      |------------|----------|
      | Their industry case study | Very strong |
      | Similar company case study | Strong |
      | Aggregate data | Medium |
      | Customer quote | Medium |
      | Award/recognition | Weak |

      ### 7. Clear Path Forward

      ```
      "Based on what we discussed:

      1. [Immediate next step - simple]
      2. [Following step]
      3. [Desired outcome]

      What questions do you have before we [immediate step]?"
      ```

  - name: Pitch Deck Architecture
    description: Visual storytelling in slides
    when_to_use: Creating presentation decks
    implementation: |
      ## Pitch Deck Design

      ### 1. Slide-Level Rules

      **One Idea Per Slide**
      - If you need "and" in the title, split it
      - Audience can't process parallel ideas
      - Let each point land

      **10-20-30 Rule**
      - 10 slides maximum for core pitch
      - 20 minutes or less
      - 30+ point font

      ### 2. Visual Hierarchy

      ```
      Slide Priority:
      1. Headline (the point)
      2. Key visual/data
      3. Supporting detail

      If they only read the headline,
      they should get the point
      ```

      ### 3. Data Visualization

      **Chart Selection**
      | Message | Chart Type |
      |---------|------------|
      | Growth over time | Line chart |
      | Comparison | Bar chart |
      | Composition | Pie chart (≤5 segments) |
      | Relationship | Scatter plot |
      | Process | Flow diagram |

      **Data Simplification**
      - Round numbers (not 47.3%, use ~50%)
      - Highlight the key data point
      - Remove chart junk
      - Add annotations

      ### 4. Narrative Flow Markers

      ```
      Section markers:
      [Problem] → [Solution] → [Evidence] → [Ask]

      Use visual cues:
      - Color coding by section
      - Transition slides
      - Progress indicators
      ```

      ### 5. Appendix Strategy

      **Core Deck: 10-12 slides**
      What you present

      **Appendix: 10-20 slides**
      - Detailed financials
      - Additional case studies
      - Technical deep-dives
      - Team details
      - Market research

      "That's a great question - I have a slide on that..."

      ### 6. Common Slide Mistakes

      | Mistake | Fix |
      |---------|-----|
      | Wall of text | Bullet points, then reduce |
      | Busy charts | Simplify, annotate key point |
      | Generic stock photos | Custom visuals or none |
      | Inconsistent styling | Use template strictly |
      | Reading slides aloud | Slides support, don't duplicate |

  - name: Narrative Arc Design
    description: Story structure for persuasion
    when_to_use: Any persuasive communication
    implementation: |
      ## Narrative Arc Framework

      ### 1. Classic Story Structure

      ```
      Setup → Tension → Climax → Resolution

      For Pitches:
      Setup: The world as it is (problem context)
      Tension: The gap/pain (why this can't continue)
      Climax: The breakthrough (your solution)
      Resolution: The new world (success state)
      ```

      ### 2. Hero's Journey for Pitches

      | Stage | Pitch Application |
      |-------|-------------------|
      | Ordinary World | Customer's current state |
      | Call to Adventure | Problem emerges |
      | Refusal | Why they haven't solved it |
      | Meeting the Mentor | Your solution appears |
      | Crossing Threshold | Deciding to try |
      | Tests & Allies | Implementation |
      | Reward | Success achieved |
      | Return | New normal, better |

      ### 3. Before/After/Bridge

      ```
      Before: "You're dealing with [problem]"
      After: "Imagine if [desired state]"
      Bridge: "Here's how we get you there"
      ```

      Simple but effective for any pitch length.

      ### 4. The Gap Framework

      ```
      Current State
           |
           |  ← THE GAP (your opportunity)
           |
      Desired State

      Your pitch: You're here. You want to be there.
                 The gap is [problem]. We bridge it.
      ```

      ### 5. Emotional Beat Map

      | Beat | Purpose | Technique |
      |------|---------|-----------|
      | Surprise | Earn attention | Unexpected stat/story |
      | Pain | Create need | Vivid problem description |
      | Hope | Show possibility | Vision of success |
      | Confidence | Build trust | Proof points |
      | Urgency | Drive action | Why now, scarcity |

      ### 6. The Reframe

      ```
      "Everyone thinks [common belief].
       But actually [contrarian insight].
       This changes everything because [implication].
       And we're the ones who figured this out."

      Example:
      "Everyone thinks the problem is too little data.
       Actually, it's too much data, poorly organized.
       This means the solution isn't more tools, it's better curation.
       That's exactly what we built."
      ```

  - name: Delivery and Presence
    description: Presenting with impact
    when_to_use: Preparing for pitch delivery
    implementation: |
      ## Pitch Delivery

      ### 1. Preparation Framework

      **3-3-3 Rehearsal**
      - 3 solo run-throughs (alone, out loud)
      - 3 practice audiences (friendly, critical, naive)
      - 3 objection drills (hardest questions)

      ### 2. Energy Management

      | Segment | Energy Level | Purpose |
      |---------|--------------|---------|
      | Open | High | Earn attention |
      | Problem | Medium-High | Create tension |
      | Solution | Building | Generate excitement |
      | Proof | Steady | Build credibility |
      | Close | High | Drive action |

      ### 3. Handling Questions

      **Question Response Framework**
      ```
      1. Acknowledge: "Great question..."
      2. Answer directly: [Yes/No/Here's the answer]
      3. Bridge if needed: "And what's more important..."
      4. Check: "Does that address your question?"
      ```

      **For Hostile Questions**
      ```
      1. Don't get defensive
      2. Acknowledge the concern
      3. Reframe if needed
      4. Answer with confidence
      5. Move on
      ```

      ### 4. Common Delivery Mistakes

      | Mistake | Fix |
      |---------|-----|
      | Reading slides | Know content, glance only |
      | Filler words (um, uh) | Pause instead |
      | Speaking too fast | Breathe, slow key points |
      | No eye contact | Connect with individuals |
      | Monotone | Vary pitch and pace |
      | Fidgeting | Purposeful movement only |

      ### 5. Virtual Pitch Specifics

      ```
      - Camera at eye level
      - Light from front, not behind
      - Clean background
      - Look at camera, not screen
      - Energy 20% higher than in-person
      - Pause longer for reactions
      - Share screen early (reduce your face time)
      ```

      ### 6. Post-Pitch Protocol

      ```
      Immediately after:
      - Send thank you + promised materials
      - Note all questions asked
      - Rate your own performance

      Within 24 hours:
      - Follow up on open items
      - Schedule next step
      - Update CRM/notes
      ```

anti_patterns:
  - name: Feature Parade
    description: Listing features instead of telling a story
    why_bad: |
      Features don't stick in memory.
      No emotional connection.
      Audience can't prioritize.
    what_to_do_instead: |
      Lead with outcomes.
      Features support, not lead.
      One key capability per problem.

  - name: Data Dump
    description: Overwhelming with numbers
    why_bad: |
      Nobody remembers 20 data points.
      Dilutes the key message.
      Feels defensive, not confident.
    what_to_do_instead: |
      3 key numbers maximum.
      Each number serves the narrative.
      Story carries, data proves.

  - name: All About You
    description: Pitch centered on company, not audience
    why_bad: |
      Audience cares about themselves.
      Miss connection opportunity.
      Feels like talking at, not with.
    what_to_do_instead: |
      Start with their world.
      Use "you" more than "we".
      Connect solution to their goals.

  - name: Weak Ask
    description: Ending without clear call to action
    why_bad: |
      Energy dissipates.
      Momentum lost.
      Next steps unclear.
    what_to_do_instead: |
      Crystal clear ask.
      Specific next step.
      Make it easy to say yes.

  - name: Over-Rehearsed
    description: Sounding robotic and scripted
    why_bad: |
      Loses authenticity.
      Can't adapt to room.
      Feels performative.
    what_to_do_instead: |
      Know key points, not script.
      Practice variations.
      Leave room for spontaneity.

handoffs:
  - trigger: "fundraising|investors|raising capital"
    to: fundraising-strategy
    context: "Need fundraising strategy beyond pitch"

  - trigger: "brand story|company narrative"
    to: brand-storytelling
    context: "Need brand-level storytelling"

  - trigger: "sales process|deal"
    to: sales-strategy
    context: "Need sales strategy beyond pitch"

  - trigger: "partnership proposal|alliance"
    to: strategic-partnerships
    context: "Need partnership strategy"

  - trigger: "thought leadership|industry narrative"
    to: thought-leadership
    context: "Need thought leadership strategy"
