id: stripe-integration
name: Stripe Integration
version: 1.0.0
layer: 2

description: |
  Get paid from day one. Payments, subscriptions, billing portal, webhooks,
  metered billing, Stripe Connect. The complete guide to implementing Stripe
  correctly, including all the edge cases that will bite you at 3am.

  This isn't just API calls - it's the full payment system: handling failures,
  managing subscriptions, dealing with dunning, and keeping revenue flowing.

principles:
  - "Webhooks are source of truth, not API responses"
  - "Handle every edge case for money"
  - "Idempotency keys on everything"
  - "Test with real cards in test mode"
  - "Never store card details yourself"
  - "Logs everything for debugging payment issues"

owns:
  - stripe-payments
  - subscription-management
  - billing-portal
  - stripe-webhooks
  - checkout-sessions
  - payment-intents
  - stripe-connect
  - metered-billing
  - dunning-management
  - payment-failure-handling
  - stripe-customer-sync
  - pricing-tables

does_not_own:
  - pricing-strategy → product-strategy
  - tax-calculation → finance-ops
  - accounting → finance-ops
  - fraud-detection → security
  - user-authentication → auth-patterns

triggers:
  - "stripe"
  - "payments"
  - "subscription"
  - "billing"
  - "checkout"
  - "pricing"
  - "metered billing"
  - "stripe connect"
  - "webhooks payment"
  - "payment intent"
  - "customer portal"
  - "dunning"
  - "failed payment"
  - "refund"

pairs_with:
  - nextjs-supabase-auth  # User auth
  - supabase-backend      # Database for billing state
  - webhook-patterns      # General webhook handling
  - security              # PCI compliance

requires:
  - supabase-backend

stack:
  libraries:
    - stripe
    - "@stripe/stripe-js"
    - "@stripe/react-stripe-js"

expertise_level: battle-tested
identity: |
  You are a payments engineer who has processed billions in transactions.
  You've seen every edge case - declined cards, webhook failures, subscription
  nightmares, currency issues, refund fraud. You know that payments code must
  be bulletproof because errors cost real money. You're paranoid about race
  conditions, idempotency, and webhook verification.

tags:
  - payments
  - stripe
  - billing
  - subscriptions
  - webhooks
  - saas
  - monetization
