id: spacecraft-systems
name: Spacecraft Systems
category: space
version: 1.0.0
description: >
  Use when designing or analyzing spacecraft subsystems including ADCS,
  power, thermal control, propulsion, communications, and command & data handling.

triggers:
  - "spacecraft"
  - "satellite"
  - "ADCS"
  - "attitude control"
  - "reaction wheel"
  - "star tracker"
  - "solar array"
  - "battery"
  - "thermal control"
  - "radiator"
  - "MLI"
  - "propulsion"
  - "thruster"
  - "communications"
  - "link budget"
  - "C&DH"
  - "subsystem"

provides:
  - name: adcs_design
    description: Attitude determination and control system design
  - name: power_system
    description: Electrical power system sizing and analysis
  - name: thermal_analysis
    description: Thermal control system design
  - name: comm_system
    description: Communication system and link budget analysis
  - name: propulsion_sizing
    description: Propulsion system selection and sizing

knowledge_base:
  subsystems:
    adcs:
      description: "Attitude Determination and Control System"
      modes:
        - "Safe mode (sun-pointing, minimum power)"
        - "Acquisition (rate damping, initial pointing)"
        - "Nominal (normal operations)"
        - "Slew (large angle maneuvers)"
        - "Fine pointing (high accuracy)"
      sensors:
        star_tracker:
          accuracy: "1-10 arcsec (3-sigma)"
          use: "High-accuracy attitude determination"
          limitations: "Blinded by Sun/Moon/Earth"
        sun_sensor:
          types: "Coarse (5 deg), Fine (0.1 deg), Digital (0.01 deg)"
          use: "Safe mode, coarse attitude"
        magnetometer:
          accuracy: "0.5-2 degrees"
          use: "LEO attitude determination"
        gyroscope:
          types: "MEMS, FOG, RLG, HRG"
          key_param: "Bias stability (deg/hr)"
          use: "Rate sensing, propagation between updates"
      actuators:
        reaction_wheel:
          use: "Fine pointing, momentum storage"
          key_params: "Max torque (Nm), max momentum (Nms)"
          sizing: "4 wheels for 3-axis + redundancy"
        magnetorquer:
          use: "Momentum dumping in LEO"
          principle: "Dipole x magnetic field = torque"
        thruster:
          use: "Large torques, momentum dumping, orbit control"
          types: "Cold gas, monoprop, biprop"

    power:
      description: "Electrical Power System (EPS)"
      components:
        solar_array:
          types: "Body-mounted, deployable, tracking"
          efficiency: "~30% for triple-junction cells"
          degradation: "~2%/year"
          factors: "Cosine loss, temperature, pointing"
        battery:
          types: "Li-ion (high energy), NiH2 (heritage)"
          key_params:
            capacity: "Wh"
            dod: "Depth of discharge (30% typical for long life)"
            cycle_life: "50000+ cycles at rated DOD"
        power_electronics:
          - "Solar array regulator"
          - "Battery charge controller"
          - "Power distribution unit"
      sizing:
        approach: |
          1. Calculate average and peak power loads
          2. Size solar array for EOL, hot case, worst pointing
          3. Size battery for eclipse duration at allowed DOD
          4. Verify positive energy balance each orbit

    thermal:
      description: "Thermal Control System (TCS)"
      environment:
        sources: "Solar flux, Earth albedo, Earth IR, internal dissipation"
        sinks: "Radiation to space"
      passive_control:
        mli: "Multi-Layer Insulation - reduces radiation"
        radiators: "High emissivity surfaces for heat rejection"
        coatings: "Control absorptivity/emissivity ratios"
        heat_pipes: "Transport heat between locations"
      active_control:
        heaters: "Maintain minimum temperatures"
        louvers: "Variable emissivity radiators"
        heat_pumps: "Active cooling for cryogenic"
      analysis:
        method: "Lumped parameter thermal network"
        cases: "Hot case (max solar), Cold case (eclipse)"

    propulsion:
      description: "Propulsion System"
      types:
        cold_gas:
          isp: "50-70 s"
          use: "Attitude control, small delta-v"
        monopropellant:
          isp: "200-230 s"
          propellant: "Hydrazine, green propellants"
        bipropellant:
          isp: "300-340 s"
          propellant: "MMH/NTO, LOX/RP-1"
        electric:
          types: "Ion (3000+ s), Hall (1500 s)"
          use: "High delta-v, long transfer times"

    communications:
      description: "Communications System"
      frequency_bands:
        S_band: "2-4 GHz, TT&C"
        X_band: "8-12 GHz, science data"
        Ka_band: "26-40 GHz, high rate"
        Optical: "Laser comm, very high rate"
      link_budget:
        equation: "P_rx = EIRP - path_loss + G_rx - losses"
        key_terms:
          eirp: "P_tx + G_tx - L_tx (dBW)"
          path_loss: "20*log10(4*pi*d/lambda) dB"
          snr: "P_rx - N_0 (dB-Hz)"
          margin: "Eb/N0 - required Eb/N0"

    cdh:
      description: "Command and Data Handling"
      components:
        - "Flight computer (processor, memory)"
        - "Data recorder (solid state)"
        - "Interfaces (1553, SpaceWire, CAN)"
      functions:
        - "Command receipt and execution"
        - "Telemetry collection and formatting"
        - "Autonomous fault detection and response"
        - "Data storage and playback"

patterns:
  - name: power_budget_analysis
    steps:
      - "List all power loads by mode"
      - "Calculate duty cycles"
      - "Determine peak and average power"
      - "Size solar array for worst case"
      - "Size battery for eclipse"
      - "Verify 20%+ margin"

  - name: link_budget_analysis
    steps:
      - "Define data rate requirement"
      - "Calculate EIRP"
      - "Compute path loss for max range"
      - "Add atmospheric and rain losses"
      - "Calculate received power"
      - "Verify 3+ dB margin"

  - name: thermal_analysis
    steps:
      - "Create thermal node model"
      - "Define hot and cold cases"
      - "Apply heat loads and environment"
      - "Run transient analysis"
      - "Verify all components in limits"
      - "Size heaters for cold case"

anti_patterns:
  - name: single_string_adcs
    problem: "Any sensor failure loses attitude control"
    solution: "Redundant sensors and fallback modes"
  - name: battery_too_small
    problem: "Deep discharge shortens battery life"
    solution: "Size for 30% DOD maximum"
  - name: cold_side_facing_sun
    problem: "Thermal control impossible"
    solution: "Define attitude constraints for thermal"
  - name: undersized_comm_link
    problem: "Cannot download mission data"
    solution: "Design for worst-case geometry"
  - name: no_safe_mode
    problem: "Anomaly becomes mission loss"
    solution: "Autonomous safe mode design"

checklist:
  adcs:
    - "Sensors selected for required accuracy"
    - "Actuators sized for disturbance torques"
    - "Safe mode defined and tested"
    - "Pointing budget closed"
  power:
    - "Solar array sized for EOL power"
    - "Battery sized for eclipse duration"
    - "Power margin > 20%"
    - "Load priority defined"
  thermal:
    - "Hot and cold cases analyzed"
    - "All components within limits"
    - "Heater power budgeted"
    - "Radiator area adequate"
  communications:
    - "Link budget closed with margin"
    - "Data rates meet mission needs"
    - "Antenna coverage analyzed"
    - "Ground station compatibility verified"
