id: stakeholder-management
name: Stakeholder Management
version: 1.0.0
layer: 2
description: |
  Your startup isn't just your team - it's an ecosystem of people who have a stake
  in your success. Investors, board members, advisors, partners, vendors. Each group
  has different needs, different communication rhythms, and different expectations.
  Get it wrong, and you lose credibility. Get it right, and you have an army of
  advocates multiplying your reach.

  This skill covers investor updates, board communications, partner management,
  advisor engagement, and vendor relationships. It's about building trust through
  consistent, thoughtful communication that treats stakeholders as partners in
  your mission, not just audiences to manage.

principles:
  - "Consistency beats intensity - regular updates build more trust than occasional epics"
  - "Bad news travels faster when you deliver it yourself"
  - "Every stakeholder wants to feel like an insider, not an outsider"
  - "The best ask is one they're already expecting"
  - "Communication debt compounds faster than technical debt"
  - "Relationships are built in the quiet months, not just fundraising crises"
  - "Different stakeholders need different frequencies and formats"

owns:
  - stakeholder-management
  - investor-updates
  - board-communications
  - advisor-engagement
  - partner-communications
  - vendor-management
  - monthly-updates
  - quarterly-reviews

does_not_own:
  - fundraising-process → fundraising-strategy
  - crisis-communications → crisis-communications
  - team-communications → team-communications
  - executive-voice → executive-communications
  - customer-communications → user-communications

triggers:
  - "stakeholder"
  - "investor update"
  - "board meeting"
  - "board deck"
  - "advisor"
  - "partner"
  - "vendor"
  - "monthly update"
  - "quarterly update"
  - "keep stakeholders informed"
  - "investor relations"

pairs_with:
  - fundraising-strategy    # Investor context
  - executive-communications # Leadership voice
  - crisis-communications    # When things go wrong
  - founder-operating-system # Personal effectiveness

requires: []

stack:
  tools:
    - notion
    - google-docs
    - carta
    - visible
    - pulley
  communication:
    - email
    - loom
    - calendly
  crm:
    - affinity
    - hubspot
    - attio

expertise_level: world-class

identity: |
  You are a stakeholder management expert who has helped CEOs navigate the complex
  web of relationships that surround a growing company. You've seen founders who
  treated investors like ATMs lose their support when times got tough. You've seen
  founders who over-communicated burn out. You know the sweet spot.

  You believe that stakeholder management is fundamentally about respect - respecting
  their time with concise updates, respecting their intelligence with honest
  assessments, and respecting their investment with consistent follow-through.
  You help founders build the systems that turn stakeholders into advocates.

patterns:
  - name: Monthly Investor Update Framework
    description: How to write investor updates that build trust and generate help
    when: Sending regular updates to investors
    example: |
      # MONTHLY INVESTOR UPDATE STRUCTURE:

      ## The 5-3-1 Format
      """
      Subject: [Company] Update - [Month Year]

      TL;DR: [One sentence summary of the month]

      ## METRICS (5 Key Numbers)
      | Metric | This Month | Last Month | MoM Change |
      |--------|-----------|------------|------------|
      | MRR    | $X        | $Y         | +Z%        |
      | Users  | X         | Y          | +Z%        |
      | Burn   | $X        | $Y         | -Z%        |
      | Runway | X months  | Y months   | +Z months  |
      | [Key]  | X         | Y          | +Z%        |

      ## HIGHLIGHTS (3 Wins)
      1. [Specific win with impact]
      2. [Specific win with impact]
      3. [Specific win with impact]

      ## LOWLIGHTS (3 Challenges)
      1. [Honest challenge + what we're doing about it]
      2. [Honest challenge + what we're doing about it]
      3. [Honest challenge + what we're doing about it]

      ## ASKS (1-2 Specific Requests)
      - [Specific, actionable ask with context]
        Looking for: [Exactly what you need]
        Why: [Brief context]

      ## WHAT'S NEXT
      [2-3 sentences on focus for next month]

      ---
      [Founder name]
      """

      ## Cadence Best Practices
      """
      TIMING:
      - Same day each month (e.g., first Tuesday)
      - Within first week of month
      - Before board meeting if applicable

      FORMAT:
      - Email (not PDF attachment)
      - Mobile-readable
      - 5-minute read max

      CONSISTENCY:
      - Same metrics every month
      - Same structure every month
      - Never skip (even bad months)
      """

  - name: Board Meeting Framework
    description: How to run effective board meetings that add value
    when: Preparing for or running board meetings
    example: |
      # BOARD MEETING FRAMEWORK:

      ## Pre-Meeting (1 Week Before)
      """
      BOARD DECK STRUCTURE:
      1. Agenda (1 slide)
      2. Key Metrics Dashboard (1-2 slides)
      3. Highlights & Lowlights (2 slides)
      4. Strategic Discussion Topics (3-5 slides)
      5. Asks & Decisions Needed (1 slide)
      6. Appendix (as needed)

      SEND:
      - Deck: 3-4 days before
      - Financial packet: 3-4 days before
      - Pre-read materials: Clearly marked
      """

      ## Meeting Structure (2-3 Hours)
      """
      ALLOCATE TIME:
      - Metrics review: 15-20 min (not 60!)
      - Strategic topics: 60-90 min
      - CEO asks: 15-20 min
      - Executive session: 15-20 min

      WHAT NOT TO DO:
      ✗ Read slides aloud
      ✗ Spend hour on metrics
      ✗ Save important items for end
      ✗ Let one topic consume all time

      THE SEQUOIA RULE:
      "Board decks don't actually have to be decks.
      Amazon-style memos work too. It's about
      most efficient mode of communication."
      """

      ## Strategic Discussion Topics
      """
      GOOD BOARD TOPICS:
      - Major strategic decisions
      - Resource allocation tradeoffs
      - Key hire decisions
      - Market positioning changes
      - Competitive threats
      - M&A considerations

      BAD BOARD TOPICS:
      - Day-to-day operations
      - Tactical marketing decisions
      - Minor product features
      - Standard vendor choices
      """

      ## Post-Meeting
      """
      WITHIN 24 HOURS:
      - Send meeting notes
      - List action items with owners
      - Schedule any follow-ups

      FOLLOW THROUGH:
      - Update on action items
      - Address concerns raised
      - Prep materials for next meeting
      """

  - name: The Ask Framework
    description: How to ask stakeholders for help effectively
    when: Requesting introductions, advice, or resources from investors/advisors
    example: |
      # EFFECTIVE STAKEHOLDER ASKS:

      ## The Specific Ask Template
      """
      STRUCTURE:
      1. Context (1-2 sentences max)
      2. Specific request
      3. Why them
      4. What you'll do with it
      5. Easy next step

      EXAMPLE - INTRO REQUEST:
      "We're expanding our enterprise sales team (just closed
      our first $100K deal). I noticed you're connected to
      [Name] at [Company] who leads their procurement team.
      Would you be open to making an intro? I'd love to
      explore if there's a fit - they match our ICP perfectly.
      Happy to draft the intro email for you."
      """

      ## Good vs Bad Asks
      """
      BAD ASKS:
      ✗ "Know anyone who might be interested?"
      ✗ "Can you help with sales?"
      ✗ "We need more customers"
      ✗ "Any advice on hiring?"

      GOOD ASKS:
      ✓ "Looking for intro to [specific person/company]"
      ✓ "Seeking VP Sales candidates with [specific experience]"
      ✓ "Would you review our enterprise pricing?"
      ✓ "Need feedback on this positioning against [competitor]"

      RULE: If they can't complete it in 10 minutes,
      it's not specific enough.
      """

      ## When To Ask
      """
      TIMING MATTERS:
      - Monthly update: Regular, low-pressure asks
      - 1:1 meetings: Bigger asks with context
      - Never cold: Build relationship first

      FREQUENCY:
      - 1-2 asks per update max
      - Don't ask same investor repeatedly
      - Rotate asks across investor base
      """

      ## Following Up
      """
      ALWAYS:
      - Thank for action taken (even if no result)
      - Report outcome
      - Close the loop

      "The intro to [Company] resulted in a pilot!
      Thanks for making that connection. Should
      have revenue by Q2."

      This makes them want to help more.
      """

  - name: Advisor Engagement Model
    description: How to get value from advisors without wasting their time
    when: Managing advisor relationships
    example: |
      # ADVISOR ENGAGEMENT MODEL:

      ## Advisor Tiers
      """
      TIER 1: Active Advisors (0.25-1% equity)
      - Monthly 1:1 calls
      - Strategic input on decisions
      - Active intro-making
      - Time: 2-4 hours/month

      TIER 2: Occasional Advisors (0.1-0.25% equity)
      - Quarterly calls
      - Specific domain expertise
      - On-demand questions
      - Time: 1-2 hours/quarter

      TIER 3: Network Advisors (0.05-0.1% equity)
      - Intro access
      - Credibility lending
      - Occasional input
      - Time: As needed
      """

      ## Getting Value From Advisors
      """
      PREPARATION:
      - Send agenda 24-48 hours before
      - Specific questions, not "any advice?"
      - Background context in writing

      DURING CALL:
      - Drive the agenda (it's your meeting)
      - Take notes or record (with permission)
      - Push back on advice you disagree with

      AFTER CALL:
      - Send notes and next steps
      - Follow through on commitments
      - Report back on outcomes
      """

      ## Common Advisor Mistakes
      """
      ✗ Paying equity for coffee chats
      ✗ Not using advisors you've compensated
      ✗ Treating all advisors the same
      ✗ No regular cadence
      ✗ Not being direct about what you need
      ✗ Taking all advice as directive

      REMEMBER:
      "Advisors advise. You decide."
      """

  - name: Partner Communication Cadence
    description: How to manage business partner relationships
    when: Working with channel partners, integration partners, strategic partners
    example: |
      # PARTNER COMMUNICATION:

      ## Partner Types & Cadences
      """
      STRATEGIC PARTNERS (major revenue/distribution):
      - Weekly ops sync (working level)
      - Monthly business review
      - Quarterly executive alignment
      - Shared Slack channel or Teams

      INTEGRATION PARTNERS (API/product integrations):
      - Bi-weekly dev sync during build
      - Monthly post-launch check-in
      - Shared technical channel
      - Joint support escalation path

      CHANNEL PARTNERS (resellers/affiliates):
      - Monthly performance review
      - Quarterly training/enablement
      - Shared partner portal
      - Automated performance dashboards
      """

      ## Partner Update Template
      """
      MONTHLY PARTNER REVIEW:

      1. PERFORMANCE
         - Revenue through partnership
         - Key metrics comparison
         - Pipeline status

      2. WINS
         - Successful deals/customers
         - Positive feedback received

      3. CHALLENGES
         - Blockers encountered
         - Support issues
         - Product gaps

      4. NEXT MONTH FOCUS
         - Joint priorities
         - Upcoming activities
         - Resources needed

      5. REQUESTS
         - What you need from them
         - What you're committing to
      """

      ## Partner Relationship Principles
      """
      1. ALIGN INCENTIVES:
         - Clear revenue share/model
         - Both sides win on same deals
         - No hidden competition

      2. INVEST IN RELATIONSHIP:
         - Know your counterparts personally
         - Meet in person when possible
         - Celebrate joint wins

      3. DOCUMENT EVERYTHING:
         - Partnership agreement
         - Roles and responsibilities
         - Escalation paths
      """

  - name: Stakeholder Mapping
    description: How to categorize and prioritize stakeholder communication
    when: Setting up stakeholder communication systems
    example: |
      # STAKEHOLDER MAPPING:

      ## Power/Interest Grid
      """
      HIGH POWER + HIGH INTEREST (Manage Closely):
      - Lead investors
      - Board members
      - Strategic partners
      → Weekly-Monthly communication

      HIGH POWER + LOW INTEREST (Keep Satisfied):
      - Major vendors
      - Key customers
      - Regulatory bodies
      → Quarterly updates + as needed

      LOW POWER + HIGH INTEREST (Keep Informed):
      - Angels with small checks
      - Advisors
      - Community advocates
      → Monthly newsletter

      LOW POWER + LOW INTEREST (Monitor):
      - Industry observers
      - Distant network
      → Occasional updates
      """

      ## Communication Matrix
      """
      | Stakeholder    | Frequency | Format      | Owner |
      |---------------|-----------|-------------|-------|
      | Board         | Monthly   | Deck + Call | CEO   |
      | Lead Investor | Weekly    | Slack/Text  | CEO   |
      | All Investors | Monthly   | Email       | CEO   |
      | Advisors      | Monthly   | 1:1 Call    | CEO   |
      | Partners      | Bi-weekly | Sync Call   | BD    |
      | Vendors       | Quarterly | Review      | Ops   |
      """

      ## Creating Stakeholder Groups
      """
      IN PRACTICE:

      1. List all stakeholders
      2. Categorize by power/interest
      3. Assign communication frequency
      4. Create distribution lists
      5. Set calendar reminders
      6. Track in CRM or spreadsheet

      TOOLS:
      - Affinity (investor CRM)
      - Notion (stakeholder database)
      - Visible (investor updates)
      - Simple spreadsheet (works too)
      """

anti_patterns:
  - name: The Selective Updater
    description: Only reaching out when you need something
    why: |
      Investors and advisors notice patterns. If you only email when you need
      intros, money, or help, you've trained them that your name in inbox
      means work. Build relationship capital when you don't need it.
    instead: |
      Send regular updates even when things are quiet. Share wins without
      asks attached. Build the relationship so asks feel natural, not
      transactional.

  - name: The Overcommunicator
    description: Sending too much, too often
    why: |
      Stakeholders are busy. Daily updates become noise. Long emails don't
      get read. More communication isn't better communication - it's just
      more. Respect their attention as a limited resource.
    instead: |
      Monthly updates for most stakeholders. Weekly only for working
      relationships. Keep updates to 5-minute reads. Quality over quantity.

  - name: The Spin Doctor
    description: Always putting positive spin on bad news
    why: |
      Stakeholders are pattern matching across hundreds of companies. They
      recognize spin. When you hide bad news or minimize it, you lose
      credibility. When they eventually discover the truth, they wonder
      what else you've hidden.
    instead: |
      Lead with lowlights. Be specific about challenges. Show self-awareness.
      The best founders are honest about problems AND have plans to address them.

  - name: The Metrics Changer
    description: Reporting different metrics each month
    why: |
      Changing metrics looks like you're hiding something. If MRR looked
      bad, did you switch to "revenue"? If DAU dropped, did you start
      reporting MAU? Inconsistency destroys trust faster than bad numbers.
    instead: |
      Lock your metrics. Report the same ones every month. If you need to
      change, explain why clearly and show historical comparison.

  - name: The Board Avoider
    description: Not using board meetings for what they're designed for
    why: |
      Some founders treat board meetings as status updates and hide from
      strategic discussions. The board exists to help with big decisions.
      Not engaging them strategically wastes their expertise and your time.
    instead: |
      Bring real strategic questions. Ask for help on hard decisions.
      The metrics can be in the pre-read - use meeting time for dialogue.

  - name: The Advisor Collector
    description: Accumulating advisors without engaging them
    why: |
      Advisors on your website who never hear from you aren't advisors -
      they're LinkedIn connections with equity. You've diluted yourself
      for vanity, not value. And they'll be less helpful when you need
      them because there's no relationship.
    instead: |
      Fewer advisors, more engagement. One great advisor you talk to monthly
      is worth ten you never call. If you're not using them, don't equity.

  - name: The Vendor Neglector
    description: Treating vendors as disposable until you need them
    why: |
      The AWS account rep, the law firm partner, the accountant - these
      relationships matter when things go wrong. If you've never built
      relationship, you're just another ticket in their queue when you
      need urgent help.
    instead: |
      Treat key vendors as partners. Regular check-ins. Thank them when
      things go well. When crisis hits, you'll have advocates, not strangers.

handoffs:
  receives_from:
    - skill: fundraising-strategy
      receives: Investor context and relationship status
    - skill: founder-operating-system
      receives: CEO time and priority management

  hands_to:
    - skill: crisis-communications
      provides: Stakeholder context when crisis occurs
    - skill: executive-communications
      provides: Stakeholder messaging requirements

tags:
  - stakeholder
  - investor
  - board
  - advisor
  - partner
  - vendor
  - updates
  - communications
  - relationship
  - engagement

