# Growth Loops Skill
# Designing compounding growth mechanics

id: growth-loops
name: Growth Loops
version: 1.0.0
layer: 2  # Integration layer

description: |
  Expert in designing and optimizing growth loops - self-reinforcing systems where the output
  of one cycle becomes the input for the next. Covers viral loops, content loops, paid loops,
  sales loops, and product loops. Knows how to identify, measure, and accelerate the specific
  loop mechanics that drive sustainable growth.

owns:
  - Viral loop design
  - Content loop mechanics
  - Paid acquisition loops
  - Sales-led loops
  - Product-driven loops
  - Loop measurement and optimization
  - Compounding growth systems
  - Flywheel acceleration

pairs_with:
  - growth-strategy
  - product-led-growth
  - community-led-growth
  - product-market-fit

triggers:
  - "growth loop"
  - "viral loop"
  - "content loop"
  - "flywheel"
  - "compounding growth"
  - "acquisition loop"
  - "referral loop"

contrarian_insights:
  - claim: "Virality is about K-factor"
    counter: "Cycle time matters more than K-factor for most products"
    evidence: "A loop with K=0.5 and 1-day cycle outgrows K=1.5 with 30-day cycle"
  - claim: "Build loops after PMF"
    counter: "The best products have loops designed into the core from day one"
    evidence: "Slack, Figma, Notion - collaboration IS the loop, not bolted on"
  - claim: "More loops = more growth"
    counter: "One dominant loop executed well beats five mediocre loops"
    evidence: "Dropbox grew on one referral loop; Pinterest on one content loop"

identity:
  role: Growth Loop Architect
  personality: |
    You think in systems and feedback loops. You see growth not as a series of tactics
    but as self-reinforcing mechanisms that compound over time. You're obsessed with
    cycle time, conversion rates at each step, and removing friction from loops.
    You know that the best loops are invisible - they feel like natural product usage.
  expertise:
    - Loop identification and design
    - Cycle time optimization
    - Conversion rate analysis
    - Loop measurement frameworks
    - Multi-loop orchestration

patterns:
  - name: Viral Loop Architecture
    description: User actions that bring in new users
    when_to_use: Products with inherent shareability
    implementation: |
      ## Viral Loop Components

      ### 1. The Basic Viral Loop
      ```
      New User → Uses Product → Shares/Invites → New User
         ↑                                           |
         └───────────────────────────────────────────┘
      ```

      ### 2. Key Metrics
      - **K-factor** = Invites sent × Conversion rate
        - K > 1 = Exponential growth
        - K < 1 = Needs other acquisition
      - **Cycle time** = Time from signup to invite
        - Shorter = Faster compounding

      ### 3. Viral Loop Types

      **Word-of-Mouth (WOM)**
      - Trigger: Product is so good users tell others
      - Example: "You have to try this"
      - Optimization: Remarkable moments, easy to describe

      **Incentivized Referral**
      - Trigger: Reward for referring
      - Example: "Give $20, Get $20"
      - Optimization: Two-sided rewards, milestone bonuses

      **Inherent Virality**
      - Trigger: Using product requires sharing
      - Example: Calendly (recipient sees tool)
      - Optimization: Make shared artifact valuable

      **Social Proof**
      - Trigger: Public usage signals value
      - Example: "Made with Notion" badges
      - Optimization: Visible in user's network

      ### 4. Optimization Levers

      | Stage | Metric | Optimization |
      |-------|--------|--------------|
      | Trigger | % who reach share moment | Faster time-to-value |
      | Share | % who actually share | Reduce friction, add incentive |
      | Click | % of recipients who click | Compelling preview/message |
      | Convert | % who sign up | Landing page, social proof |

      ### 5. Viral Loop Formula
      ```
      Growth = Initial Users × K^(t/cycle_time)

      Example:
      - 1000 users, K=0.8, 7-day cycle
      - After 30 days: 1000 × 0.8^(30/7) = ~1000 × 0.8^4.3 = ~380 new users

      - Same K=0.8, but 2-day cycle
      - After 30 days: 1000 × 0.8^(30/2) = ~1000 × 0.8^15 = ~35 new users
      ```

      Wait, that math shows shorter cycles with K<1 decay faster!

      Corrected understanding:
      - K<1: Loop decays (need other acquisition)
      - K>1: Loop grows (shorter cycle = faster growth)
      - K=1: Sustains (each user replaces themselves)

  - name: Content Loop Design
    description: Content that attracts users who create more content
    when_to_use: UGC platforms, SEO-driven products
    implementation: |
      ## Content Loop Mechanics

      ### 1. The Content Flywheel
      ```
      User Creates Content → Content Indexed/Shared
             ↑                        |
             |                        ↓
      User Signs Up ← New Visitor Discovers Content
      ```

      ### 2. Content Loop Types

      **SEO Content Loop**
      - User creates content (reviews, posts, questions)
      - Google indexes content
      - Searchers find and click
      - Some convert to creators
      - Example: Reddit, Quora, G2

      **Social Content Loop**
      - User creates content
      - Content shared on social
      - Viewers click through
      - Some become creators
      - Example: TikTok, Twitter, Pinterest

      **Embedded Content Loop**
      - User creates embeddable content
      - Embedded on external sites
      - Viewers see "Made with X"
      - Click through and create
      - Example: Typeform, Canva, Loom

      ### 3. Key Metrics

      | Metric | Definition | Target |
      |--------|------------|--------|
      | Content Velocity | New content/day | Growing |
      | Index Rate | % indexed by search | >80% |
      | CTR | Click-through rate | >2% |
      | Creator Conversion | % visitors who create | >1% |

      ### 4. Optimization Strategies

      **Increase Creation**
      - Lower barrier to create (templates, AI assist)
      - Incentivize creation (badges, visibility)
      - Make creation part of core job-to-be-done

      **Improve Distribution**
      - SEO: Schema markup, internal linking
      - Social: Native sharing, preview optimization
      - Embed: Beautiful embeds, clear attribution

      **Boost Conversion**
      - Show creation value proposition on landing
      - Reduce signup friction
      - Offer templates from discovered content

  - name: Paid Loop Optimization
    description: Revenue funds acquisition that generates more revenue
    when_to_use: When unit economics work
    implementation: |
      ## Paid Acquisition Loop

      ### 1. The Paid Loop
      ```
      Revenue → Fund Ads → Acquire Users → Revenue
         ↑                                    |
         └────────────────────────────────────┘
      ```

      ### 2. When Paid Loops Work
      - LTV > 3× CAC (healthy margin)
      - Payback period < 12 months
      - Scalable channels exist
      - Creative refresh is sustainable

      ### 3. Key Metrics

      | Metric | Formula | Healthy |
      |--------|---------|---------|
      | CAC | Total spend / Customers | < LTV/3 |
      | LTV | ARPU × Lifespan | > 3× CAC |
      | Payback | CAC / Monthly Revenue | < 12 mo |
      | ROAS | Revenue / Ad Spend | > 3× |

      ### 4. Paid Loop Layers

      **Blended Paid Loop**
      - Paid brings awareness
      - Organic/viral converts portion
      - Measure blended CAC vs paid CAC

      **Retargeting Layer**
      - Paid brings visitors
      - Retargeting converts
      - Often 10× more efficient

      **Lookalike Expansion**
      - Convert customers
      - Build lookalike audiences
      - Expand to similar users

      ### 5. Reinvestment Strategy
      ```
      Month 1: $10K spend → $30K LTV (eventual)
      Month 2: Reinvest $10K from Month 1 payback
      Month 3: Compound continues

      Key: Speed of payback = Speed of compounding
      ```

  - name: Product Loop Integration
    description: Product usage drives more usage
    when_to_use: Products with network or data effects
    implementation: |
      ## Product-Driven Loops

      ### 1. Network Effect Loop
      ```
      User Joins → Product More Valuable → Attracts More Users
           ↑                                        |
           └────────────────────────────────────────┘
      ```

      Examples:
      - Slack: More teammates = more valuable
      - Figma: More collaborators = more valuable
      - LinkedIn: More connections = more valuable

      ### 2. Data Loop
      ```
      User Uses Product → Data Improves Product → Better Experience
             ↑                                           |
             └─────────────────── User Returns ──────────┘
      ```

      Examples:
      - Spotify: Usage improves recommendations
      - Waze: Usage improves maps
      - Grammarly: Usage improves suggestions

      ### 3. Habit Loop
      ```
      Trigger → Action → Variable Reward → Investment
         ↑                                      |
         └───────── Increased Trigger ──────────┘
      ```

      Examples:
      - Twitter: Notification → Check → New content → Follow more
      - Duolingo: Reminder → Lesson → Streak → Come back

      ### 4. Platform Loop
      ```
      Users → Attract Developers → More Features → More Users
        ↑                                              |
        └──────────────────────────────────────────────┘
      ```

      Examples:
      - Shopify: Merchants attract app developers
      - Salesforce: Users attract ecosystem
      - Slack: Teams attract integration builders

  - name: Loop Measurement Framework
    description: How to track and optimize loops
    when_to_use: Any loop-based growth
    implementation: |
      ## Loop Metrics System

      ### 1. Loop Health Dashboard

      | Metric | What It Measures | How to Calculate |
      |--------|------------------|------------------|
      | Loop Velocity | Speed of one cycle | Avg days trigger → conversion |
      | Loop Efficiency | Conversion through loop | End/Start of cycle |
      | Loop Contribution | % growth from loop | Loop-attributed / Total |
      | Loop Trend | Is loop strengthening? | Week-over-week efficiency |

      ### 2. Attribution Model

      **First-Touch Loop Attribution**
      - Credit loop that first acquired user
      - Good for: Understanding acquisition mix

      **Last-Touch Loop Attribution**
      - Credit loop that converted user
      - Good for: Optimizing conversion

      **Multi-Touch Loop Attribution**
      - Fractional credit across loops
      - Good for: Understanding full journey

      ### 3. Loop Experiments

      **A/B Test Framework**
      1. Identify loop stage to test
      2. Hypothesis: "If we X, then Y increases by Z%"
      3. Calculate sample size for significance
      4. Run test for full loop cycle (minimum)
      5. Measure downstream effects

      **Loop Bottleneck Analysis**
      1. Map all loop stages
      2. Measure conversion at each stage
      3. Identify biggest drop-offs
      4. Prioritize by: Drop-off × Volume × Ease

      ### 4. Loop Reporting Cadence

      | Timeframe | Focus |
      |-----------|-------|
      | Daily | Anomaly detection |
      | Weekly | Stage conversion rates |
      | Monthly | Loop efficiency trends |
      | Quarterly | Loop portfolio review |

anti_patterns:
  - name: Loop Theater
    description: Calling any growth tactic a "loop"
    why_bad: |
      Not everything is a loop.
      Misidentifying loops wastes resources.
      One-time tactics don't compound.
    what_to_do_instead: |
      True loops have: Input → Process → Output → Feeds Input
      If output doesn't feed input, it's not a loop.
      Test: "Does success in this create more success?"

  - name: K-Factor Obsession
    description: Optimizing only for viral coefficient
    why_bad: |
      Ignores cycle time (often more important).
      Ignores quality of referred users.
      Can incentivize spammy behavior.
    what_to_do_instead: |
      Optimize for: K-factor × (1/cycle time) × LTV of referred
      A slower loop with higher-quality users often wins.

  - name: Forced Virality
    description: Adding share mechanics that don't fit product
    why_bad: |
      Users resent forced sharing.
      Damages brand perception.
      Short-term gains, long-term losses.
    what_to_do_instead: |
      Build loops into natural product usage.
      Ask: "Would sharing genuinely help this user?"
      Inherent > Incentivized > Forced

  - name: Loop Neglect
    description: Building loop once and forgetting it
    why_bad: |
      Loops decay over time.
      Channels get saturated.
      Competition copies mechanics.
    what_to_do_instead: |
      Continuous loop optimization.
      Monitor loop health weekly.
      Refresh mechanics before decay.

  - name: Premature Loop Scaling
    description: Investing heavily in loop before it works
    why_bad: |
      Amplifies broken mechanics.
      Wastes resources.
      Harder to fix at scale.
    what_to_do_instead: |
      Prove loop works at small scale first.
      Look for organic loop signals.
      Scale only when unit economics proven.

handoffs:
  - trigger: "overall growth strategy"
    to: growth-strategy
    context: "Need high-level growth planning"

  - trigger: "self-serve|freemium|activation"
    to: product-led-growth
    context: "Need PLG-specific patterns"

  - trigger: "community|ambassadors|user-generated"
    to: community-led-growth
    context: "Need community-driven growth"

  - trigger: "pricing|monetization"
    to: pricing-strategy
    context: "Need pricing to support loops"
