# Technical Debt Strategy Skill
# Taking the right shortcuts and paying them back at the right time

id: technical-debt-strategy
name: Technical Debt Strategy
category: development
version: 1.0.0
last_updated: 2025-12-19

description: |
  Technical debt is not bad. Reckless debt is bad. Strategic debt is a tool.
  Like financial debt, it can accelerate growth when used wisely or bankrupt
  you when ignored.

  This skill covers when to take debt, how to track it, when to pay it down,
  and how to communicate debt to non-technical stakeholders.

triggers:
  keywords:
    - technical debt
    - tech debt
    - refactor
    - rewrite
    - legacy code
    - code quality
    - shortcuts
    - hack
    - quick fix
    - cleanup
  contexts:
    - Deciding whether to refactor
    - Prioritizing debt paydown
    - Planning rewrites
    - Communicating tech debt to leadership

principles:
  - name: Debt is a tool, not a sin
    description: |
      Shipping fast with known shortcuts is often the right call. The sin is
      not knowing you took debt, not tracking it, or never paying it back.
      Intentional debt with a payback plan is smart.
    examples:
      good: Ship MVP with hardcoded config, ticket to fix, timeline to address
      bad: Ship MVP with hardcoded config, forget about it, wonder why deploys break

  - name: Distinguish deliberate from accidental
    description: |
      Deliberate debt is a conscious tradeoff. Accidental debt is mess created
      by not knowing better. Deliberate debt compounds slowly. Accidental debt
      compounds fast.
    examples:
      good: Chose simple solution knowing scale will require rearchitecture
      bad: Did not understand the problem, created tangled mess

  - name: Pay interest or pay principal
    description: |
      Every time you work around debt, you pay interest. At some point, paying
      interest exceeds paying principal. Track when workarounds are eating time.
    examples:
      good: Tracked 4 hours/week working around auth system, justified 2-week refactor
      bad: Team frustrated but cannot quantify why refactor matters

  - name: Refactor in context, not in isolation
    description: |
      Pure refactoring sprints often fail or regress. Refactor as you build
      features that touch the code. Boy Scout Rule - leave it better than
      you found it.
    examples:
      good: Refactoring auth while adding SSO feature
      bad: 3-week refactor sprint with no feature output

  - name: Communicate in business terms
    description: |
      Leadership does not care about code quality. They care about velocity,
      reliability, and cost. Translate debt to those terms. Interest payments
      slow features. Principal payments enable capabilities.
    examples:
      good: Debt costs us 2 days/sprint in workarounds. Payoff enables 3x faster shipping.
      bad: The codebase is messy and we should clean it up.

anti_patterns:
  - name: Debt denial
    description: Refusing to acknowledge shortcuts were taken
    example: No tracking of known issues, pretending codebase is clean
    why_bad: Debt compounds silently. Team knows, leadership surprised.
    fix: Track all known debt. Regular debt reviews. Honest assessment.

  - name: Big bang rewrite
    description: Starting from scratch to solve debt problems
    example: Rewriting entire system because it has debt
    why_bad: Rewrites usually take 2-3x longer. New system has new debt.
    fix: Incremental migration. Strangler fig pattern. Prove value continuously.

  - name: Perfectionist paralysis
    description: Refusing to ship anything with debt
    example: Endless refactoring before features, gold-plating everything
    why_bad: Shipping is learning. Perfect code for wrong product is waste.
    fix: Ship with intentional debt. Track it. Pay it back when validated.

  - name: All debt is equal thinking
    description: Not prioritizing which debt matters
    example: Refactoring rarely-touched code while core paths are fragile
    why_bad: Limited time. Some debt costs more interest than others.
    fix: Prioritize by interest rate (pain frequency x severity).

  - name: Debt as excuse
    description: Blaming debt for all problems when execution is the issue
    example: We cannot ship anything because tech debt
    why_bad: Teams always have some debt. High performers ship anyway.
    fix: Distinguish real blockers from preferences. Ship incrementally.

frameworks:
  - name: Debt Quadrant
    when_to_use: Categorizing types of debt
    structure:
      - "Deliberate + Prudent: We know the tradeoff, ship now, fix later"
      - "Deliberate + Reckless: We know it is wrong but ship anyway"
      - "Accidental + Prudent: Did not know better, will fix when learned"
      - "Accidental + Reckless: Did not know, do not care"
    notes: Only the first quadrant is truly strategic debt

  - name: Interest Rate Calculation
    when_to_use: Prioritizing debt paydown
    structure:
      - "Frequency: How often does this debt cause pain? (daily/weekly/monthly)"
      - "Severity: How much time lost per occurrence? (minutes/hours/days)"
      - "Risk: What is worst case if this breaks? (inconvenience/outage/data loss)"
      - "Interest = Frequency x Severity + Risk factor"
    notes: Pay down highest interest rate first

  - name: Refactor vs Rewrite Decision
    when_to_use: Major architectural decisions
    structure:
      - "Can we refactor incrementally? If yes, prefer refactor."
      - "Is the domain well understood? If no, prefer refactor to learn."
      - "Is the team experienced with rewrites? If no, prefer refactor."
      - "Can we afford 6+ months of parallel systems? If no, prefer refactor."
    notes: Default to refactor. Rewrite only with strong evidence.

  - name: Debt Documentation
    when_to_use: Tracking debt across codebase
    structure:
      - "Location: Where in codebase"
      - "Description: What is the debt"
      - "Impact: How it slows us down"
      - "Payoff: Estimated effort to fix"
      - "Interest: Ongoing cost of not fixing"
      - "Priority: When should we address"

handoffs:
  receives_from:
    - skill: backend
      receives: Architectural decisions to evaluate
    - skill: devops
      receives: Infrastructure debt awareness

  hands_to:
    - skill: product-management
      provides: Velocity impact assessments
    - skill: qa-engineering
      provides: Quality risk assessments

resources:
  essential:
    - title: Managing Technical Debt
      author: Philippe Kruchten
      type: book
      why: Comprehensive framework for debt management
    - title: Refactoring by Martin Fowler
      type: book
      why: Practical techniques for safe incremental improvement

  recommended:
    - title: Strangler Fig Pattern
      url: https://martinfowler.com/bliki/StranglerFigApplication.html
      type: article
      why: Pattern for incremental system replacement
