# Founder Character Skill
# The traits that predict success - from Paul Graham's essays

id: founder-character
name: Founder Character
category: strategy
version: 1.0.0
last_updated: 2025-12-19

description: |
  What makes founders succeed? Paul Graham has observed thousands of founders
  and distilled patterns. Relentlessly resourceful. Fierce nerds. Earnest.
  These traits matter more than credentials or connections.

  This skill synthesizes PG's essays on founder character into actionable
  guidance for developing the traits that predict success.

triggers:
  keywords:
    - founder traits
    - what makes founders succeed
    - relentlessly resourceful
    - founder mindset
    - startup personality
    - founder character
  contexts:
    - Self-assessment as a founder
    - Evaluating co-founders
    - Developing founder skills

principles:
  - name: Relentlessly resourceful
    description: |
      The defining trait of successful founders. When blocked, they find a way
      around. When resources are lacking, they make do. They do not stop.
      Problems are puzzles, not walls.
    source: Relentlessly Resourceful
    examples:
      good: Server down, figure out workaround in 30 minutes, keep shipping
      bad: Hit an obstacle, wait for someone to solve it

  - name: Fierce nerds
    description: |
      Intellectual intensity combined with competitiveness. Genuinely curious.
      Care deeply about quality. Will debate ideas forever. Channel competitive
      drive into building rather than fighting.
    source: Fierce Nerds
    examples:
      good: Deep diving into problem space, arguing about solutions, shipping better version
      bad: Surface-level understanding, avoiding conflict, accepting good enough

  - name: Earnestness over cynicism
    description: |
      Genuine belief in what you're building. Not ironic detachment. Earnest
      founders attract earnest employees and customers. Cynicism is defense
      against caring, and caring is required to build great things.
    source: Earnestness
    examples:
      good: Passionate explanation of why the problem matters
      bad: Cool detachment, ironic distance, hedging conviction

  - name: Mean people fail
    description: |
      In the long run, reputation matters. Being difficult to work with limits
      who will join you, partner with you, invest in you. The best people avoid
      mean people. Kindness compounds.
    source: Mean People Fail
    examples:
      good: Reputation for being tough but fair, people want to work with you
      bad: Reputation for being difficult, best candidates decline

  - name: Keep identity small
    description: |
      The more things you identify with, the more defensively you argue. Keep
      your identity small. Be willing to be wrong. Change your mind when evidence
      warrants. Ideas are not you.
    source: Keep Your Identity Small
    examples:
      good: Able to admit mistake, change direction based on evidence
      bad: Defensive about being wrong, conflates ideas with self-worth

anti_patterns:
  - name: Learned helplessness
    description: Accepting blockers as permanent instead of solvable
    example: We cannot do X because of Y. End of discussion.
    why_bad: Resourceful founders find ways. This is giving up.
    fix: Reframe as puzzle. What is one way around this? What is another?

  - name: Credential worship
    description: Believing pedigree predicts success
    example: We need someone from Google to solve this
    why_bad: Credentials are past, not future. Many successful founders unconventional.
    fix: Evaluate by capability and character, not resume.

  - name: Passive aggressiveness
    description: Avoiding direct conflict while undermining
    example: Agreeing in meeting, complaining after
    why_bad: Trust erodes. Problems fester. Real issues unaddressed.
    fix: Direct feedback, delivered kindly. Conflict is healthy.

  - name: Idea protectionism
    description: Treating your ideas as needing defense
    example: Getting defensive when ideas challenged
    why_bad: Best ideas emerge from rigorous debate. Defense prevents improvement.
    fix: Separate ideas from identity. Seek strongest counter-arguments.

  - name: Performative passion
    description: Faking enthusiasm you do not feel
    example: Pitching with manufactured excitement
    why_bad: People detect inauthenticity. Unsustainable over years.
    fix: Work on things you genuinely care about.

  - name: Learned Helplessness
    description: Accepting blockers as permanent instead of solvable puzzles
    why: Resourceful founders find ways. This is giving up before trying.
    instead: Reframe as puzzle. What's one way around this? What's another? Keep going.

  - name: Credential Worship
    description: Believing pedigree predicts success over character and capability
    why: Credentials describe past, not future. Many successful founders unconventional.
    instead: Evaluate by resourcefulness, curiosity, and character. Not resume.

  - name: Passive Aggression
    description: Avoiding direct conflict while undermining indirectly
    why: Trust erodes. Problems fester. Real issues never addressed.
    instead: Direct feedback delivered kindly. Disagreement is healthy. Hiding it is toxic.

  - name: Idea Protectionism
    description: Defending ideas against criticism instead of improving them
    why: Best ideas emerge from rigorous debate. Defense prevents improvement.
    instead: Separate ideas from identity. Seek strongest counter-arguments. Improve.

  - name: Cynical Detachment
    description: Maintaining ironic distance to protect against caring
    why: Great things require caring deeply. Cynicism prevents necessary earnestness.
    instead: Work on things you genuinely care about. Be earnest. Vulnerability is strength.

  - name: Jerk Behavior Tolerance
    description: Accepting mean behavior because someone is talented
    why: Culture rot spreads. Best people leave. Reputation damaged.
    instead: No brilliant jerks. Talent plus kindness only. Non-negotiable.

patterns:
  - name: Relentless Resourcefulness
    description: When blocked, find a way around. Problems are puzzles, not walls.
    when: Facing any obstacle or resource constraint
    example: |
      Server down? Find workaround in 30 minutes, keep shipping
      Can't afford tool? Build minimal version yourself
      Expert unavailable? Learn enough to get unstuck
      Resourceful founders don't stop. They route around.

  - name: Fierce Intellectual Curiosity
    description: Combine genuine curiosity with competitive drive to understand deeply
    when: Learning about problem space or making decisions
    example: |
      Read everything about the domain. Talk to experts. Go deep.
      Debate ideas rigorously. Care about being right, not seeming smart.
      Channel competitive energy into building better, not fighting.

  - name: Earnest Conviction
    description: Genuine belief in what you're building without ironic distance
    when: Communicating about your company or product
    example: |
      Passionate explanation of why the problem matters
      Not: Cool detachment or hedging conviction
      Cynicism is defense against caring. Caring is required to build great things.

  - name: Small Identity Maintenance
    description: Keep ego separate from ideas to enable rapid learning
    when: Receiving feedback or making decisions
    example: |
      "I was wrong about that" said easily
      Ideas challenged without defensiveness
      Changing mind when evidence warrants
      Your ideas are not you. Flexibility beats stubbornness.

  - name: Reputation Compounding
    description: Be difficult to work with limits who will join, invest, partner
    when: All interactions with team, customers, investors, partners
    example: |
      Tough but fair. High standards with respect.
      Kindness compounds. Mean people fail eventually.
      Best people avoid jerks. Be someone great people want to work with.

  - name: Direct Feedback Loop
    description: Give and receive feedback directly, avoiding passive aggression
    when: Addressing conflicts or performance issues
    example: |
      "Here's what's not working and why" (directly, kindly)
      Not: Agreeing in meeting, complaining after
      Healthy conflict is necessary. Passive aggression is poison.

frameworks:
  - name: Resourcefulness Self-Assessment
    when_to_use: Evaluating your own resourcefulness
    structure:
      - "When was the last time you were truly blocked?"
      - "What was your response? Wait or find workaround?"
      - "How many solutions did you try before asking for help?"
      - "Do you default to I cannot or let me figure out how?"

  - name: Co-Founder Evaluation
    when_to_use: Assessing potential co-founders
    structure:
      - "How do they respond to problems? Wait or solve?"
      - "Do they have genuine curiosity about your space?"
      - "Are they earnest or ironically detached?"
      - "What is their reputation? Do good people want to work with them?"
      - "How do they respond to being wrong?"

  - name: Character Development Practices
    when_to_use: Building founder character
    structure:
      - "Practice resourcefulness: Give yourself 30 min before asking for help"
      - "Build curiosity: Read widely, ask why, go deeper"
      - "Develop earnestness: Work on things you actually care about"
      - "Strengthen kindness: Help others without expectation"
      - "Reduce identity: Practice saying I was wrong"

handoffs:
  receives_from:
    - skill: idea-maze
      receives: Problem worth caring about

  hands_to:
    - skill: early-stage-hustle
      provides: Mindset for execution
    - skill: founder-mode
      provides: Character traits for scaling

resources:
  essential:
    - title: Relentlessly Resourceful
      author: Paul Graham
      url: http://paulgraham.com/relres.html
      type: essay
      why: The single most important founder trait defined
    - title: Fierce Nerds
      author: Paul Graham
      url: http://paulgraham.com/fn.html
      type: essay
      why: Understanding intellectual intensity

  recommended:
    - title: Mean People Fail
      author: Paul Graham
      url: http://paulgraham.com/mean.html
      type: essay
      why: Why being a jerk limits success
    - title: Keep Your Identity Small
      author: Paul Graham
      url: http://paulgraham.com/identity.html
      type: essay
      why: Keeping mind open to being wrong
