# Founder Operating System Skill
# How to work effectively as a founder - from Paul Graham's essays

id: founder-operating-system
name: Founder Operating System
category: strategy
version: 1.0.0
last_updated: 2025-12-19

description: |
  Founders face unique challenges in how they work. Maker vs manager schedule
  conflicts. Default alive vs dead math. Time and money slowly leaking away.
  Effective founders develop systems for navigating these challenges.

  This skill synthesizes PG's essays on founder productivity and decision-making
  into an operating system for founder effectiveness.

triggers:
  keywords:
    - founder productivity
    - maker schedule
    - manager schedule
    - default alive
    - runway
    - focus
    - founder time management
    - prioritization
  contexts:
    - Optimizing how you work
    - Making strategic decisions
    - Managing founder time

principles:
  - name: Maker schedule vs manager schedule
    description: |
      Makers need long uninterrupted blocks. Managers work in hour chunks.
      Founders are both. Protect maker time ruthlessly. Batch manager work.
      A single meeting can blow a whole afternoon of maker work.
    source: Maker's Schedule, Manager's Schedule
    examples:
      good: Mornings are maker time, no meetings. Afternoons for calls.
      bad: Meetings scattered throughout day, never deep work.

  - name: Default alive or default dead
    description: |
      If you maintain current growth and burn, will you become profitable before
      running out of money? Know which you are. Default dead requires immediate
      action - cut burn, accelerate growth, or raise money.
    source: Default Alive or Default Dead
    examples:
      good: We are default dead. Here is our plan to become default alive.
      bad: We have 8 months runway, we will figure it out.

  - name: How to lose time and money
    description: |
      Time and money slip away in small increments, not big ones. A little
      feature creep. A slightly higher burn. The path to failure is gradual,
      not sudden. Watch the small things.
    source: How to Lose Time and Money
    examples:
      good: Weekly review of where time and money went
      bad: Assuming big decisions matter, ignoring daily choices

  - name: Writing is thinking
    description: |
      Unclear writing is unclear thinking. If you cannot write it clearly, you
      do not understand it. Writing forces clarity. Founders should write
      regularly - investor updates, memos, public posts.
    source: Write Like You Talk
    examples:
      good: Weekly written reflection on what was learned
      bad: Never writing, assuming verbal communication sufficient

  - name: Strong opinions, loosely held
    description: |
      Have conviction to move forward, but update when evidence changes. The
      ability to disagree and commit, then revise, is essential. Neither
      stubborn nor wishy-washy.
    source: How to Disagree
    examples:
      good: Clear position, but update the moment new evidence arrives
      bad: Either refusing to commit or changing position constantly

anti_patterns:
  - name: Calendar as tyrant
    description: Letting calendar fragments destroy productive time
    example: 6 meetings spread across day, no deep work possible
    why_bad: Makers need blocks. Fragmented time is wasted time.
    fix: Batch meetings. Protect mornings. Say no more often.

  - name: Runway denial
    description: Not knowing or facing default alive/dead status
    example: Vaguely aware runway is short, not doing math
    why_bad: By the time you face it, options have narrowed.
    fix: Calculate monthly. Face reality. Take appropriate action.

  - name: Thousand cuts
    description: Death by small decisions, not big ones
    example: Small feature additions, small hires, small tools adding up
    why_bad: Each seems fine. Together they kill you.
    fix: Track small decisions. Monthly review of creep.

  - name: Verbal only culture
    description: Never writing things down
    example: All decisions in meetings, nothing documented
    why_bad: Thinking stays fuzzy. History is lost. Alignment unclear.
    fix: Write weekly updates. Document decisions. Think in writing.

  - name: Flip flopping
    description: Changing direction with every new input
    example: New strategy after every investor conversation
    why_bad: Team whiplash. Nothing executes. Credibility lost.
    fix: Commit to position. Update only with significant evidence.

  - name: Calendar Tyranny
    description: Letting meetings fragment maker time into useless chunks
    why: Makers need blocks. Meeting at 10am and 2pm destroys entire day.
    instead: Batch meetings. Protect mornings. Say no to scattered calendar.

  - name: Runway Denial
    description: Not knowing or facing default alive/dead status
    why: By the time you face reality, options have narrowed dramatically.
    instead: Calculate monthly. Face truth. Take appropriate action early.

  - name: Thousand Cuts Blindness
    description: Ignoring small decisions that accumulate into failure
    why: Each small addition seems fine. Together they kill you.
    instead: Track small decisions. Monthly review of scope/burn/time creep.

  - name: Verbal-Only Culture
    description: Never writing things down, all decisions in meetings
    why: Thinking stays fuzzy. History lost. Alignment unclear. Learning forgotten.
    instead: Write weekly updates. Document decisions. Think in writing.

  - name: Flip-Flopping
    description: Changing direction with every new input or conversation
    why: Team whiplash. Nothing executes well. Credibility evaporates.
    instead: Commit to positions. Update only with significant evidence.

  - name: Always-On Burnout
    description: Working constantly without recovery time
    why: Degraded decision quality. Creativity drops. Unsustainable.
    instead: Protect evening/weekend recovery. Return fresh. Marathon requires pacing.

patterns:
  - name: Maker Time Protection
    description: Block long uninterrupted periods for deep work, batch meetings separately
    when: Structuring daily schedule as a founder
    example: |
      Mornings (8-12): Maker time. No meetings. Deep work only.
      Afternoons (1-5): Manager time. Meetings batched.
      One meeting in the morning destroys the whole block for thinking work.

  - name: Default Alive Vigilance
    description: Know your burn, growth, and path to profitability every month
    when: Monthly strategic review
    example: |
      Burn: $50k/mo, Revenue: $10k/mo growing 20%/mo
      Calculate: Months to profitability at current trajectory
      If profitability month > runway remaining: DEFAULT DEAD → Act now

  - name: Writing as Thinking
    description: Write regularly to clarify thinking and communicate clearly
    when: Making decisions and communicating with team
    example: |
      Weekly investor update (even if not raising)
      Monthly learning memo
      Write to understand. If you can't write it clearly, you don't understand it.

  - name: Small Leaks Tracking
    description: Watch how time and money slip away in small increments
    when: Weekly operational review
    example: |
      Not big decisions that kill you, but small feature additions, small hires
      Weekly: Where did time go? What got added to burn?
      Death by thousand cuts is more common than dramatic failure.

  - name: Strong Opinions, Loosely Held
    description: Have conviction to move forward, update rapidly when evidence changes
    when: Making decisions with incomplete information
    example: |
      Clear position enables action. Flexibility enables learning.
      Commit to decision. Execute. Update when evidence warrants.
      Neither stubborn nor wishy-washy.

  - name: Batch Processing
    description: Group similar tasks together to minimize context switching
    when: Managing diverse founder responsibilities
    example: |
      All customer calls on Tuesday/Thursday afternoons
      All admin work Friday morning
      All investor updates Sunday evening
      Context switching kills productivity. Batch to protect flow.

frameworks:
  - name: Maker Schedule Template
    when_to_use: Structuring founder time
    structure:
      - "Morning (8-12): Maker time. No meetings. Deep work only."
      - "Lunch (12-1): Buffer and thinking time"
      - "Afternoon (1-5): Manager time. Meetings batched."
      - "Evening: Recovery. Do not work. Return fresh tomorrow."
    notes: Adjust times to your rhythm. Key is protecting blocks.

  - name: Default Alive Calculator
    when_to_use: Monthly strategic check
    structure:
      - "Current monthly burn: $X"
      - "Current monthly revenue: $Y"
      - "Monthly growth rate: Z%"
      - "Months to profitability at current trajectory: N"
      - "Runway remaining: M months"
      - "If M < N: DEFAULT DEAD. Action required."

  - name: Weekly Review Practice
    when_to_use: Catching time and money leaks
    structure:
      - "Where did my time go this week? (calendar audit)"
      - "What got added to burn? (expense review)"
      - "What crept into scope? (feature review)"
      - "What moved us toward default alive?"
      - "What moved us toward default dead?"

  - name: Writing Practice
    when_to_use: Developing clarity of thought
    structure:
      - "Weekly: Investor update or internal memo"
      - "Monthly: Reflection on learnings"
      - "Quarterly: Strategic review"
      - "Publish when possible - public accountability helps"

handoffs:
  receives_from:
    - skill: founder-character
      receives: Character traits to channel
    - skill: burn-rate-management
      receives: Financial context for decisions

  hands_to:
    - skill: founder-mode
      provides: Operating rhythm for scaling
    - skill: hypergrowth-ops
      provides: Productivity patterns for team

resources:
  essential:
    - title: "Maker's Schedule, Manager's Schedule"
      author: Paul Graham
      url: http://paulgraham.com/makersschedule.html
      type: essay
      why: The most important essay on founder time management
    - title: Default Alive or Default Dead
      author: Paul Graham
      url: http://paulgraham.com/aord.html
      type: essay
      why: The math every founder must know

  recommended:
    - title: How to Lose Time and Money
      author: Paul Graham
      url: http://paulgraham.com/selfindulgence.html
      type: essay
      why: How small things add up to failure
    - title: Write Like You Talk
      author: Paul Graham
      url: http://paulgraham.com/talk.html
      type: essay
      why: Clarity of writing is clarity of thought
