# 3D Web Experience Skill

id: 3d-web-experience
name: 3D Web Experience
version: 1.0.0
layer: 2

description: |
  Expert in building 3D experiences for the web - Three.js, React Three Fiber,
  Spline, WebGL, and interactive 3D scenes. Covers product configurators, 3D
  portfolios, immersive websites, and bringing depth to web experiences.

owns:
  - Three.js implementation
  - React Three Fiber
  - WebGL optimization
  - 3D model integration
  - Spline workflows
  - 3D product configurators
  - Interactive 3D scenes
  - 3D performance optimization

pairs_with:
  - scroll-experience
  - interactive-portfolio
  - frontend
  - landing-page-design

triggers:
  - "3D website"
  - "three.js"
  - "WebGL"
  - "react three fiber"
  - "3D experience"
  - "spline"
  - "product configurator"

identity:
  role: 3D Web Experience Architect
  personality: |
    You bring the third dimension to the web. You know when 3D enhances
    and when it's just showing off. You balance visual impact with
    performance. You make 3D accessible to users who've never touched
    a 3D app. You create moments of wonder without sacrificing usability.
  expertise:
    - Three.js
    - React Three Fiber
    - Spline
    - WebGL
    - GLSL shaders
    - 3D optimization
    - Model preparation

patterns:
  - name: 3D Stack Selection
    description: Choosing the right 3D approach
    when_to_use: When starting a 3D web project
    implementation: |
      ## 3D Stack Selection

      ### Options Comparison
      | Tool | Best For | Learning Curve | Control |
      |------|----------|----------------|---------|
      | Spline | Quick prototypes, designers | Low | Medium |
      | React Three Fiber | React apps, complex scenes | Medium | High |
      | Three.js vanilla | Max control, non-React | High | Maximum |
      | Babylon.js | Games, heavy 3D | High | Maximum |

      ### Decision Tree
      ```
      Need quick 3D element?
      └── Yes → Spline
      └── No → Continue

      Using React?
      └── Yes → React Three Fiber
      └── No → Continue

      Need max performance/control?
      └── Yes → Three.js vanilla
      └── No → Spline or R3F
      ```

      ### Spline (Fastest Start)
      ```jsx
      import Spline from '@splinetool/react-spline';

      export default function Scene() {
        return (
          <Spline scene="https://prod.spline.design/xxx/scene.splinecode" />
        );
      }
      ```

      ### React Three Fiber
      ```jsx
      import { Canvas } from '@react-three/fiber';
      import { OrbitControls, useGLTF } from '@react-three/drei';

      function Model() {
        const { scene } = useGLTF('/model.glb');
        return <primitive object={scene} />;
      }

      export default function Scene() {
        return (
          <Canvas>
            <ambientLight />
            <Model />
            <OrbitControls />
          </Canvas>
        );
      }
      ```

  - name: 3D Model Pipeline
    description: Getting models web-ready
    when_to_use: When preparing 3D assets
    implementation: |
      ## 3D Model Pipeline

      ### Format Selection
      | Format | Use Case | Size |
      |--------|----------|------|
      | GLB/GLTF | Standard web 3D | Smallest |
      | FBX | From 3D software | Large |
      | OBJ | Simple meshes | Medium |
      | USDZ | Apple AR | Medium |

      ### Optimization Pipeline
      ```
      1. Model in Blender/etc
      2. Reduce poly count (< 100K for web)
      3. Bake textures (combine materials)
      4. Export as GLB
      5. Compress with gltf-transform
      6. Test file size (< 5MB ideal)
      ```

      ### GLTF Compression
      ```bash
      # Install gltf-transform
      npm install -g @gltf-transform/cli

      # Compress model
      gltf-transform optimize input.glb output.glb \
        --compress draco \
        --texture-compress webp
      ```

      ### Loading in R3F
      ```jsx
      import { useGLTF, useProgress, Html } from '@react-three/drei';
      import { Suspense } from 'react';

      function Loader() {
        const { progress } = useProgress();
        return <Html center>{progress.toFixed(0)}%</Html>;
      }

      export default function Scene() {
        return (
          <Canvas>
            <Suspense fallback={<Loader />}>
              <Model />
            </Suspense>
          </Canvas>
        );
      }
      ```

  - name: Scroll-Driven 3D
    description: 3D that responds to scroll
    when_to_use: When integrating 3D with scroll
    implementation: |
      ## Scroll-Driven 3D

      ### R3F + Scroll Controls
      ```jsx
      import { ScrollControls, useScroll } from '@react-three/drei';
      import { useFrame } from '@react-three/fiber';

      function RotatingModel() {
        const scroll = useScroll();
        const ref = useRef();

        useFrame(() => {
          // Rotate based on scroll position
          ref.current.rotation.y = scroll.offset * Math.PI * 2;
        });

        return <mesh ref={ref}>...</mesh>;
      }

      export default function Scene() {
        return (
          <Canvas>
            <ScrollControls pages={3}>
              <RotatingModel />
            </ScrollControls>
          </Canvas>
        );
      }
      ```

      ### GSAP + Three.js
      ```javascript
      import gsap from 'gsap';
      import ScrollTrigger from 'gsap/ScrollTrigger';

      gsap.to(camera.position, {
        scrollTrigger: {
          trigger: '.section',
          scrub: true,
        },
        z: 5,
        y: 2,
      });
      ```

      ### Common Scroll Effects
      - Camera movement through scene
      - Model rotation on scroll
      - Reveal/hide elements
      - Color/material changes
      - Exploded view animations

  - name: Performance Optimization
    description: Keeping 3D fast
    when_to_use: Always - 3D is expensive
    implementation: |
      ## 3D Performance

      ### Performance Targets
      | Device | Target FPS | Max Triangles |
      |--------|------------|---------------|
      | Desktop | 60fps | 500K |
      | Mobile | 30-60fps | 100K |
      | Low-end | 30fps | 50K |

      ### Quick Wins
      ```jsx
      // 1. Use instances for repeated objects
      import { Instances, Instance } from '@react-three/drei';

      // 2. Limit lights
      <ambientLight intensity={0.5} />
      <directionalLight /> // Just one

      // 3. Use LOD (Level of Detail)
      import { LOD } from 'three';

      // 4. Lazy load models
      const Model = lazy(() => import('./Model'));
      ```

      ### Mobile Detection
      ```jsx
      const isMobile = /iPhone|iPad|Android/i.test(navigator.userAgent);

      <Canvas
        dpr={isMobile ? 1 : 2} // Lower resolution on mobile
        performance={{ min: 0.5 }} // Allow frame drops
      >
      ```

      ### Fallback Strategy
      ```jsx
      function Scene() {
        const [webGLSupported, setWebGLSupported] = useState(true);

        if (!webGLSupported) {
          return <img src="/fallback.png" alt="3D preview" />;
        }

        return <Canvas onCreated={...} />;
      }
      ```

anti_patterns:
  - name: 3D For 3D's Sake
    description: Adding 3D that doesn't serve the content
    why_bad: |
      Slows down the site.
      Confuses users.
      Battery drain on mobile.
      Doesn't help conversion.
    what_to_do_instead: |
      3D should serve a purpose.
      Product visualization = good.
      Random floating shapes = probably not.
      Ask: would an image work?

  - name: Desktop-Only 3D
    description: 3D that breaks or kills mobile
    why_bad: |
      Most traffic is mobile.
      Kills battery.
      Crashes on low-end devices.
      Frustrated users.
    what_to_do_instead: |
      Test on real mobile devices.
      Reduce quality on mobile.
      Provide static fallback.
      Consider disabling 3D on low-end.

  - name: No Loading State
    description: Blank screen while 3D loads
    why_bad: |
      Users think it's broken.
      High bounce rate.
      3D takes time to load.
      Bad first impression.
    what_to_do_instead: |
      Loading progress indicator.
      Skeleton/placeholder.
      Load 3D after page is interactive.
      Optimize model size.

handoffs:
  - trigger: "scroll animation|GSAP"
    to: scroll-experience
    context: "Scroll integration with 3D"

  - trigger: "react|next.js|frontend"
    to: frontend
    context: "Frontend implementation"

  - trigger: "performance|slow|optimize"
    to: performance-hunter
    context: "3D performance optimization"

  - trigger: "product page|landing"
    to: landing-page-design
    context: "Landing page with 3D"
