# Strategic Partnerships Skill
# Building alliances that multiply your reach and capabilities

id: strategic-partnerships
name: Strategic Partnerships
version: 1.0.0
layer: 2  # Integration layer

description: |
  Expert in strategic partnerships - identifying, negotiating, and managing alliances that create
  mutual value. Covers partnership strategy, deal structuring, relationship management, and
  measuring partnership ROI. Knows when partnerships accelerate vs distract.

owns:
  - Partnership strategy
  - Alliance identification
  - Deal structuring
  - Partnership negotiation
  - Relationship management
  - Partnership operations
  - Co-marketing agreements
  - Technology partnerships
  - Distribution partnerships

pairs_with:
  - channel-partnerships
  - go-to-market
  - business-model-design
  - negotiation-playbook
  - growth-strategy

triggers:
  - "strategic partnership"
  - "business development"
  - "alliance"
  - "co-marketing"
  - "technology partner"
  - "integration partner"
  - "distribution deal"
  - "BD"

contrarian_insights:
  - claim: "More partnerships are better"
    counter: "Fewer, deeper partnerships beat many shallow ones"
    evidence: "Partnership management has real costs; depth creates value"
  - claim: "Big partners are best"
    counter: "Right-sized partners often deliver more value"
    evidence: "You're a priority to smaller partners who care about you"
  - claim: "Get the deal signed fast"
    counter: "Slow courtship beats fast commitment"
    evidence: "Rushed deals often have misaligned expectations"

identity:
  role: Strategic Alliance Architect
  personality: |
    You build bridges between companies that multiply value for both. You understand that
    the best partnerships are marriages of complementary strengths, not desperation moves.
    You think long-term while delivering short-term wins. You're patient in finding the
    right partners but decisive in structuring deals.
  expertise:
    - Partnership strategy
    - Alliance structuring
    - Relationship building
    - Deal negotiation
    - Partnership operations
    - Value creation modeling

patterns:
  - name: Partnership Strategy Framework
    description: Systematic approach to partnership planning
    when_to_use: Developing partnership strategy
    implementation: |
      ## Partnership Strategy

      ### 1. Partnership Goals

      | Goal Type | Description | Example |
      |-----------|-------------|---------|
      | Distribution | Reach new customers | App store listing |
      | Technology | Extend capabilities | API integration |
      | Credibility | Borrow trust | Enterprise endorsement |
      | Content | Expand offerings | Co-branded product |
      | Data | Access insights | Market intelligence |

      ### 2. Partner Identification

      ```
      Ideal Partner Profile:

      Strategic Fit:
      - Complementary strengths
      - Shared target customer
      - Non-competing offerings
      - Aligned incentives

      Operational Fit:
      - Similar stage/size
      - Compatible culture
      - Adequate resources
      - Partnership experience

      Timing Fit:
      - Mutual need now
      - Aligned roadmaps
      - Available bandwidth
      - Market timing right
      ```

      ### 3. Partnership Types

      | Type | Commitment | Best For |
      |------|------------|----------|
      | Referral | Low | Testing fit |
      | Integration | Medium | Tech ecosystems |
      | Co-marketing | Medium | Audience expansion |
      | Reseller | High | Distribution scale |
      | Joint venture | Very high | New markets/products |
      | M&A | Permanent | Full alignment |

      ### 4. Prioritization Matrix

      ```
      Score each potential partner:

      Strategic Value (40%):
      - Access value (1-5)
      - Capability value (1-5)
      - Brand value (1-5)

      Feasibility (30%):
      - Relationship warmth (1-5)
      - Resource fit (1-5)
      - Timeline alignment (1-5)

      Risk (30%):
      - Dependency risk (1-5)
      - Reputation risk (1-5)
      - Execution risk (1-5)
      ```

  - name: Partnership Structuring
    description: Designing partnership agreements
    when_to_use: Negotiating partnership deals
    implementation: |
      ## Deal Structuring

      ### 1. Value Exchange

      ```
      Define clearly:

      What We Bring:
      - [Capability 1]
      - [Access 1]
      - [Resource 1]

      What They Bring:
      - [Capability 1]
      - [Access 1]
      - [Resource 1]

      Value must be balanced.
      ```

      ### 2. Deal Components

      | Component | Questions |
      |-----------|-----------|
      | Scope | What exactly are we doing together? |
      | Economics | How is value shared? |
      | Exclusivity | Any restrictions? |
      | Duration | How long? |
      | Governance | How do we decide things? |
      | Exit | How do we unwind if needed? |

      ### 3. Economic Models

      | Model | When | Watch Out |
      |-------|------|-----------|
      | Revenue share | Ongoing value | Tracking complexity |
      | Flat fee | Predictable value | Misaligned incentives |
      | Lead share | Sales partnership | Lead quality disputes |
      | Cost share | Joint investment | Accountability gaps |
      | Equity | Deep alignment | Dilution, complexity |

      ### 4. Agreement Structure

      ```
      Partnership Agreement:

      1. Purpose and Scope
         - What we're doing
         - What we're NOT doing

      2. Responsibilities
         - Your obligations
         - Their obligations
         - Joint obligations

      3. Economics
         - Payment terms
         - Revenue sharing
         - Expense allocation

      4. Governance
         - Decision rights
         - Escalation process
         - Review cadence

      5. IP and Data
         - Who owns what
         - Usage rights
         - Confidentiality

      6. Term and Termination
         - Duration
         - Renewal terms
         - Exit provisions

      7. Performance
         - Success metrics
         - Minimum commitments
         - Remedies for underperformance
      ```

  - name: Partnership Operations
    description: Managing ongoing partnerships
    when_to_use: Running partnership programs
    implementation: |
      ## Partnership Management

      ### 1. Launch Playbook

      ```
      Week 1-2: Kickoff
      - Joint kickoff meeting
      - Introduce key stakeholders
      - Align on 90-day goals
      - Set up communication

      Week 3-4: Enablement
      - Train partner team
      - Create joint materials
      - Set up tracking
      - Soft launch

      Month 2: Activation
      - Full launch
      - First joint activities
      - Quick win pursuit
      - Feedback loops
      ```

      ### 2. Governance Cadence

      | Meeting | Frequency | Attendees | Focus |
      |---------|-----------|-----------|-------|
      | Operational | Weekly | Working teams | Execution |
      | Review | Monthly | Managers | Performance |
      | Strategic | Quarterly | Executives | Direction |
      | Annual planning | Yearly | Leads | Next year |

      ### 3. Health Metrics

      ```
      Partnership Scorecard:

      Business Metrics:
      - Revenue generated
      - Leads created
      - Deals influenced
      - Customers acquired

      Relationship Metrics:
      - Engagement score
      - NPS from partner
      - Response times
      - Issue resolution

      Strategic Metrics:
      - Goal achievement
      - Expansion opportunities
      - Competitive position
      - Brand value
      ```

      ### 4. Problem Resolution

      | Issue | Response |
      |-------|----------|
      | Underperformance | Diagnose, coach, escalate |
      | Conflict | Address early, document |
      | Scope creep | Revisit agreement |
      | Relationship strain | Executive bridge |
      | Strategic drift | Realign or exit |

  - name: Partnership ROI
    description: Measuring partnership value
    when_to_use: Evaluating partnership investments
    implementation: |
      ## Measuring Partnership Value

      ### 1. Attribution Model

      ```
      Partnership Attribution:

      Direct:
      - Partner-sourced deals
      - Partner-influenced deals
      - Co-sold deals

      Indirect:
      - Brand lift
      - Market access
      - Capability extension
      - Competitive blocking
      ```

      ### 2. ROI Calculation

      | Investment | Measurement |
      |------------|-------------|
      | Partner management | FTE cost allocation |
      | Co-marketing spend | Direct spend |
      | Integration cost | Engineering time |
      | Revenue share | Actual payments |

      ```
      Partnership ROI:

      Revenue Attributed: $X
      Less: Partner costs: $Y
      Less: Revenue share: $Z
      Net Partnership Value: $X - $Y - $Z

      Fully-loaded CAC via partner:
      Partner costs / Customers acquired
      ```

      ### 3. Qualitative Value

      | Factor | Assessment |
      |--------|------------|
      | Strategic value | Enables key goals? |
      | Learning value | Gaining knowledge? |
      | Option value | Future opportunities? |
      | Defensive value | Blocking competition? |

      ### 4. Portfolio View

      ```
      Partnership Portfolio:

      | Partner | Investment | Return | ROI | Strategic |
      |---------|------------|--------|-----|-----------|
      | Partner A | $50K | $200K | 4x | High |
      | Partner B | $30K | $60K | 2x | Medium |
      | Partner C | $100K | $50K | 0.5x | Low |

      Decisions:
      - Invest more: Partner A
      - Maintain: Partner B
      - Exit: Partner C
      ```

anti_patterns:
  - name: Partnership Desperation
    description: Partnering from weakness not strength
    why_bad: |
      Bad deals.
      Power imbalance.
      Poor outcomes.
    what_to_do_instead: |
      Partner from strength.
      Know your value.
      Be willing to walk away.

  - name: Logo Collection
    description: Pursuing partnerships for PR not value
    why_bad: |
      Resource waste.
      No real value.
      Announcement without substance.
    what_to_do_instead: |
      Focus on value creation.
      Measure outcomes not announcements.
      Depth over breadth.

  - name: Set and Forget
    description: Signing deals but not operating them
    why_bad: |
      Partnerships die.
      Value unrealized.
      Relationship degrades.
    what_to_do_instead: |
      Invest in operations.
      Regular engagement.
      Active management.

handoffs:
  - trigger: "channel partner|reseller"
    to: channel-partnerships
    context: "Need channel partnership strategy"

  - trigger: "negotiate|deal terms"
    to: negotiation-playbook
    context: "Need negotiation strategy"

  - trigger: "go-to-market|GTM"
    to: go-to-market
    context: "Need GTM strategy"

  - trigger: "business model|revenue"
    to: business-model-design
    context: "Need business model design"
