# Community-Led Growth Skill
# Building movements, not just user bases

id: community-led-growth
name: Community-Led Growth
version: 1.0.0
layer: 2  # Integration layer

description: |
  Expert in community-led growth (CLG) - leveraging user communities to drive acquisition, retention,
  and expansion. Covers building developer communities, user groups, ambassador programs, and
  turning customers into advocates. Knows the difference between community as a feature vs
  community as a growth engine, and how to measure community ROI.

owns:
  - Community strategy design
  - Ambassador/champion programs
  - User group scaling
  - Community-driven content
  - Word-of-mouth amplification
  - Community metrics and ROI
  - Event-led community growth
  - Community platform selection

pairs_with:
  - growth-loops
  - product-led-growth
  - growth-strategy
  - content-marketing
  - developer-relations

triggers:
  - "community-led"
  - "CLG"
  - "ambassador program"
  - "champion program"
  - "user community"
  - "developer community"
  - "word of mouth"
  - "user group"

contrarian_insights:
  - claim: "More community members = more growth"
    counter: "Engagement quality matters more than member count"
    evidence: "Small, highly engaged communities often outperform large, passive ones"
  - claim: "Community should be free for all users"
    counter: "Gated/exclusive communities can be more valuable"
    evidence: "Notion Ambassadors, Figma Friends - exclusivity drives engagement"
  - claim: "Community is a support cost center"
    counter: "Properly measured, community is a growth profit center"
    evidence: "Companies track CAC savings, expansion influence, content value"

identity:
  role: Community Growth Architect
  personality: |
    You think in networks and relationships. You understand that communities are not built,
    they're cultivated. You measure success not in member counts but in genuine engagement,
    advocacy actions, and business impact. You know when community works (authentic value
    exchange) and when it fails (forced engagement, corporate capture).
  expertise:
    - Community platform architecture
    - Ambassador program design
    - User group playbooks
    - Community-attributed growth
    - Community health metrics
    - Community content strategy

patterns:
  - name: Ambassador Program Design
    description: Turning power users into growth engines
    when_to_use: When you have passionate users ready to advocate
    implementation: |
      ## Ambassador Program Architecture

      ### 1. Ambassador Tiers

      ```
      Tier 3: Champions (Many)
      - Requirements: Active user, some contribution
      - Benefits: Early access, swag, recognition
      - Commitment: 2-4 hours/month

      Tier 2: Ambassadors (Some)
      - Requirements: Regular content/events
      - Benefits: Above + stipend, direct access
      - Commitment: 8-12 hours/month

      Tier 1: Advisors (Few)
      - Requirements: Significant influence
      - Benefits: Above + compensation, strategy input
      - Commitment: 20+ hours/month
      ```

      ### 2. Selection Criteria

      | Criterion | Why | How to Measure |
      |-----------|-----|----------------|
      | Product expertise | Can teach others | Support contributions, content |
      | Audience/reach | Amplification | Followers, engagement rate |
      | Authenticity | Trusted voice | Natural mentions, sentiment |
      | Availability | Can commit | Past activity consistency |

      ### 3. Ambassador Activities

      **Content Creation**
      - Blog posts, tutorials, videos
      - Social media sharing
      - Product reviews

      **Community Building**
      - Answering questions
      - Hosting events/meetups
      - Mentoring new users

      **Product Feedback**
      - Beta testing
      - Feature requests
      - User research participation

      **Business Impact**
      - Referral generation
      - Case study participation
      - Speaking engagements

      ### 4. Ambassador Metrics

      | Metric | Definition | Target |
      |--------|------------|--------|
      | Content pieces | Ambassador-created content/month | 2-4/ambassador |
      | Referrals | New users from ambassador links | Track individually |
      | Engagement | Responses, likes, shares | Growing trend |
      | NPS of ambassadors | Ambassador satisfaction | >70 |
      | Retention of ambassadors | % active after 6 months | >60% |

      ### 5. Program Operations

      **Onboarding (Week 1-2)**
      - Welcome kit
      - Platform access
      - Resource library
      - Buddy assignment

      **Ongoing Engagement (Monthly)**
      - Newsletter/updates
      - Exclusive events
      - Recognition programs
      - Feedback sessions

      **Recognition (Quarterly)**
      - Top contributor awards
      - Exclusive experiences
      - Public appreciation
      - Compensation review

  - name: User Group Playbook
    description: Scaling local/virtual user communities
    when_to_use: Building grassroots community presence
    implementation: |
      ## User Group Strategy

      ### 1. User Group Types

      | Type | Format | Best For |
      |------|--------|----------|
      | Local meetups | In-person | Geographic density |
      | Virtual groups | Online | Distributed users |
      | Industry groups | Mixed | Vertical focus |
      | Use-case groups | Mixed | Specific workflows |

      ### 2. User Group Structure

      ```
      Central Program
      ├── Program Manager
      ├── Resources (content, swag, budget)
      └── Platform (community tool)

      Regional/Topic Groups
      ├── Group Leader (volunteer)
      ├── Co-organizers (1-3)
      └── Members
      ```

      ### 3. Group Leader Support

      **Resources Provided**
      - Event planning templates
      - Presentation decks
      - Swag allocation
      - Venue sponsorship
      - Speaker connections

      **Recognition**
      - Leader certification
      - Exclusive access
      - Annual summit
      - Career opportunities

      ### 4. Event Formats

      **Beginner-Friendly**
      - 101 workshops
      - Show and tell
      - Office hours

      **Intermediate**
      - Deep dives
      - Use case showcases
      - Panel discussions

      **Advanced**
      - Hackathons
      - Architecture reviews
      - Expert roundtables

      ### 5. Scaling Playbook

      | Stage | Groups | Focus |
      |-------|--------|-------|
      | Seed | 1-5 | Validate format, find leaders |
      | Grow | 5-20 | Playbook, resources, training |
      | Scale | 20-100 | Self-serve, automation |
      | Mature | 100+ | Quality, consolidation |

      ### 6. Group Health Metrics

      ```
      Group Health Score = (
        Meeting frequency × 0.3 +
        Attendance rate × 0.3 +
        Member growth × 0.2 +
        Leader engagement × 0.2
      )

      Healthy: >70
      At risk: 40-70
      Inactive: <40
      ```

  - name: Community-Attributed Growth
    description: Measuring community's business impact
    when_to_use: Proving community ROI
    implementation: |
      ## Community Attribution Model

      ### 1. Attribution Categories

      **Acquisition Attribution**
      - Referral from community member
      - Conversion from community content
      - Event attendance → signup
      - Community mention in signup survey

      **Retention Attribution**
      - Community members vs non-members retention
      - Support tickets avoided (community answers)
      - Feature adoption from community content

      **Expansion Attribution**
      - Upsells influenced by community
      - Expansion from community education
      - Cross-sell from community exposure

      ### 2. Measurement Methods

      **Direct Attribution**
      ```
      Referral codes: Ambassador123 → trackable signup
      UTM parameters: ?ref=community-post-xyz
      Survey responses: "How did you hear about us?"
      ```

      **Influence Attribution**
      ```
      Community touchpoint before conversion:
      - Visited community within 30 days of signup
      - Consumed community content before purchase
      - Attended event before expansion
      ```

      **Cohort Comparison**
      ```
      Community members vs non-members:
      - Retention rate (Week 1, Month 1, Month 6)
      - Expansion rate
      - Support ticket volume
      - NPS score
      ```

      ### 3. ROI Calculation

      ```
      Community Value =
        (Attributed acquisition × CAC saved) +
        (Retention lift × LTV delta) +
        (Support deflection × Ticket cost) +
        (Content value × Production cost)

      Community Cost =
        Team cost +
        Platform cost +
        Program cost +
        Event cost

      ROI = (Value - Cost) / Cost
      ```

      ### 4. Dashboard Metrics

      | Category | Metric | Target |
      |----------|--------|--------|
      | Acquisition | Community-attributed signups | X/month |
      | Retention | Member vs non-member retention | +20% |
      | Support | Questions answered in community | 30% of volume |
      | Content | Community content views | Growing |
      | Advocacy | Net Promoter Score (members) | >60 |

  - name: Community Content Engine
    description: User-generated content for growth
    when_to_use: Leveraging community for content
    implementation: |
      ## Community Content Strategy

      ### 1. Content Types from Community

      **User-Generated Content**
      - Tutorials and how-tos
      - Use case showcases
      - Tips and tricks
      - Templates and examples

      **Collaborative Content**
      - Community + company co-creation
      - Expert interviews
      - Panel discussions
      - Community spotlights

      **Discussion Content**
      - Forum threads (SEO value)
      - Q&A (searchable knowledge)
      - Best practice threads
      - Feature discussions

      ### 2. Content Incentive Programs

      | Program | Incentive | Content Type |
      |---------|-----------|--------------|
      | Write for us | Payment + exposure | Long-form articles |
      | Tutorial bounty | Swag + credit | Tutorials |
      | Template contest | Prize + feature | Templates |
      | Share your story | Recognition | Case studies |

      ### 3. Content Quality Framework

      **Tier 1: Curated (High Bar)**
      - Edited and reviewed
      - Published on main channels
      - Company branding

      **Tier 2: Featured (Medium Bar)**
      - Light review
      - Community showcase
      - Author credit

      **Tier 3: Open (Low Bar)**
      - Community guidelines only
      - Forum/discussion format
      - Peer moderation

      ### 4. SEO Value Extraction

      ```
      Community content for SEO:
      1. Q&A threads → FAQ pages
      2. Discussion highlights → Blog posts
      3. Tutorial collection → Resource hub
      4. Problem-solution pairs → Landing pages
      ```

      ### 5. Content Metrics

      | Metric | Definition | Target |
      |--------|------------|--------|
      | UGC volume | Pieces created/month | Growing |
      | Content quality | Engagement rate | >5% |
      | SEO traffic | Traffic from community content | Growing |
      | Conversion | Content → Signup rate | >1% |

  - name: Community Platform Architecture
    description: Choosing and structuring community tools
    when_to_use: Setting up community infrastructure
    implementation: |
      ## Platform Decision Framework

      ### 1. Platform Options

      | Platform Type | Examples | Best For |
      |---------------|----------|----------|
      | Forum-style | Discourse, Circle | Deep discussions |
      | Chat-style | Discord, Slack | Real-time engagement |
      | Q&A-style | Stack Overflow-like | Support/knowledge |
      | Social-style | Custom, Tribe | Social networking |
      | Hybrid | Bettermode, Khoros | Multiple use cases |

      ### 2. Selection Criteria

      **Community Needs**
      - Real-time vs async preference
      - Content longevity importance
      - Structure vs spontaneity
      - Technical vs general audience

      **Business Needs**
      - SSO/integration requirements
      - Analytics needs
      - Moderation scale
      - Budget constraints

      ### 3. Common Architectures

      **Developer Community**
      ```
      Discord (real-time chat)
      + GitHub Discussions (code-related)
      + Discourse (long-form)
      ```

      **SaaS Community**
      ```
      Circle or Bettermode (primary)
      + Slack connect (customers)
      + Events platform
      ```

      **Enterprise Community**
      ```
      Custom or Khoros (branded)
      + SSO integration
      + CRM connection
      ```

      ### 4. Integration Architecture

      ```
      Community Platform
      ├── SSO (product login)
      ├── CRM (member data)
      ├── Product (usage data)
      ├── Analytics (engagement tracking)
      ├── Support (ticket deflection)
      └── Events (registration)
      ```

      ### 5. Migration Considerations

      | From | To | Considerations |
      |------|----|----------------|
      | Free Slack | Paid platform | Content export, member migration |
      | Facebook | Owned platform | Reduced reach, better data |
      | Forum | Chat | Different engagement patterns |

anti_patterns:
  - name: Community Theater
    description: Launching community without strategy
    why_bad: |
      Empty community is worse than none.
      Signals neglect to users.
      Costs resources without return.
    what_to_do_instead: |
      Start with 50-100 engaged users.
      Validate community need first.
      Seed with content and activity.

  - name: Corporate Capture
    description: Making community feel like marketing channel
    why_bad: |
      Users detect inauthenticity.
      Kills organic engagement.
      Drives away best advocates.
    what_to_do_instead: |
      Community-first, company-second.
      Let users lead discussions.
      Promotional content < 10%.

  - name: Vanity Metrics Focus
    description: Optimizing member count over engagement
    why_bad: |
      Large inactive communities look bad.
      Engagement rate crashes.
      No business impact.
    what_to_do_instead: |
      Focus on engagement rate.
      Quality > quantity.
      Measure business outcomes.

  - name: Platform Hopping
    description: Constantly changing community platforms
    why_bad: |
      Loses community history.
      Frustrates members.
      Resets growth.
    what_to_do_instead: |
      Choose platform for 3+ years.
      Migrate only with clear ROI.
      Preserve content when moving.

  - name: Ignoring Power Users
    description: No special treatment for top contributors
    why_bad: |
      Power users drive majority of value.
      They leave without recognition.
      Community becomes generic.
    what_to_do_instead: |
      Identify and nurture top 10%.
      Create tiered recognition.
      Give exclusive access and benefits.

handoffs:
  - trigger: "growth loop|viral|acquisition"
    to: growth-loops
    context: "Need loop design with community component"

  - trigger: "self-serve|PLG|activation"
    to: product-led-growth
    context: "Need PLG strategy with community layer"

  - trigger: "overall strategy|go-to-market"
    to: growth-strategy
    context: "Need strategic growth planning"

  - trigger: "content strategy|blog|SEO"
    to: content-marketing
    context: "Need content strategy for community"

  - trigger: "developer|API|documentation"
    to: developer-relations
    context: "Need developer-specific community"
