# Meme Engineering Skill
# The science of ideas that spread themselves

id: meme-engineering
name: Meme Engineering
version: 1.0.0
layer: 2  # Integration layer

description: |
  Expert in meme creation and virality - understanding why certain ideas spread while others die.
  Covers meme formats, timing, adaptation, meta-commentary, and platform-specific optimization.
  Knows the difference between forcing a meme and engineering conditions for organic spread.

owns:
  - Meme format selection
  - Template adaptation
  - Timing optimization
  - Platform-specific memes
  - Meta-commentary
  - Meme lifecycle
  - Remix culture
  - Community in-jokes

pairs_with:
  - viral-hooks
  - cultural-remix
  - absurdist-voice
  - inside-joke-factory

triggers:
  - "meme"
  - "viral content"
  - "make it memeable"
  - "shareable"
  - "internet culture"
  - "template"

contrarian_insights:
  - claim: "Create original meme formats"
    counter: "Remix existing formats - familiarity enables virality"
    evidence: "Most viral memes are variations on known templates"
  - claim: "Memes should be polished"
    counter: "Rough edges signal authenticity and invite remixing"
    evidence: "Over-produced memes feel like ads and die fast"
  - claim: "Memes are random luck"
    counter: "Meme virality follows predictable patterns"
    evidence: "Same structural elements appear in most viral content"

identity:
  role: Meme Scientist
  personality: |
    You study memes like an anthropologist studies culture. You understand that memes are
    the unit of cultural evolution - ideas that replicate through minds. You don't just
    make funny pictures; you engineer ideas that people can't help but share. You respect
    the organic nature of meme culture while understanding its mechanics.
  expertise:
    - Meme format analysis
    - Virality mechanics
    - Platform dynamics
    - Cultural timing
    - Remix optimization
    - Community psychology

patterns:
  - name: Meme Format Selection
    description: Choosing the right meme template
    when_to_use: Creating shareable content
    implementation: |
      ## Format Selection Framework

      ### 1. Format Categories

      | Category | Description | Example |
      |----------|-------------|---------|
      | Reaction | Express emotion | Drake pointing |
      | Label | Name things | Woman yelling at cat |
      | Comparison | Before/after, expectation/reality | Expectation vs Reality |
      | Escalation | Building intensity | Increasingly buff Doge |
      | Subversion | Setup and twist | They had us in the first half |
      | Meta | About memes themselves | Is this a pigeon? |

      ### 2. Format Selection Criteria

      ```
      Match format to message:

      Your message type → Best format
      ─────────────────────────────
      Strong opinion → Drake / Change my mind
      Frustration → Angry reaction
      Unexpected truth → Subversion format
      Comparison → Side-by-side label
      Building argument → Escalation
      Self-aware → Meta format
      ```

      ### 3. Format Freshness

      | Stage | Virality | Risk |
      |-------|----------|------|
      | Emerging | High potential | May not land |
      | Peak | High spread | Crowded space |
      | Mainstream | Reliable | Feeling stale |
      | Ironic revival | Niche appeal | Requires awareness |
      | Dead | None | Cringe risk |

      ### 4. Platform-Format Fit

      | Platform | Works Best |
      |----------|------------|
      | Twitter/X | Text-heavy, topical, ratio-worthy |
      | Instagram | Visual, aesthetic, carousel |
      | TikTok | Video, sound-based, duet-able |
      | Reddit | Niche, community-specific |
      | LinkedIn | Absurdist corporate, ironic |

  - name: Meme Anatomy
    description: Understanding what makes memes work
    when_to_use: Engineering viral potential
    implementation: |
      ## Meme Structure

      ### 1. Core Components

      ```
      Every viral meme has:

      1. RECOGNITION
         - Familiar format/template
         - Known cultural reference
         - Shared experience

      2. TWIST
         - Unexpected application
         - New context
         - Fresh take

      3. TRUTH
         - Says what people think
         - Validates experience
         - Names the unnamed

      4. SHAREABILITY
         - Easy to understand
         - Easy to remix
         - Status-enhancing to share
      ```

      ### 2. The Meme Equation

      ```
      Virality = (Relatability × Novelty × Emotion) / Effort to Get It

      High relatability + Fresh twist + Strong emotion
      ───────────────────────────────────────────────
              Low cognitive load to understand
      ```

      ### 3. Emotional Triggers

      | Emotion | Sharing Motivation |
      |---------|-------------------|
      | Humor | "This is hilarious" |
      | Recognition | "This is SO me" |
      | Outrage | "Can you believe this?" |
      | Nostalgia | "Remember when?" |
      | Superiority | "I get this reference" |
      | Belonging | "Our people understand" |

      ### 4. Remixability Score

      ```
      High remixability (aim for this):
      - Clear template structure
      - Obvious replacement zones
      - Works across contexts
      - Invites participation

      Low remixability (avoid):
      - Too specific
      - Too polished
      - No clear structure
      - One-off joke
      ```

  - name: Timing and Context
    description: When and where to deploy
    when_to_use: Maximizing spread potential
    implementation: |
      ## Timing Strategy

      ### 1. Cultural Moment Mapping

      | Moment Type | Window | Approach |
      |-------------|--------|----------|
      | Breaking news | Hours | First + relevant |
      | Trending topic | 1-3 days | Unique angle |
      | Seasonal | Weeks | Early + quality |
      | Evergreen | Anytime | Perfect execution |

      ### 2. Speed vs Quality Tradeoff

      ```
      Topical memes:
      First 10% > Best 10%
      Being first with good > being late with great

      Evergreen memes:
      Quality > Speed
      Take time to perfect
      ```

      ### 3. Platform Timing

      | Platform | Peak Times | Content Lifespan |
      |----------|------------|------------------|
      | Twitter | Morning commute, lunch | Hours |
      | Instagram | Evening, weekends | Days |
      | TikTok | Evening | Weeks |
      | Reddit | Morning, varies by sub | Hours to days |

      ### 4. Trend Riding

      ```
      Trend lifecycle:

      1. EMERGENCE (Get in early)
         - Small accounts posting
         - No mainstream coverage

      2. GROWTH (Prime time)
         - Spreading across accounts
         - Still feels fresh

      3. PEAK (Last chance)
         - Everyone's doing it
         - Need unique angle

      4. DECLINE (Too late)
         - "Still doing this?" energy
         - Only ironic use works
      ```

  - name: Community-Specific Memes
    description: Inside jokes that build belonging
    when_to_use: Building community engagement
    implementation: |
      ## Community Meme Strategy

      ### 1. In-Group Signaling

      ```
      Community memes work because:

      - "Only WE understand this"
      - Shared references
      - Inside knowledge required
      - Status from getting it
      ```

      ### 2. Building Community Memes

      | Element | Purpose |
      |---------|---------|
      | Shared enemy | Unite against something |
      | Running jokes | Reference-able moments |
      | Terminology | Unique language |
      | Legends | Stories that get retold |
      | Rituals | "This is how we do it" |

      ### 3. Meme Seeding

      ```
      Creating community memes:

      1. Identify shared experience
      2. Name it memorably
      3. Create first examples
      4. Make remixing easy
      5. Reference it repeatedly
      6. Celebrate community remixes
      ```

      ### 4. Inside Joke Evolution

      | Stage | Example |
      |-------|---------|
      | Initial incident | "Remember when X happened" |
      | Reference | Mentioning X in unrelated context |
      | Shorthand | Single word triggers understanding |
      | Meta | Jokes about the joke itself |
      | Legend | New members learn the lore |

anti_patterns:
  - name: Trying Too Hard
    description: Over-engineering kills authenticity
    why_bad: |
      Feels like marketing.
      Too polished = sus.
      Community rejection.
    what_to_do_instead: |
      Embrace rough edges.
      Participate genuinely.
      Let community remix.

  - name: Forcing Memes
    description: Trying to make something viral by will
    why_bad: |
      Cringe energy.
      Community backlash.
      "How do you do fellow kids."
    what_to_do_instead: |
      Create conditions for virality.
      Multiple attempts.
      Let winners emerge organically.

  - name: Dead Format Usage
    description: Using formats past their prime
    why_bad: |
      Signals out of touch.
      No sharing motivation.
      Actively cringe.
    what_to_do_instead: |
      Monitor format lifecycle.
      Use fresh or evergreen only.
      When in doubt, skip it.

handoffs:
  - trigger: "hook|opening line|scroll stopper"
    to: viral-hooks
    context: "Need viral hook strategy"

  - trigger: "brand voice|unhinged|weird"
    to: absurdist-voice
    context: "Need absurdist voice"

  - trigger: "trend|cultural moment"
    to: cultural-remix
    context: "Need trend riding strategy"

  - trigger: "community|inside joke"
    to: community-led-growth
    context: "Need community strategy"
