import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TEMPLATES_DIR = path.join(__dirname, '..', 'templates');

/**
 * Scaffold a new project from config
 */
export async function scaffoldProject(config, targetDir) {
  // Create project directory
  await fs.mkdir(targetDir, { recursive: true });

  // Create subdirectories
  await fs.mkdir(path.join(targetDir, 'docs'), { recursive: true });
  await fs.mkdir(path.join(targetDir, 'skills'), { recursive: true });
  await fs.mkdir(path.join(targetDir, '.claude'), { recursive: true });

  // Generate and write files
  await Promise.all([
    writeClaudeMd(config, targetDir),
    writeStateJson(config, targetDir),
    writeTaskQueue(config, targetDir),
    writePrdTemplate(config, targetDir),
    writeArchitectureTemplate(config, targetDir),
    writeSkillSchema(targetDir),
    copySkills(config, targetDir),
    writeClaudeSettings(config, targetDir)
  ]);

  return targetDir;
}

async function writeClaudeMd(config, targetDir) {
  const behaviors = config.behaviors || { mandatory: [], selected: [] };
  const allBehaviors = [...(behaviors.mandatory || []), ...(behaviors.selected || [])];

  const content = `# ${config.project_name}

> ${config.description || 'A VibeShip project'}

---

## Quick Start

This project was scaffolded with VibeShip Orchestrator.

Run \`claude\` to start building.

---

## Stack

### Agents
${config.agents.map(a => `- ${a}`).join('\n')}

### MCPs
${config.mcps.map(m => `- ${m}`).join('\n')}

### Build Disciplines
${allBehaviors.map(b => `- ${b}`).join('\n') || '- None selected'}

---

## Project State

- \`state.json\` - Current phase and decisions
- \`task_queue.json\` - Task breakdown and progress
- \`docs/PRD.md\` - Product requirements
- \`docs/ARCHITECTURE.md\` - Technical decisions

---

## Commands

| Command | Action |
|---------|--------|
| \`status\` | Show current phase and progress |
| \`continue\` | Resume from last checkpoint |
| \`replan\` | Go back to planning phase |

---

Built with VibeShip. "You vibe. It ships."
`;

  await fs.writeFile(path.join(targetDir, 'CLAUDE.md'), content);
}

async function writeStateJson(config, targetDir) {
  const state = {
    version: 1,
    project_name: config.project_name,
    description: config.description || '',
    phase: 'planning',
    discovery: config.discovery || {},
    stack: {
      agents: config.agents,
      mcps: config.mcps
    },
    behaviors: config.behaviors || { mandatory: [], selected: [] },
    custom_skills_needed: config.custom_skills_needed || [],
    checkpoint: {
      last_task: null,
      timestamp: new Date().toISOString()
    },
    decisions: [],
    assumptions: []
  };

  await fs.writeFile(
    path.join(targetDir, 'state.json'),
    JSON.stringify(state, null, 2)
  );
}

async function writeTaskQueue(config, targetDir) {
  const queue = {
    version: 1,
    tasks: []
  };

  await fs.writeFile(
    path.join(targetDir, 'task_queue.json'),
    JSON.stringify(queue, null, 2)
  );
}

async function writePrdTemplate(config, targetDir) {
  const content = `# Product Requirements Document

## Project: ${config.project_name}

### Overview

${config.description || '[To be filled by planner]'}

---

### Problem Statement

[What problem does this solve?]

---

### Target User

[Who is this for?]

---

### Core Features

[Priority ordered list of features]

1.
2.
3.

---

### Out of Scope (V1)

[What are we NOT building?]

-

---

### Success Criteria

[How do we know this works?]

-

---

*Generated by VibeShip Orchestrator*
`;

  await fs.writeFile(path.join(targetDir, 'docs', 'PRD.md'), content);
}

async function writeArchitectureTemplate(config, targetDir) {
  const content = `# Architecture

## Project: ${config.project_name}

---

### System Overview

[High-level system diagram]

---

### Tech Stack

| Layer | Technology |
|-------|------------|
| Frontend | [TBD] |
| Backend | [TBD] |
| Database | [TBD] |
| Auth | [TBD] |

---

### File Structure

\`\`\`
${config.project_name}/
├── src/
├── docs/
└── ...
\`\`\`

---

### Data Models

[Key entities and relationships]

---

### API Routes

[Key endpoints]

---

### Key Decisions

| Decision | Rationale |
|----------|-----------|
| | |

---

*Generated by VibeShip Orchestrator*
`;

  await fs.writeFile(path.join(targetDir, 'docs', 'ARCHITECTURE.md'), content);
}

async function writeSkillSchema(targetDir) {
  const content = `# Skill Schema

> Shared protocols for all skills

---

## State Management

All skills must read/write state through these files:

| File | Purpose |
|------|---------|
| \`state.json\` | Current phase, decisions, assumptions |
| \`task_queue.json\` | Tasks and their status |

---

## Mandatory Behaviors

Before marking ANY task complete:

1. **Verify** - Run the code/tests, confirm working
2. **Architecture check** - Confirm no deviation from ARCHITECTURE.md
3. **Security scan** - Check for secrets, validate inputs
4. **Maintainability** - Clear naming, no magic numbers, logical structure

---

## Task Status

| Status | Meaning |
|--------|---------|
| \`pending\` | Not started |
| \`in_progress\` | Currently working |
| \`completed\` | Done and verified |
| \`blocked\` | Waiting on something |

---

## Handoff Protocol

When completing a task:

1. Update task status in \`task_queue.json\`
2. Update checkpoint in \`state.json\`
3. Return control to planner

---

*VibeShip Orchestrator Schema v1*
`;

  await fs.writeFile(path.join(targetDir, 'skills', '_schema.md'), content);
}

async function copySkills(config, targetDir) {
  // For now, create placeholder skill files
  // In production, these would be copied from a skills repository

  const plannerSkill = `# Planner Skill

> The brain of VibeShip Orchestrator

You are the VibeShip Planner. You orchestrate the entire project lifecycle.

## Your Job

1. Read state.json to understand current phase
2. If phase is 'planning', generate PRD and ARCHITECTURE
3. Decompose into tasks in task_queue.json
4. Execute tasks by loading appropriate skills
5. Verify each task before marking complete

## Phases

| Phase | Purpose |
|-------|---------|
| planning | Generate PRD, architecture, task breakdown |
| building | Execute tasks via skills |
| review | Summarize, get feedback |

---

*Always read skills/_schema.md first*
`;

  await fs.writeFile(path.join(targetDir, 'skills', 'planner.md'), plannerSkill);

  // Create placeholder for each selected agent
  for (const agent of config.agents) {
    if (agent === 'planner') continue; // Already created

    const skillContent = `# ${agent.charAt(0).toUpperCase() + agent.slice(1)} Skill

> Agent: ${agent}

---

## Identity

You are the ${agent} agent for this project.

---

## Capabilities

[To be customized based on project needs]

---

*Always read skills/_schema.md first*
`;

    await fs.writeFile(path.join(targetDir, 'skills', `${agent}.md`), skillContent);
  }
}

async function writeClaudeSettings(config, targetDir) {
  const settings = {
    version: 1,
    project: config.project_name,
    mcps: config.mcps
  };

  await fs.writeFile(
    path.join(targetDir, '.claude', 'settings.json'),
    JSON.stringify(settings, null, 2)
  );
}
