# SEO Skill
# Search engine optimization for startups

id: seo
name: SEO
category: marketing
description: |
  Search engine optimization for startups. Covers technical SEO, content
  strategy, and link building. Focus on sustainable approaches that compound
  over time rather than tricks that get penalized.

triggers:
  - seo
  - search engine optimization
  - organic traffic
  - google ranking
  - keyword research
  - backlinks
  - content strategy
  - search visibility

principles:
  - name: Solve Real Problems
    description: |
      The best SEO strategy is creating content that genuinely helps people.
      Google gets better at detecting quality. Helpful content wins long term.
      Write for humans first, optimize for search second.
    examples:
      - Answer questions your customers actually ask
      - Create resources you would bookmark yourself
      - Depth over breadth on topics you own
      - Update content to stay accurate

  - name: Technical Foundation First
    description: |
      Before content, ensure technical basics are solid. Fast loading,
      mobile friendly, crawlable, proper structure. Technical issues can
      tank otherwise good content.
    examples:
      - Core Web Vitals passing
      - Mobile-first design
      - Clean URL structure
      - Proper meta tags and schema

  - name: Compound Over Time
    description: |
      SEO is a long game. Results take 6-12 months. But they compound.
      One good piece of content can drive traffic for years. Invest in
      evergreen content that ages well.
    examples:
      - Evergreen topics over news
      - Update old content regularly
      - Build topical authority over time
      - Internal linking strategy

  - name: Match Search Intent
    description: |
      Ranking is not enough if content does not match what searcher wants.
      Understand intent: informational, navigational, transactional.
      Match content format to intent.
    examples:
      - How-to queries want tutorials
      - Best X queries want comparisons
      - Buy X queries want product pages
      - Check SERPs to understand intent

  - name: Earn Links Naturally
    description: |
      Backlinks still matter but must be earned. Create linkable assets.
      Original research, tools, comprehensive guides. Things people
      naturally want to reference.
    examples:
      - Original research and data
      - Free tools that solve problems
      - Definitive guides on topics
      - Expert roundups and interviews

patterns:
  - name: Skyscraper Technique
    description: Find top-ranking content, create better version, earn their links
    when: Building backlinks in competitive topic areas
    example: |
      Step 1: Find high-ranking content with many backlinks (Ahrefs)
      Example: "Email marketing guide" has 500 backlinks

      Step 2: Create superior version (longer, updated, better examples, video)
      Your guide: 10k words vs their 3k, 2025 data, interactive examples

      Step 3: Reach out to sites linking to old version
      "Hey, saw you linked to [old guide]. We created [new guide] with updated
      2025 tactics and video tutorials. Might be valuable for your readers."

      Conversion rate: 5-10% of outreach typically links back.

  - name: Internal Linking Hierarchy
    description: Use internal links to distribute authority and guide crawlers
    when: You have multiple pages competing for same keywords or orphaned content
    example: |
      Structure:
      Homepage → Category pages → Subcategory pages → Individual articles

      Link from high-authority pages (homepage) to important pages.
      Link from new content to older pillar content.
      Use descriptive anchor text (not "click here").

      Example:
      Blog post on "email subject lines" links to pillar "email marketing guide"
      with anchor text "comprehensive email marketing strategies"

      Tools: Screaming Frog to find orphaned pages (no internal links)

  - name: Featured Snippet Optimization
    description: Structure content to capture position zero in search results
    when: Targeting informational queries with high search volume
    example: |
      Query type → Format:
      - "How to X" → Numbered steps (H2 for each step)
      - "What is X" → Short paragraph definition (40-60 words)
      - "Best X" → Bulleted list with brief explanations
      - "X vs Y" → Comparison table

      Example for "what is SEO":
      <p>SEO (Search Engine Optimization) is the practice of improving
      website visibility in organic search results by optimizing content,
      technical structure, and backlink profile to match search engine
      ranking algorithms and user intent.</p>

      Keep under 60 words. Use simple language. Answer directly.

  - name: Search Intent Clustering
    description: Group keywords by intent to create right content format
    when: Planning content strategy with keyword research
    example: |
      Keyword: "project management"

      Informational: "what is project management" → Guide/definition
      Navigational: "asana project management" → Product page
      Commercial: "best project management software" → Comparison post
      Transactional: "buy project management software" → Pricing page

      Don't create blog post for transactional intent. Match format to intent.

  - name: E-E-A-T Optimization
    description: Demonstrate Experience, Expertise, Authoritativeness, Trustworthiness
    when: Creating content in YMYL (Your Money Your Life) categories
    example: |
      Experience: Author bylines with credentials, case studies, real examples
      Expertise: Detailed technical content, original research, citations
      Authoritativeness: Backlinks from authoritative sites, media mentions
      Trustworthiness: HTTPS, clear privacy policy, contact info, reviews

      For medical content: Author must be MD. For legal: JD. For finance: CFP.
      Google heavily weights credentials in YMYL topics.

  - name: Content Refresh Strategy
    description: Update existing content to maintain and improve rankings
    when: You have aged content that's declining in rankings
    example: |
      Quarterly audit:
      1. Export pages losing traffic (Search Console)
      2. Check if ranking dropped or search volume declined
      3. For dropped rankings: Update content

      Updates:
      - Refresh statistics and data (current year)
      - Add new sections for recent developments
      - Improve depth and examples
      - Update title to current year "Best X (2025)"
      - Add new internal links to recent content

      Re-publish with updated date. Often regains rankings within 2-4 weeks.

anti_patterns:
  - name: Keyword Stuffing
    description: Unnaturally repeating keywords hoping to rank
    indicators:
      - Same phrase repeated excessively
      - Awkward phrasing to fit keywords
      - Keyword density focus
    instead: Write naturally, include keywords where they fit

  - name: Thin Content At Scale
    description: Publishing lots of low-quality pages for keyword coverage
    indicators:
      - Many short pages with little value
      - AI-generated without human review
      - Pages that exist for SEO not users
    instead: Fewer pages with more depth and value

  - name: Black Hat Tactics
    description: Manipulative techniques that risk penalties
    indicators:
      - Buying links
      - Private blog networks
      - Cloaking or hidden text
    instead: Earn rankings through quality and value

  - name: Ignoring Technical Issues
    description: Focusing on content while site has fundamental problems
    indicators:
      - Slow page loads
      - Poor mobile experience
      - Crawl errors in Search Console
    instead: Fix technical foundation before scaling content

  - name: Chasing Algorithm Updates
    description: Constantly changing strategy based on every Google update
    indicators:
      - Reactive strategy changes
      - Following every SEO news story
      - Short-term tactics
    instead: Focus on fundamentals that survive all updates

guidance:
  vibe-coder: |
    SEO means getting found on Google. The basics:

    1. What questions do your customers type into Google?
    2. Write helpful answers to those questions
    3. Make sure your site loads fast and works on phones
    4. Get other sites to link to your content

    It takes months to see results. Start now, be patient.

  builder: |
    SEO fundamentals for startups:

    Technical checklist:
    - Site loads in under 3 seconds
    - Mobile-friendly design
    - HTTPS enabled
    - Clean URL structure (/topic/subtopic)
    - XML sitemap submitted to Search Console

    Content approach:
    - List 50 questions your customers ask
    - Write definitive answers to top 10
    - One topic cluster you can own
    - Update content quarterly

    Start with Search Console - its free and shows what you rank for.

  developer: |
    Technical SEO for developers:

    Performance (Core Web Vitals):
    - LCP < 2.5s, FID < 100ms, CLS < 0.1
    - Image optimization (WebP, lazy loading)
    - Code splitting and caching
    - CDN for static assets

    Crawlability:
    - robots.txt properly configured
    - Sitemap auto-generated and submitted
    - Clean URLs (no parameters for important pages)
    - Proper canonicals for duplicate content

    Structured data:
    - JSON-LD for relevant schema types
    - Organization, Product, FAQ, HowTo as applicable
    - Test with Rich Results Test

    Pre-rendering for SPAs if needed.

  expert: |
    SEO strategy framework:

    Keyword research:
    - Seed keywords from customer conversations
    - Expand with Ahrefs/SEMrush
    - Map to funnel stage (awareness, consideration, decision)
    - Prioritize: volume x relevance x difficulty

    Content architecture:
    - Pillar pages for main topics
    - Cluster content linking to pillars
    - Internal linking strategy
    - Content refresh schedule

    Link building:
    - Linkable asset creation (tools, research, guides)
    - Digital PR for original data
    - Strategic guest posting
    - Broken link building

    Measurement:
    - Rank tracking for target keywords
    - Organic traffic by page
    - Conversions from organic
    - Page-level engagement metrics

handoff:
  before:
    - Have a website with basic content
    - Understand target customer
  after:
    - Content calendar execution
    - Link building campaigns
  related_skills:
    - marketing-fundamentals
    - analytics

sources:
  - Google Search Central documentation
  - Ahrefs blog and courses
  - Moz Beginners Guide to SEO
  - Backlinko case studies
