# SEO Skill
# Search engine optimization for startups

id: seo
name: SEO
category: marketing
description: |
  Search engine optimization for startups. Covers technical SEO, content
  strategy, and link building. Focus on sustainable approaches that compound
  over time rather than tricks that get penalized.

triggers:
  - seo
  - search engine optimization
  - organic traffic
  - google ranking
  - keyword research
  - backlinks
  - content strategy
  - search visibility

principles:
  - name: Solve Real Problems
    description: |
      The best SEO strategy is creating content that genuinely helps people.
      Google gets better at detecting quality. Helpful content wins long term.
      Write for humans first, optimize for search second.
    examples:
      - Answer questions your customers actually ask
      - Create resources you would bookmark yourself
      - Depth over breadth on topics you own
      - Update content to stay accurate

  - name: Technical Foundation First
    description: |
      Before content, ensure technical basics are solid. Fast loading,
      mobile friendly, crawlable, proper structure. Technical issues can
      tank otherwise good content.
    examples:
      - Core Web Vitals passing
      - Mobile-first design
      - Clean URL structure
      - Proper meta tags and schema

  - name: Compound Over Time
    description: |
      SEO is a long game. Results take 6-12 months. But they compound.
      One good piece of content can drive traffic for years. Invest in
      evergreen content that ages well.
    examples:
      - Evergreen topics over news
      - Update old content regularly
      - Build topical authority over time
      - Internal linking strategy

  - name: Match Search Intent
    description: |
      Ranking is not enough if content does not match what searcher wants.
      Understand intent: informational, navigational, transactional.
      Match content format to intent.
    examples:
      - How-to queries want tutorials
      - Best X queries want comparisons
      - Buy X queries want product pages
      - Check SERPs to understand intent

  - name: Earn Links Naturally
    description: |
      Backlinks still matter but must be earned. Create linkable assets.
      Original research, tools, comprehensive guides. Things people
      naturally want to reference.
    examples:
      - Original research and data
      - Free tools that solve problems
      - Definitive guides on topics
      - Expert roundups and interviews

anti_patterns:
  - name: Keyword Stuffing
    description: Unnaturally repeating keywords hoping to rank
    indicators:
      - Same phrase repeated excessively
      - Awkward phrasing to fit keywords
      - Keyword density focus
    instead: Write naturally, include keywords where they fit

  - name: Thin Content At Scale
    description: Publishing lots of low-quality pages for keyword coverage
    indicators:
      - Many short pages with little value
      - AI-generated without human review
      - Pages that exist for SEO not users
    instead: Fewer pages with more depth and value

  - name: Black Hat Tactics
    description: Manipulative techniques that risk penalties
    indicators:
      - Buying links
      - Private blog networks
      - Cloaking or hidden text
    instead: Earn rankings through quality and value

  - name: Ignoring Technical Issues
    description: Focusing on content while site has fundamental problems
    indicators:
      - Slow page loads
      - Poor mobile experience
      - Crawl errors in Search Console
    instead: Fix technical foundation before scaling content

  - name: Chasing Algorithm Updates
    description: Constantly changing strategy based on every Google update
    indicators:
      - Reactive strategy changes
      - Following every SEO news story
      - Short-term tactics
    instead: Focus on fundamentals that survive all updates

guidance:
  vibe-coder: |
    SEO means getting found on Google. The basics:

    1. What questions do your customers type into Google?
    2. Write helpful answers to those questions
    3. Make sure your site loads fast and works on phones
    4. Get other sites to link to your content

    It takes months to see results. Start now, be patient.

  builder: |
    SEO fundamentals for startups:

    Technical checklist:
    - Site loads in under 3 seconds
    - Mobile-friendly design
    - HTTPS enabled
    - Clean URL structure (/topic/subtopic)
    - XML sitemap submitted to Search Console

    Content approach:
    - List 50 questions your customers ask
    - Write definitive answers to top 10
    - One topic cluster you can own
    - Update content quarterly

    Start with Search Console - its free and shows what you rank for.

  developer: |
    Technical SEO for developers:

    Performance (Core Web Vitals):
    - LCP < 2.5s, FID < 100ms, CLS < 0.1
    - Image optimization (WebP, lazy loading)
    - Code splitting and caching
    - CDN for static assets

    Crawlability:
    - robots.txt properly configured
    - Sitemap auto-generated and submitted
    - Clean URLs (no parameters for important pages)
    - Proper canonicals for duplicate content

    Structured data:
    - JSON-LD for relevant schema types
    - Organization, Product, FAQ, HowTo as applicable
    - Test with Rich Results Test

    Pre-rendering for SPAs if needed.

  expert: |
    SEO strategy framework:

    Keyword research:
    - Seed keywords from customer conversations
    - Expand with Ahrefs/SEMrush
    - Map to funnel stage (awareness, consideration, decision)
    - Prioritize: volume x relevance x difficulty

    Content architecture:
    - Pillar pages for main topics
    - Cluster content linking to pillars
    - Internal linking strategy
    - Content refresh schedule

    Link building:
    - Linkable asset creation (tools, research, guides)
    - Digital PR for original data
    - Strategic guest posting
    - Broken link building

    Measurement:
    - Rank tracking for target keywords
    - Organic traffic by page
    - Conversions from organic
    - Page-level engagement metrics

handoff:
  before:
    - Have a website with basic content
    - Understand target customer
  after:
    - Content calendar execution
    - Link building campaigns
  related_skills:
    - marketing-fundamentals
    - analytics

sources:
  - Google Search Central documentation
  - Ahrefs blog and courses
  - Moz Beginners Guide to SEO
  - Backlinko case studies
